### ISSUE TITLE
Canonical URL per Page

### ISSUE THREAD

**Issue by alexanderloewe** [nystudio107/craft-seomatic#1014]
Is there a way to config an individual canonical field in the section configs?

If this is empty, the entry URL is taken?

<img width="1465" alt="Bildschirmfoto 2021-11-17 um 20 46 09" src="https://user-images.githubusercontent.com/69263307/142272153-1be4f940-5d8a-4781-aee8-241a5baf5610.png">

**Comment by khalwat** [comment]
No. If you need to override the canonical URL for individual entries, you'd use the SEO Settings field to override it on a per-entry basis.

**Comment by alexanderloewe** [comment]
In my case, I can't do that because we have 5k + entries in the installation with individual Craft plain text fields.

I think it should be an option with can be configured like the other fields. In my opinion, there is no reason why the other fields can be configured, but the canonical field isn't.

**Comment by khalwat** [comment]
When you say "Configured" what is it that you mean?

You can put arbitrary Twig code into that field, so you should be able to do pretty much whatever you like.

What is your desired outcome here?

You could do something like:

```twig
{{ entry.someField ??? entry.url }}
```

Which will cause it to use the value in `entry.SomeField` if it is present and not empty, otherwise it will fall back on `entry.url`

ref: https://nystudio107.com/docs/seomatic/using.html#seomatic%E2%80%99s-empty-coalesce-operator

**Comment by alexanderloewe** [comment]
I misunderstood your first answer. It came across as if I had to use the SEO field from the plugin.

{ entry.canonical ??? entry.url } does the trick in my case just fine. Thanks Andrew!
