### ISSUE TITLE
Add global identifier to structured data for products in Craft Commerce

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-seomatic#1026]
Out of the box SEOmatic supports some structured data for products. However, after a new launch of a Commerce website, I was alerted by Google Search Console of some warnings.

The following warnings were found on your site:
Missing field 'review'
Missing field 'priceValidUntil'
Missing field 'aggregateRating'
No global identifier provided (e.g. gtin, mpn, isbn)
Missing field 'brand'

Whilst most of these fields cannot be assumed, I believe we could assume and use the `SKU` for the `global identifier` and auto populate this. 

As mentioned on Discord, this is a feature request to include this in SEOmatic.

**Comment by khalwat** [comment]
So the issue here is that there is no "global identifier" field, but rather fields that _can_ be used as a global identifier if they make sense:

* GTIN8 – a code used for items that are too small to fit the usual 12-14 digits. 
* GTIN12 / UPC  and GTIN13 / EAN – the most common codes, used in North America (UPC) and outside of North America  (EAN). 
* GTIN14 / ITF-14: a code used for packaged products that contain multiple individual items such as a pack of canned sodas. 
* ISBN: stands for “International Standard Book Number” and it is used, of course, for books. 
* MPN: stands for Manufacturer part number. These numbers are typically found on machines and hardware that contain different parts. 

My issue here is having SEOmatic try to decide for you what makes sense. Obviously, ISBN as a global identifier isn't going to make sense for anything other than a book, for example.

I think this is again something that you should automate via custom Twig code as needed, as per: 

https://nystudio107.com/blog/annotated-json-ld-structured-data-examples
