### ISSUE TITLE
Keyword analysis in SEOmatic

### ISSUE THREAD

**Issue by hcaandersen** [nystudio107/craft-seomatic#1035]
I've come across from Wordpress with Yoast to CraftCMS with SEOmatic. I'm really missing the keyword analysis feature in Yoast, where you can enter a set of keywords for a **specific page** and get feedback on how effective the page is for those keywords. Is there anything like that in SEOmatic?

**Comment by khalwat** [comment]
Currently, there is not. The old SEOmatic for Craft 2 had this in there, but we found than many people relied on external tools to do keyword checking.

However, I do agree that it's nice for content authors, so it's something that will be coming!

**Comment by garycrane** [comment]
Would love to see this added for SEOmatic. Any update on when/if this might be coming? The client wants me to look at the EtherSEO plugin but I'm nervous about using it due to bugs and support issues. They've come from WordPress, love using Craft but really miss the tools that Yoast gave them. Thoughts?
