### ISSUE TITLE
Support for cache prefix/affix?

### ISSUE THREAD

**Issue by spharion88** [nystudio107/craft-seomatic#1048]
Changing the seoTitle based on a query/get parameter is only possible combined with a clearCache call (as described here https://github.com/nystudio107/craft-seomatic/issues/325). 

Is there a reason why {% do seomatic.meta.seoTitle() %} doesn't include the clearCache call itself?

Wouldn't it be a nicer solution to allow cache prefixes/affixes similar to the how the {% cache %} tag works?
That would give the user the possibility to cache specific query params and if not used to excessive cache flooding still won't be an issue.

**Comment by khalwat** [comment]
You can do that now via the `allowedUrlParams` setting -> https://github.com/nystudio107/craft-seomatic/blob/develop/src/config.php#L160

**Comment by hiasl** [comment]
Would it be possible to make this configurable via TWIG to be able to limit it to certain use cases / templates / sections / URLs?

**Comment by khalwat** [comment]
What's the use-case for this? I'm thinking per-section URL params might be getting a little bit too involved.

**Comment by hiasl** [comment]
No, definitely not per-section. I do not event think it's a good idea to configure it generally via any config file (that includes the current implementation mentioned above).

Generally: There are cases where you want to have title variants depending on a certain GET parameter, but not necessarily a different cache version for each variant of the GET value. That means you probably only need 2 different cache variants although of course you have an unlimited amount of variants GET values.

Setting it per TWIG would especially allow prevention of ballooning the cache because you can validate your input first.

I think Craft's cache tag with its key option is a very good example how it could be done, but maybe as an appendix to your current cache key instead of completely setting it as a whole to prevent any conflict with your current cache solution.

And here's a use case:
We have an event overview, which we can optionally (via a filter) limit to a certain month / year. Month and year passed as a GET var, if selected in the filter. Once something's chosen here (which is easy to validate as well), the title of the page should reflect the selection.

If we enabled the 2 GET params via config, it could flood the cache. We just need to verify if the values passed in are correct and then set a cache key appendix and a modification of the title, e.g. 
```
{% do seomatic.cache.keyAppend('November-2020') %}
{% do seomatic.meta.seoTitle(seomatic.meta.seoTitle ~ "in November 2020") %}
```

or

```
{% do seomatic.cache.keyAppend(month ~ '-' ~ year)  %}
{% do seomatic.meta.seoTitle(seomatic.meta.seoTitle ~ "in " ~ month ~ " " ~ year) %}
```

**Comment by khalwat** [comment]
Unfortunately, that can't work in this case, because SEOmatic has a two-level cache. The first level of the cache happens _before_ Twig is even executed, so you won't have the opportunity to be able to change it via Twig.

Is it workable for you to simply bust the cache vis `clearCache` only if those parameters are present?

**Comment by hiasl** [comment]
Well, if that's not possible, then we will use `clearCache` :-)
