### ISSUE TITLE
Content SEO empty for disabled site

### ISSUE THREAD

**Issue by bavocorteville** [nystudio107/craft-seomatic#1061]
### Describe the bug
A client of ours wants to fill in a disabled site, but content SEO is empty for disabled sites.

### Versions
- Plugin version: 3.4.23
- Craft version: 3.7.29

**Comment by khalwat** [comment]
Correct, that's how the plugin works, it does not allow you to add information to sites that are disabled, since it will never generate SEO information for any URLs from that site.

**Comment by chrismlusk** [comment]
While the plugin doesn't need to generate anything for disabled sites, I think it would be still be helpful to access elements in the Content SEO section so that authors can get SEO details configured and set up before a new site is launched. 

Clients can manage all other content for a disabled site. They can access their Global SEO settings, too, so it's a bit awkward that Content SEO isn't available until a site is live.

Is this something you would reconsider, @khalwat?
