### ISSUE TITLE
Do not enable humans.txt, security.txt and ads.txt by default as they expose information about how to attack the website.

### ISSUE THREAD

**Issue by FrDH** [nystudio107/craft-seomatic#1077]
### Is your feature request related to a problem? Please describe.
The files humans.txt, security.txt and ads.txt expose information such as installed plugins and the admin email address, which makes the website more vulnerable. For security reasons it is best not to share any of this at all.
Also, as the information in these files by default is not correct or complete, it would be better if they weren't enabled by default.

### Describe the solution you would like
Do not enable the files by default.

### Describe alternatives you have considered
We made the files forbidden using .htaccess

### Additional context
none

**Comment by khalwat** [comment]
That would be security through obscurity, which I'm not sure is a viable way forward.

However, if you want these off by default, you can disable them in the SEOmatic settings.

**Comment by FrDH** [comment]
I dont agree with the security through obscurity remark, but even then these files contain information that isn't correct.

Disabling the options in the CP is not the same as having them off by default, You're suggesting we now have to dig through 100+ websites to disable the options manually?

**Comment by khalwat** [comment]
> I dont agree with the security through obscurity remark, but even then these files contain information that isn't correct.

The information provided is meant to be a starting point. You can edit them to display anything you like (or remove anything you don't want to be displayed)

Here's the information that is by default displayed:

**ads.txt**
```
# ads.txt file for {{ siteUrl }}
# More info: https://support.google.com/admanager/answer/7441288?hl=en
{{ siteUrl }},123,DIRECT
```

So the `ads.txt` does not display any information at all, other than the site's URL, which is already part of the request.

**security.txt**
```
# security.txt file for {{ siteUrl }} - more info: https://securitytxt.org/
# (required) Contact email address for security issues
Contact: {% set adminUser = craft.app.getUsers().userById(1) %}{{ adminUser.email ?? 'user@example.com' }}

# (required) Expiration date for the security information herein
Expiration: {{ date('1year')|atom }}

# (optional) OpenPGP key:
Encryption: {{ siteUrl }}pgp-key.txt

# (optional) Security policy page:
Policy: {{ siteUrl }}security-policy

# (optional) Security acknowledgements page:
Acknowledgements: {{ siteUrl }}hall-of-fame
```

The `security.txt` file does display a contact email address, but the point of `security.txt` is to actually _help_ with security issues: https://securitytxt.org/ and they recommend listing a contact email address.

**humans.txt**

```
/* TEAM */

Creator: {{ seomatic.site.creator.genericName ?? "n/a" }}
URL: {{ parseEnv(seomatic.site.creator.genericUrl) ?? "n/a" }}
Description: {{ seomatic.site.creator.genericDescription ?? "n/a" }}

/* THANKS */

Craft CMS - https://craftcms.com
Pixel & Tonic - https://pixelandtonic.com

/* SITE */

Standards: HTML5, CSS3
Components: Craft CMS 3, Yii2, PHP, JavaScript, SEOmatic
```

This does list in text some of the tools/technologies used for the site, but again that's the point of the standard. Also bear in mind that by default, Craft itself sends headers that identifies the website as running Craft CMS (and by extension, Yii2 & PHP) by default as well:

https://craftcms.com/docs/3.x/config/config-settings.html#sendpoweredbyheader

If you really want to disable all of these by default, you can do so by using the config discussed here:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively#customized-setup

...by setting `'include' => false,` : <https://github.com/nystudio107/craft-seomatic/blob/develop/src/seomatic-config/globalmeta/FrontendTemplatesContainer.php#L26> but this only affects new installs (it works this way so that it doesn't override your defaults).

You can also override the default templates by providing your own versions of the default templates in the Craft `templates/` directory:

* `_frontend/pages/humans.twig`
* `_frontend/pages/ads.twig`
* `_frontend/pages/security.twig`

...if you prefer to set them there, rather than via the `seomatic-config` as discussed above.

ref: <https://github.com/nystudio107/craft-seomatic/blob/develop/src/models/EditableTemplate.php#L82>

**Comment by FrDH** [comment]
Thank you for the quick response.

I'm sorry if I come of a bit frustrated, but for us to comply with the ISO 27001 standard we MUST disable this file, which I now understand should be done manually for each live website.

The main reason for this topic was that securty.txt exposes the admin email adres (which in no way can increase security, right?). As the rest of the information is an assumption to begin with, maybe you could just use the fake email adres or something like `{{ siteUrl }}security` instead?

> This does list in text some of the tools/technologies used for the site, but again that's the point of the standard. Also bear in mind that by default, Craft itself sends headers that identifies the website as running Craft CMS (and by extension, Yii2 & PHP) by default as well

We already have these headers disabled :)

Anyway, SEOmatic has a lot of good stuff in it, keep that up.

**Comment by khalwat** [comment]
> I'm sorry if I come of a bit frustrated, but for us to comply with the ISO 27001 standard we MUST disable this file, which I now understand should be done manually for each live website.

No worries at all, I understand you're just trying to solve your problems.

I'm not familiar with that standard, can you point me to the relevant sections of it? I might make changes to SEOmatic based on the recommendations therein.

> The main reason for this topic was that securty.txt exposes the admin email adres (which in no way can increase security, right?). As the rest of the information is an assumption to begin with, maybe you could just use the fake email adres instead?

Sure, that's not a bad idea. The idea was to provide something used by default, an email address that would work out of the box. Typically email addresses are not used as logins by default, so it wouldn't help people gain access to the system (and they'd need the password as well).

**Comment by FrDH** [comment]
There are multiple versions, be we're sertified with ISO/IEC 27001:2013

**Comment by khalwat** [comment]
So what can I do to help you here? I can change the default templates so that new installs will get the updated default templates that won't include the admin's email address in `security.txt` but that won't help existing installs.

What would make it easiest for you to be able to update your existing sites?

**Comment by FrDH** [comment]
> I can change the default templates so that new installs will get the updated default templates that won't include the admin's email address in security.txt

That would be great.

For existing installs I think we'll use .htaccess to make the files forbidden.
Thanks

**Comment by khalwat** [comment]
Two changes were made:

* Change the default email address in `security.txt` to the placeholder `user@example.com`
* The `ads.txt` and `security.txt` templates are no longer enabled by default, because they require configuration before use

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.27”,
```
Then do a `composer clear-cache && composer update`

**Comment by FrDH** [comment]
Thanks 👍
