### ISSUE TITLE
Content SEO duplicated sections

### ISSUE THREAD

**Issue by peteeveleigh** [nystudio107/craft-seomatic#1094]
I have an issue whereby there are duplicates of the same Product type in the SEOMatic Content SEO index.

I can see there is history with this issue and it's been brought up and apparently resolved a number of times. But I've just encountered it on a new site using version 3.4.28. 

I've no idea how this has happened. All I know is that there are 2 "Radiators" products sections listed in SEOmatic's Content SEO list. My gut feeling is it's related to project config whereby git is able to merge 2 sets of metabundle data together without causing a conflict.

I seem to have fixed it by removing the earlier of the 2 duplicate rows from the seomatic_metabundles database table. If I remove the newer of the 2 tables it gets recreated. I'm wondering what surprises this "fix" might cause further down the line if I remove the duplicate in this way? Is it safe to do this?

### Versions
- Plugin version: 3.4.28
- Craft version: 3.7.37
- Commerce version: 3.4.12

**Comment by khalwat** [comment]
Yes, it is safe to do that -- if a meta bundle is missing, SEOmatic will just recreate it, so the only downside is losing any config data that you might have for that section.

If you manage to track down how you ended up here, I'd be interested in finding that out, so we can get it addressed!

**Comment by kerrig** [comment]
I was also having this issue, thanks @fantasticmachine for the notes on deleting the duplicate row in the database, that fixed it for me as well.

@khalwat I think that I got into this issue because I had renamed/swapped around the names of two sections and even though the sections were correctly updated in Craft, they weren't properly updated in SEOmatic's section list. I had a News Articles section and a Press Releases section that needed to be swapped around because content was imported/created into the incorrect sections. Like I said, they were updated properly in Craft but after that change, two "News Articles" sections appeared in the Content SEO list and the "Press Releases" didn't appear at all. Once I deleted the duplicate row (with the old section ID) from the metabundles table, that cleared it up in the SEOmatic Content SEO list, removing the additional "News Articles" section and properly showing the "Press Releases" section. Just to note this was also breaking the sitemap, as the news articles section was listed twice in the sitemap and the press releases section wasn't appearing, until I just cleared it up with this fix. Hopefully that helps you track down the issue.

Worth noting I was still on Craft 3 for this (3.7.56), not sure if this is still an issue in Craft 4.
