### ISSUE TITLE
[FR] Sitemap Index / Pagination

### ISSUE THREAD

**Issue by aloco** [nystudio107/craft-seomatic#1142]
### Is your feature request related to a problem? Please describe.

Hi, we have a large Webshop with around 40K Products. We can´t access the sitemap generated by SEOMatic for those products, the request ends in a 504. It seems like it was generated successful but the output is too large. It would be very helpful if SEOMatic supports paginated sitemaps. Unfortunately we can´t make all products accessible for crawlers via internal links only, therefore we need a complete sitemap(s).

Thank you

**Comment by khalwat** [comment]
SEOmatic currently does not support paginated sitemaps. You can try regenerating the sitemap via CLI command if you like.

However, I want to note that you do not need every page in your site to be in the sitemap.

Sitemaps are just hints to GoogleBot of what to crawl next. If one of your pages is already in the Google index, it will stay there whether it is in the sitemap or not. Additionally, Google discovers links in other ways as well, by crawling pages, etc.

So what many people do is they set the sitemap to only show the 100 or so most recent entires in a section. SEOmatic handles this for you automatically if you set the **Sitemap Limit**, so that only the most recently changed (and thus in need of re-crawling) entries are in the sitemap for GoogleBot.

**Comment by khalwat** [comment]
Google's current sitemap limits:

> All formats limit a single sitemap to 50MB (uncompressed) and 50,000 URLs. If you have a larger file or more URLs, you will have to break your list into multiple sitemaps

https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap

SEOmatic already supports sitemaps indexes, and each section in Craft will get a separate sitemap. It currently does not support splitting up a single (large) sitemap into multiple sitemaps.

I'm on the fence about ever doing this, because I'm not sure it's actually a direction I should be steering people towards. I think it's more effective to use sitemaps as mentioned above.

Happy to hear your thoughts!

**Comment by khalwat** [comment]
Relevant, in case we decide to paginate: https://developers.google.com/search/docs/advanced/sitemaps/large-sitemaps

**Comment by aloco** [comment]
I see your point.

In our case, the generation of the sitemap completes successful. We have less than 50K URLs so I would say the use case is valid. Actual I don´t really get how SEOMatic is providing the sitemap: is it a generated XML File on the file system or is it generated on the fly based on a database table which was prepared by the generate sitemap job? Maybe its enough to provide an option to place the XML file on disk so it can be served by the webserver and doesn´t require a php worker after it was generated

**Comment by khalwat** [comment]
It stores the generated sitemap in the cache, so that's whatever you have the Craft caching method set to. By default, that's a file-based cache, but in general, I recommend using Redis if available.

I do want to reiterate that you probably do not actually want to have all 40K URLs in your sitemap, it's unlikely to actually benefit your site, and could in fact be a detriment, in that it's a lot of data for GoogleBot to download, digest, and process.

**Comment by aloco** [comment]
We solved this for now by not putting everything in the sitemap, would appreciate an option to allow to split up large sitemaps for the same entry type.

**Comment by khalwat** [comment]
Noted. Will file a FR for the pagination of sitemaps.
