### ISSUE TITLE
Disable a specific channel sitemap from appearing in the Sitemap XML index

### ISSUE THREAD

**Issue by russelld** [nystudio107/craft-seomatic#1149]
Is there a way to disable a specific content channel from the sitemap generation? We have a content channel that is appearing in our sitemap index we would like to disable from appearing in our main sitemap index.

**Comment by khalwat** [comment]
Turn off URLs for that section, and they will not appear in the sitemap.

If you want URLs to be public (keeping in mind that Google may still find these URLs in another way), you can also disable sitemaps for this channel via Content SEO settings -> Sitemap

**Comment by andreasbecker** [comment]
Is it possible to prevent a specific url to be included in the sitemap programmatically? Something like this:

```
{% if entry.isPromotion %}
   {# Don't include the url of the current entry in the sitemap #}
   {% do seomatic.sitemap(entry.url).include(false) %}
{% endif %}
```
Or can this only be done via CMS on a per entry basis?

**Comment by khalwat** [comment]
It isn't possible to do that, because that template will never be parsed when the sitemap is generated.

So for specific URLs, you can use an SEO Settings field, and someone can enable/disable them from the GUI.

Typically, it's somewhat pointless to exclude a public URL from a sitemap, because GoogleBot will often find publicly accessible URLs just by crawling as well.
