### ISSUE TITLE
Setting SEO Titles for Tags pages in Craft CMS

### ISSUE THREAD

**Issue by russelld** [nystudio107/craft-seomatic#1151]
I am wondering if there is a way to use seomatic to control the output for the titles and seo of Tags type pages. I see how it's used to add control the SEO for Category pages within the Content SEO, but I do not see a way to control Tags output. 

Thanks

**Comment by khalwat** [comment]
I'm confused, what "Tags" are we discussing here? If you mean Craft Tag elements, they don't have URLs, so SEOmatic there are no frontend pages that they are directly analogous to.

**Comment by russelld** [comment]
Tags absolutely do have URLs. 
Yes Craft tag archive pages. ie 
site.com/tags/tag-slug

Do the global settings apply here? I believe so, but I do not see a way to for instance insert the tag title into the title of a tag archive page. 

thanks

**Comment by russelld** [comment]
Also to customize the description text of the Tag archive… etc… would be very helpful. thank you.

**Comment by russelld** [comment]
In our case we have multiple tag taxonomies. People, Topics, and Works. Similar to our Category taxonomies which do in fact have their own way of controlling SEO in the plugin. However Tags taxonomies which do have actual urls based on the tag group title and the actual tag slug do not seem to be editable/configurable in SEOMatic.

**Comment by khalwat** [comment]
Are you perhaps doing something custom on those Tag archive pages? Because according to the [Craft Knowledge Base](https://craftcms.com/knowledge-base/assigning-urls-to-tags#:~:text=There%20is%20currently%20no%20built,like%20there%20is%20with%20entries.):

> There is currently no built-in support for giving each [tag](https://craftcms.com/docs/3.x/tags-fields.html) its own URL like there is with entries

If so, you can also work with the SEOmatic APIs to set the titles, descriptions, etc. to whatever you want, using the SEOmatic API:

https://nystudio107.com/docs/seomatic/using.html#twig-templating
