### ISSUE TITLE
Seomatic extremely slow when creating a new entry

### ISSUE THREAD

**Issue by oyvindlarsent** [nystudio107/craft-seomatic#1160]
For the last couple of weeks our pages built in Craft have become significantly slower. When working backend I can see from the YII debugger that it's the Seomatic plugin that slows down the process, and I can also see the same frontend sometimes (but not always). 

![image](https://user-images.githubusercontent.com/107917057/174751571-b59aa973-5c0c-40d8-a5f8-ff75da1e67eb.png)

Does anyone have a suggestion as to why this is happening? 

Craft version: Craft CMS 3.6.14
Plugin version: 3.3.41

**Comment by khalwat** [comment]
SEOmatic uses a two-level cache when not in development mode, so things will be slower if you are working in local development. Read more on the cache here: https://nystudio107.com/blog/tips-for-using-seomatic-effectively#caching-and-cache-busting

However, the times you're showing me here are excessively slow. I would have to guess that something isn't set up optimally with your local development environment.

**Comment by khalwat** [comment]
The only other thing I can think of is if your asset volumes are not set up properly, and thus the image transforms for the various SEO images are being redone with every request. But the timings you're showing me are extremely slow, much slower than I'd expect to see due to the lack of SEOmatic caching in local development.
