### ISSUE TITLE
og:locale not parsed

### ISSUE THREAD

**Issue by S-n-d** [nystudio107/craft-seomatic#1164]
og:locale meta tag content is not parsed properly. HTML output is:

`<meta content="{{ { craft.app.language |replace({"_": "_"}) } }}" property="og:locale">`

### To reproduce
Fresh install of Craft 4 and SEOmatic plugin. 

### Versions
- Plugin version: 4.0.3
- Craft version: 4.0.5.2

**Comment by khalwat** [comment]
Fixed in:

3.4.44: https://github.com/nystudio107/craft-seomatic/releases/tag/3.4.34

4.0.4: https://github.com/nystudio107/craft-seomatic/releases/tag/4.0.4

Unfortunately, already created meta bundles will need to be removed, either by uninstalling and re-installing the plugin, or by deleting them from the `seomatic_metabundles` table in the database.

**Comment by curtismorte** [comment]
As an FYI to anyone who comes across this, remember what you're doing when you uninstall a plugin or delete records from the database!

This means you will have to go back an completely reconfigure the plugin settings that are stored in DB.

**Comment by khalwat** [comment]
Sorry about that @curtismorte -- I think it may actually update the bundles automatically for you since I updated the bundle version though.
