### ISSUE TITLE
Entry "View" link redirects to SEO preview

### ISSUE THREAD

**Issue by mgburns** [nystudio107/craft-seomatic#1166]
### Describe the bug

We're working on a Craft 4 site build out and are noticing that all "View" buttons in the entry editor are redirecting to SEO previews:

```
/seomatic/preview-social-media?elementId=4221&siteId=1
```

### To reproduce
Steps to reproduce the behaviour:
1. Edit any entry
2. Click on the "View" button
3. See that you are directed to the SEO preview

### Expected behaviour
I expect to be redirected to the entry on the frontend.

### Screenshots
https://www.loom.com/share/3ac89b9747a64190b63dade298dd1077

### Versions
- Plugin version: 4.0.5
- Craft version: 4.0.5.2

**Comment by khalwat** [comment]
This is not an SEOmatic issue, it's defaulting to that because you don't have any preview targets set up in your Section's settings:

<img width="1044" alt="Screen Shot 2022-06-28 at 12 59 35 PM" src="https://user-images.githubusercontent.com/7570798/176239470-b1885fc1-4c24-4c97-bfb1-7adde03d37cf.png">

**Comment by mgburns** [comment]
🤦🏻 First time starting a project with Craft Solo and upgrading to Craft Pro. Lesson learned! Thanks for taking the time to respond.

**Comment by khalwat** [comment]
No worries! That's what I'm here for!
