### ISSUE TITLE
Multi-site landing page SEO

### ISSUE THREAD

**Issue by jmauzyk** [nystudio107/craft-seomatic#1172]
### Question
We recently localized our site using subdirectories to differentiate between different locales. I used [this StackExchange question](https://craftcms.stackexchange.com/questions/23752/craft-3-multi-site-with-no-default-site) as the basis for how our site is set up. However, I added some additional logic in the webroot `index.php` so that requests without a locale subdirectory, path, or saved locale preference are routed to a landing page for the user to select a locale.

What I'm noticing is that after visiting that landing page and going to the homepage for the primary site (en-US), the tags etc. rendered by SEOmatic are from the cached SEO content of the landing page. I'm guessing this has to do with Craft defaulting to the homepage of the primary site when a site isn't defined.

Do you have any suggestions on how to handle this so that the landing page SEO content is separate from that of the primary site homepage?

**Comment by khalwat** [comment]
What is your actual site URL for the primary site? Is it the bare domain, or is it `https://mysite.com/en`?

Are you able to share the custom login in your `index.php`?

SEOmatic caches meta information on a per-URI and per-site basis. So probably the best course of action would be an actual redirect to the landing page URI rather than cloaking it in some manner?

There is also a way you can bust the cache if you don't mind always having the landing pages be uncached hits in terms of the meta information (it will be slower): https://nystudio107.com/blog/tips-for-using-seomatic-effectively#caching-and-cache-busting

**Comment by jmauzyk** [comment]
The primary site URL is https://mysite.com/en-us/, the international is https://mysite.com/en-int/.

Because this is our first foray into localization and our bare domain is well established in users' minds, I have the [`index.php`](https://github.com/nystudio107/craft-seomatic/files/9115924/index.php.zip) set up to render a template with locales listed if the incoming request is just the bare domain. This is where I think the SEO data is being cached for the primary homepage, because the bare domain isn't associated with any site so Craft defaults to the primary site homepage.

Trying to avoid cache busting because of the performance hit. Was also trying to avoid creating a third site just for the bare domain because it seems like it would add a lot of unnecessary stuff to the DB, though maybe I'm overthinking that.

**Comment by khalwat** [comment]
So just looking at that `index.php` file, that's going to be run on every request. In an ideal world, you want to do as little as possible in your `index.php`.

I don't fully understand your routing needs, but if there is a way to just let Craft do its thing for the request in the normal case, and then only do custom logic if there's some exceptional case that needs to be handled, that'd be ideal.

Retour allows you to listen to an event that it'll throw if it can't find a redirect, and is about do give up and result in a 404. You could hook your custom logic in there, to do whatever redirect needs to be done:

https://nystudio107.com/docs/retour/advanced.html#resolve-redirect-events

...and otherwise, just let Craft handle everything. I think you'd end up with less of a performance hit this way.

Then regarding the cached meta information, I like your idea of setting up an additional site whose sole function is to handle letting people pick the locale they want to use. That should clean that up too, because it should work with the caching in SEOmatic.

In general, work with the system as much as possible, rather than fighting it :)

**Comment by jmauzyk** [comment]
Looking at a this a bit more, I think our specific routing needs wouldn't necessarily work well with handling everything through Retour. It solves some problems but would also introduce new ones.

It would also require setting up that third site for the bare domain. This would work, but it would add a third site option to various indexes even though the only element available for that site would be the homepage single. Not the end of the world, but not an ideal authoring experience.

Following the guidance of that StackExchange question, I have the standard Craft `index.php` and `.htaccess` files in `en-us/` and `en-int/` directories within the webroot. This way, the `index.php` in webroot (the one previously attached) only runs if the request path has no locale subdirectory, so performance isn't a concern in that regard.

Regarding the SEO caching, I figured out an embarrassingly simple solution. In the locale landing page template, I simply added the tag `{% do seomatic.config.renderEnabled(false) %}` and manually rendered meta tags as needed. This prevents SEOmatic from caching meta info for the landing page as the primary site homepage.

Thanks for working through this with me!
