### ISSUE TITLE
Disable auto-rendering for one entry type?

### ISSUE THREAD

**Issue by j-greig** [nystudio107/craft-seomatic#119]
I have a 'Hidden' entry type for one structure, whose entries are not displayed on the public-facing website.

Is there any way to turn off the automagically generated meta info and replace it with a noindex?

**Comment by khalwat** [comment]
There's no automagic way, but you can do something like this in your template:

```twig
{% do seomatic.tag.get("robots").content("none") %}
```

If you just want to change the `<meta name="robots">` tag to prevent it from being indexed.

If you want to do something like disable the rendering of all metadata entirely, you could do this:

```twig
{% do seomatic.config.renderEnabled(false) %}
```

Which will prevent it from rendering _anything_ on that page.

**Comment by j-greig** [comment]
Perfecto, thank you!

**Comment by toddpadwick** [comment]
I tried this method but the entry is still added to the sitemap. How do I prevent the page being rendered on the sitemap on a template level?

**Comment by khalwat** [comment]
You can't do it at the template level, because no templates are involved when the sitemap is generated.

You'd need to do it via an SEO Settings field that has the sitemap controls in it, so you can disable them selectively. That, or you could do it via a custom module.

If you still have issues, please create a new issue, as what you're trying to do isn't entirely related to this existing closed issue.
