### ISSUE TITLE
Error loading entries, and also Tracking Scripts and Global SEO after update

### ISSUE THREAD

**Issue by hugo-costa** [nystudio107/craft-seomatic#1194]
### Describe the bug
Entries are not able to or some config pages of the plugin are not loading with the following error:

```
Twig Template Loading Error – craft\web\twig\TemplateLoaderException
Unable to find the template “twigfield/twigfield” in "seomatic/settings/_includes/fields/_seoTitle.twig" at line 19.
```

### To reproduce
Steps to reproduce the behaviour:
1. Go to Seomatic or Entry
2. See error message above

### Versions
- Seomatic version: 3.4.37
- Craft version:3.7.51
- Craft Twigfield 1.0.10 (also tested with 1.0.8)
- Composer 2.3.x

### Attempted Fixes:
- added `"nystudio107/craft-twigfield": "^1.0.10",` to composer, also added 1.0.8 initially but error is still occurring. 
- Checked composer has correct allow-plugins:
```
},
  "config": {
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.4"
    },
    "allow-plugins": {
      "yiisoft/yii2-composer": false,
      "craftcms/plugin-installer": true
    }
```
- Deleted the seomatic and twifield folder vendor/nystudio107 directory and ran `composer install`
- Verified composer.lock can see the plugins
- Cleared cache

**Comment by khalwat** [comment]
Please see the solution here: https://github.com/nystudio107/craft-twigfield/issues/2

If you still have this issue, check to see if you see a line like this after doing `composer update nystudio107/craft-twigfield`:

```
Do you trust "yiisoft/yii2-composer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] 
```

If so, you need to update the `allow-plugins` in your `composer.json` as per:

https://github.com/craftcms/cms/issues/11500#issuecomment-1165688915

Also you should say `y` to the question it's asking, otherwise Twigfield can't be properly installed.
