### ISSUE TITLE
Removing Meta Robots from Autogenerated output

### ISSUE THREAD

**Issue by johneemac** [nystudio107/craft-seomatic#1200]
I have another way of adding in the meta robots tags outwith SEOMatic

`<meta name="robots" content="all">`

How can i remove that tag from the output?

I'm just autogenerating the output, but can go a manually route if need be.

I've looked at all settings and a search on here but can't seem to find anything.

Many thanks.

**Comment by khalwat** [comment]
It would probably be best to let SEOmatic do it, because it will render it appropriately based on the current environment.

You can modify the values it uses however you want, e.g.:

```twig
{% do seomatic.tag.get("robots").content("whatever") %}
```

However, if you want to remove it, you can do it with what is described here:

https://nystudio107.com/docs/seomatic/using.html#seomatic-tags-containers

```twig
{% do seomatic.tag.get("robots").include(false) %}
```
