### ISSUE TITLE
Sitemap URL is missing in link tags

### ISSUE THREAD

**Issue by tremby** [nystudio107/craft-seomatic#1241]
### Describe the bug
I'm running a headless site, grabbing all data via GQL, and I want to serve the sitemap.xml file.

In exploring the GQL API I found that the "sitemapIndexes" and "sitemaps" fields gives names of XML files and their contents but none of them is the base `sitemap.xml` crawlers look for by default.

I expected then `metaLinkContainer` to have a link to the (non-`sitemap.xml`) main sitemap file, but it is not.

In investigating further I found that when not headless, SEOmatic redirects `/sitemap.xml` to another file, found via its internal `sitemapIndexUrlForSiteId` method. That isn't exposed via GQL, however.

I only see one object come back when I query for `sitemapIndexes` and so maybe I should use that one as the main file, or the first of the array, but I'm not sure that would always be the correct thing to do, and I can't find anything in the documentation to guide me.

It seems like a bug to me that the main sitemap index isn't pointed to as part of the links. Some valid syntax, I am led to believe by [a stackoverflow answer](https://stackoverflow.com/a/68117984/496046) is:

    <link rel="sitemap" type="application/xml" title="Sitemap" href="/sitemap-file.xml">

### To reproduce
Steps to reproduce the behaviour:
1. Query GQL for `sitemaps` and `sitemapIndexes`
2. See that none of them have the name `sitemap.xml`.
3. Query GQL for `metaLinkContainer`
4. See that none of the results point to any of the sitemap indexes which came back at step 1

### Expected behaviour
With data from GQL I can point my users to my sitemap, whether that means the correct redirection URL for `sitemap.xml` is available somewhere, or `metaLinkContainer` includes a link to the correct sitemap index. 

### Versions
- Plugin version: 4.0.9
- Craft version: 4.2.7

**Comment by khalwat** [comment]
It's not missing. The `sitemapIndexes` query is the one you want:

https://nystudio107.com/docs/seomatic/advanced.html#frontend-templates-graphql-queries

It returns the sitemap index (what should be displayed in response to a request for `/sitemap.xml`), but with the filename prefixed with `sitemaps-` followed by the site ID, e.g.: `1-`

SEOmatic (when used non-headless) actually redirects requests for `/sitemap.xml` to the correct sitemap, e.g. `/sitemap.xml` -> `/sitemaps-1-sitemap.xml` depending on what the current `siteId` is.

It does this because despite what you have in your `/robots.txt`, some crawlers just look for `/sitemap.xml` and nothing else.

Using a `<link>` tag to try to specify the sitemap you want crawlers to use isn't a great way to try to do it, because many crawlers don't even look for that tag, and default to `/sitemap.xml`

**Comment by tremby** [comment]
Ahhh I didn't realize it was pointed to in robots.txt. Thanks.

**Comment by tremby** [comment]
Hm, well I still want to redirect sitemap.xml to the correct file. That still means I either need to parse robots.txt to get the right filename, or I need to know which of the items in the sitemapIndexes array is the correct one to redirect to. What do you suggest?

**Comment by khalwat** [comment]
All you should need to do is take the contents of what is returned to you via the `sitemapIndexes` query, and write it out to `/sitemap.xml` or return it in response to `/sitemap.xml`

Unless you have a multi-site setup, that's all you'll need to do.

You don't need to do any redirection of any kind... unless you really want to. Just ignore the fact that the filename is returned as `sitemaps-1-sitemap.xml` and use the contents.

**Comment by tremby** [comment]
It is in fact multisite. I presumed the only special thing I need to do for
that would be to query with the appropriate siteId.

But regardless of that, I am still concerned about the response of
sitemapIndexes being an array. It's no problem to serve each one at the
names they each specify, but I don't see a flag for "this one is the root,
serve this additionally as sitemap.xml". This is why in my previous message
I was wondering how to determine that, such as by maybe parsing robots.txt.
Maybe there's only ever one in the array? But then why would it be an
array? Hopefully you can see my line of thinking and you know what I'm
missing.

Anyway, I'll look at it again in the morning with fresh eyes.

**Comment by khalwat** [comment]
Okay so since it's multi-site, here's what you do. Either pass in the `siteId` or `site` (handle) to the query like this:

```graphql
{
  seomatic {
    sitemapIndexes(siteId: 1) {
      filename
      contents
    }
  }
}
```

What will be returned to you is what should be used as the root `/sitemap.xml` for that specific site.

ref: https://nystudio107.com/docs/seomatic/advanced.html#sitemap-graphql-queries

**Comment by tremby** [comment]
sitemapIndexes returns an array.

Is there always exactly one item in it when a valid siteId is given?

**Comment by khalwat** [comment]
If you specify a `siteId` or `site` handle, there will be exactly one and only one of them in the array, yes.

**Comment by tremby** [comment]
OK, that's what I needed. Thank you.

So I need to serve the contents it gives both as sitemap.xml *and* as whatever filename it specifies (whether separately or as a redirection), since robots.txt references the arbitrary filename, but some tools ignore that and go straight for sitemap.xml.

**Comment by khalwat** [comment]
If you choose to use the `robots.txt` that SEOmatic provides, yes.
