### ISSUE TITLE
Content SEO Setup

### ISSUE THREAD

**Issue by joshuaseop2sinc** [nystudio107/craft-seomatic#1249]

**Comment by khalwat** [comment]
You would click on SEOmatic -> Content SEO, and set up the section mappings there, as described here:

https://nystudio107.com/docs/seomatic/overview.html#the-meta-cascade

**Comment by joshuaseop2sinc** [comment]
@khalwat the screenshot is what I'm seeing after having those section mappings set up. The values for B, C, & D are still resulting in 0% - any advice? Perhaps we have to update to the newest version first as you mentioned in my other post?

**Comment by khalwat** [comment]
Yes, I would update first

**Comment by khalwat** [comment]
@joshuaseop2sinc no, that is not normal. What version of the plugin is installed presently?

Also can you provide a screenshot of what you see in the Content SEO section?

**Comment by joshuaseop2sinc** [comment]
@khalwat we are operating with version 3.4.45. Here is the screenshot:
![content seo](https://user-images.githubusercontent.com/119890105/206588568-547e8876-f034-44d1-832b-d0c4b2945cfc.JPG)

**Comment by khalwat** [comment]
No, I mean click on SEOmatic -> Content SEO in the left sidebar, and take a screenshot of that listing of sections

**Comment by joshuaseop2sinc** [comment]
![Capture2](https://user-images.githubusercontent.com/119890105/206591037-9625f4a8-30d9-4187-a078-114cb7be8bcc.JPG)
here's what we see

**Comment by khalwat** [comment]
I need a screenshot of the entire page, that's just the first two sections

**Comment by joshuaseop2sinc** [comment]
![Capture2](https://user-images.githubusercontent.com/119890105/206591260-5b79f715-103c-4f6d-a8d7-7e0ad6877a0d.JPG)

**Comment by khalwat** [comment]
Okay, I'm so sorry, I misread your initial comments.

So that chart that you posted is a little confusing, it's a radial bar graph, which shows 4 bar graphs representing grades:

* **A** - dark green 
* **B** - light green
* **C** - orange
* **D** - maroon

If you move your mouse over the rings on the chart, you'll see the grade and the % displayed

So in your case, it's showing you that 100% of your sections get an **A** grade (they are fully set up), and 0% of your sections get B, C, or D grades.

Here's an example of what it might look like if _nothing_ was fully set up, and everything gets a **D** grade:

<img width="353" alt="Screenshot 2022-12-08 at 8 19 53 PM" src="https://user-images.githubusercontent.com/7570798/206601662-a192c335-7b82-4d14-9531-5f381ba36679.png">
