### ISSUE TITLE
Tracking scripts only load where renderEnabled is true

### ISSUE THREAD

**Issue by joepagan** [nystudio107/craft-seomatic#1252]
### Describe the bug

Tracking scripts only load where `renderEnabled` is `true`

### To reproduce
Steps to reproduce the behaviour:
1. set true see gtm scripts in head
2. set false see no gtm scripts in head

### Expected behaviour

The referenced setting only refers to rendering meta data and does not imply that tracking scripts will also not be rendered, from `seomatic.php`:
```
    // Should SEOmatic render metadata?
    'renderEnabled' => true,
```

Appreciate you meant the setting description to probably be a catch all for anything to be rendered. So maybe labelling as a bug is not fair.
We have a site where we haven't yet migrate the meta content to seomatic fully and expected the tracking scripts we added to the backend to just come through.

### Versions
- Plugin version: 4.0.15
- Craft version: 4.3.3

**Comment by khalwat** [comment]
Yeah this is expected behavior -- tracking scripts are in containers, and render just like tags, links, and JSON-LD structured data.

Instead of disabling rendering completely, what you can do is disable rendering of the containers you don't want, e.g.:

```twig
{% do seomatic.tag.container().include(false) %}
{% do seomatic.link.container().include(false) %}
```

The above will cause any `<meta>` tags and `<link>` tags to not render.

https://nystudio107.com/docs/seomatic/using.html#meta-containers
