### ISSUE TITLE
publisher.itemtype is invalid when selecting BlogPost

### ISSUE THREAD

**Issue by jordikroon** [nystudio107/craft-seomatic#129]
See:
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.tde.nl%2Fupdates%2Ftde-en-knvb-ontwikkelen-nieuwe-oranje-app

**Comment by khalwat** [comment]
This is pretty interesting; I'm not sure if this is actually correct, though. You should be able to use the `@id` property alone to specify it, as per:

https://stackoverflow.com/questions/34761970/schema-org-json-ld-reference/34776122#34776122

and:

https://webmasters.stackexchange.com/questions/98569/what-is-the-use-of-id-in-json-ld-syntax

And since it isn't complaining about the fields with the same syntax is being used (`author`, `copyrightHolder`, `creator`, etc.) that makes me wonder if the issue is actually that the schema.org type for the `@id` it's referring to isn't correct: 

```<script type="application/ld+json">{"@context":"http://schema.org","@id":"https://www.tde.nl#creator","@type":"LocalBusiness",```

According to this:

https://developers.google.com/search/docs/data-types/article

Google _requires_ that the organization type for the `publisher` specifically is an `Organization`. Why? I don't know -- the JSON-LD markup that SEOmatic is producing is valid as per the schema.org spec, this must be something specific to Google.

Seems silly that a publisher can _only_ be of the type `Organization` but if you change its type in the SEOmatic -> Identity settings, it should no longer flag this as an error. But then you lose the additional fields you get for a `LocalBusiness`.

I honestly think this is a flaw in the Structured Data Testing Tool.
