### ISSUE TITLE
Seomatic sitemap cache redis

### ISSUE THREAD

**Issue by almeric** [nystudio107/craft-seomatic#1295]
### Question
We have a site with very large sitemaps (some with 14k+ entries, others with 32k+ entries) and we have a cron job (re)generating these sitemaps every night. 

This site also uses a Redis cache and it looks like the sitemaps are pushed out of the cache by other items. Is there a way to exclude the sitemaps from the Redis cache and use the default `storage/runtime/cache/` for sitemaps so they don't get invalidated?

We've tried convincing our client that only the latest ~1000 items in the sitemap is enough, but unfortunately they insist on having all the pages available in the sitemap :/

**Comment by khalwat** [comment]
Yeah I don't agree with their idea of keeping _everything_ in the sitemap at all. Honestly, the last 100 (or even less) is all you need, because sitemaps are about discoverability, not about indexing.

And the SEOmatic sitemap will automatically sort by last modified date, so anything new or recently changed will always be listed, directing GoogleBot to spend its indexing time there.

Anyway unfortunately, if they won't listen to reason on that... then your option is just to expand the size of your Redis cache.

**Comment by khalwat** [comment]
This change https://github.com/nystudio107/craft-seomatic/commit/43565e693aca6aca3e4662562f427e22ead44317 in SEOmatic `4.0.29` & `3.5.58` fixes an oversight in the way SEOmatic was caching the `MetaJsonLdContainer`. This change will result in:

* Significantly lower overhead for cache hits, because the rendered metadata is now being properly cached
* Smaller cache sizes, due to only the rendered data being cached, not the entire array of `MetaJsonLd` objects
