### ISSUE TITLE
Is there an easy way to not show sitemap URLs for all sites in robots.txt?

### ISSUE THREAD

**Issue by nilsenpaul** [nystudio107/craft-seomatic#1317]
### Question
The default `robots.txt` uses `{{ seomatic.helper.sitemapIndex() }}` to show sitemap URLs for all sites (in the site group, if that setting is enabled). Is there a good reason for this (showing sitemaps for all sites, as opposed to showing only the sitemap for the current site). Is there an easy way to dynamically show only the URL for the sitemap of the current site?

In the case of the website(s) I'm working on now, there are 6 sites with their own separate domains. So, no multilocale setup, but 6 different 'brands', so to speak.

**Comment by khalwat** [comment]
`robots.txt` must exist in the root level of the website, according to the spec. Thus SEOmatic will by default show all sites in the `robots.txt` since in most cases, there is only one root domain.

SEOmatic assumes that all sites in the same Site Group are localizations of the same site. If you have "sister sites" as described above, you'll want to put each site in its own separate Site Group, or you can turn on the **Site Groups define logically separate sites** setting:

https://nystudio107.com/docs/seomatic/configuring.html#advanced-plugin-settings

The **Multi-Site Language/Locale Support** section has a detailed description of how SEOmatic works in this regard:

https://nystudio107.com/docs/seomatic/technologies.html#multi-site-language-locale-support
