### ISSUE TITLE
Cache miss

### ISSUE THREAD

**Issue by mariuswestgaard** [nystudio107/craft-seomatic#1331]
### Describe the bug
We're using SEOmatic on our Headless multisite setup, and are having issues with Seomatic that seems to slow down our CMS.

When loading a specific entry in the CMS, and reviewing the logs in the toolbar, we see these log-entries (also on subsequent loads):

```
1 | 19:56:41.467 | < 0ms > | info | yii\web\Session::open | Session started
-- | -- | -- | -- | -- | --
2 | 19:56:41.469 | < 1ms > | info | nystudio107\codeeditor\CodeEditor::bootstrap | CodeEditor module bootstrapped
3 | 19:56:41.525 | < 56ms > | info | nystudio107\retour\Retour::init | Retour plugin loaded
4 | 19:56:41.583 | < 58ms > | info | nystudio107\seomatic\Seomatic::init | SEOmatic plugin loaded
5 | 19:56:46.064 | < 4s 480ms > | info | nystudio107\seomatic\services\{closure} | parsed_globals_ cache miss: seomatic_metacontainer_nyheter/fns-baerekraftsjef-besokte-nrc-prosjekt9page1entries/newsItems/166326-fns-baerekraftsjef-besokte-nrc-prosjekt
6 | 19:56:46.471 | < 406ms > | info | nystudio107\seomatic\helpers\{closure} | schemaArray cache miss
```

As you can see in entry 5, the seomatic_metacontainer_** is not able to find it's cache entry, and then uses 4.48s to complete.

We're also using redis (was added today), but this issue was there before adding redis.

### To reproduce
Steps to reproduce the behaviour:
1. View an entry in the CMS
2. Check the log (with devMode=false) in the debug toolbar (see screenshot)

### Expected behaviour
I'd expect the metacontainer to be cached (at least on subsequent loads) and the plugin to be able to use the cache.

### Screenshots
<img width="2997" alt="Screenshot 2023-06-13 at 20 06 46" src="https://github.com/nystudio107/craft-seomatic/assets/27733229/53c742aa-c478-4235-bd87-a2b8828aa376">

### Versions
- Plugin version: 4.0.27
- Craft version: 4.4.13

**Comment by khalwat** [comment]
SEOmatic just uses whatever you've set Craft/Yii2 up for caching purposes. If there is a cache miss, either the item isn't in the cache yet, or it has somehow been evicted from the cache.

It's very likely this has to do with your caching setup rather than SEOmatic itself.

4.48s sounds so long that it probably is indicating something wrong on the devops side of things.

How long does it normally take to load an entry?

If you reload that same entry, is it still slow? (it shouldn't be, it should be cached)

**Comment by mariuswestgaard** [comment]
Yeah, that's what I'd expect to happen, but does not happen. The redis cache works fine on anything else, but not seomatic. Yap, 4.48s is really long. It always takes this long to load an entry, as it does not become cached (as mentioned in the description the cache miss happens on first and subsequent loads).

**Comment by khalwat** [comment]
Right, but again, SEOmatic just uses the caching method that you've provide to Craft/Yii2 to use. When you say it works fine for everything else, have you tried

```
redis-cli monitor
```

so you can see the items entering and existing the cache? https://redis.io/commands/monitor/

**Comment by khalwat** [comment]
I've reviewed the code in question that your log appears to be from:

https://github.com/nystudio107/craft-seomatic/blob/develop-v4/src/services/MetaContainers.php#L273

I'm not seeing anything in there that should be taking 4.5s unless something is very wrong.

Is this the only entry that this happens with?

What happens if you disable the SEOmatic plugin entirely, is it still slow?

**Comment by mariuswestgaard** [comment]
Thanks for checking. Did some more digging, and the issue was not with SEOmatic after all, and it does not take 4-5s either. It was misleading timings and logs.

**Comment by khalwat** [comment]
This change https://github.com/nystudio107/craft-seomatic/commit/43565e693aca6aca3e4662562f427e22ead44317 in SEOmatic `4.0.29` & `3.5.58` fixes an oversight in the way SEOmatic was caching the `MetaJsonLdContainer`. This change will result in:

* Significantly lower overhead for cache hits, because the rendered metadata is now being properly cached
* Smaller cache sizes, due to only the rendered data being cached, not the entire array of `MetaJsonLd` objects
