### ISSUE TITLE
Database Exception when browsing to any entry

### ISSUE THREAD

**Issue by danieladarve** [nystudio107/craft-seomatic#1348]
### Describe the bug
Getting the following exception in all entries after enabling the plugin:

Database Exception – [yii\db\Exception](http://www.yiiframework.com/doc-2.0/yii-db-exception.html)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'typeId' in 'where clause'
The SQL being executed was: SELECT *
FROM `seomatic_metabundles`
WHERE ((`sourceBundleType`='section') AND (`sourceId`=1) AND (`sourceSiteId`=1)) AND (`typeId`=1)
LIMIT 1

<a href="https://ibb.co/FxNynbv"><img src="https://i.ibb.co/j6BQHvK/Screenshot-2023-07-25-at-9-21-19-am.png" alt="Screenshot-2023-07-25-at-9-21-19-am" border="0" /></a>

I can see the migration https://github.com/nystudio107/craft-seomatic/blob/v3/src/migrations/m200419_203444_add_type_id.php in the database migrations table, however the column doesnt exist in the seomatic_metabundles table

### Versions
- Plugin version: 3.4.59
- Craft version: 3.8.16

**Comment by khalwat** [comment]
You need to ensure that migration is run, you can try

```
php craft migrate/all
```

or you can try running the migration individually... but the issue here is just that the migration has not been run

https://craftcms.com/docs/4.x/extend/migrations.html

If I had to guess, the plugin was updated, but pending migrations were not run, thus this change was not made to the db column.
