### ISSUE TITLE
Social Media Preview Generating 403 Error For All Users

### ISSUE THREAD

**Issue by bfopma** [nystudio107/craft-seomatic#1354]
### Describe the bug
When attempting to use the 'Social Media Preview' option of Live Preview, a message of "Unauthorized. User is not authorized to perform this action" is displayed. This occurs for the admin user (and all others).

This issue appears similar to [https://github.com/nystudio107/craft-seomatic/issues/905](https://github.com/nystudio107/craft-seomatic/issues/905)

### Likely relevant details
We use a separate subdomain for access to the CMS than what is used for the primary website. E.g.

CMS: [something].sitename.com/[something]
Public-facing Site: www.sitename.com

We also use Blitz and Cloudfront (on the www.sitename.com domain side), so there are potentially a couple of layers of caching involved.

Curious if there is some disconnect between the CMS domain side and the www. side that could be preventing access.

### Versions
- Plugin version: 4.0.30
- Craft version: 4.5.0

**Comment by khalwat** [comment]
I'm not sure it's related to that particular issue you cited.

Does this message happen for every entry? Do the entries you're attempting to preview not have a URL associated with them?

Essentially it sets an authorization for the current session:

https://github.com/nystudio107/craft-seomatic/blob/develop-v4/src/Seomatic.php#L570

...and then the controller that does the preview checks to ensure that authorization exists:

https://github.com/nystudio107/craft-seomatic/blob/develop-v4/src/controllers/PreviewController.php#L56

I was unable to replicate your issue locally, so I suspect it's something specific to your setup / devops. I'm not sure why a session wouldn't persist?

It's possible it is related to the domain name differences you note, maybe because the session cookie isn't set across domains?

**Comment by bfopma** [comment]
Thank you, Andrew!

Yes, by default the session cookie is not shared across subdomains and that appears to be the issue. I adjusted the 'defaultCookieDomain' Craft config setting to use this cookie across all subdomains and that seems to have resolved the problem. I'm somewhat surprised we haven't run into this elsewhere (e.g. Craft's Live Preview), but I assume that Craft is authenticating in a different way. 

Appreciate your help!
