### ISSUE TITLE
MetaValue::parseMetaString error log with certain characters 

### ISSUE THREAD

**Issue by AdamChlan** [nystudio107/craft-seomatic#1357]
In our error logs, we are seeing instances such as the following:

```2023-09-13 14:00:54 [web.ERROR] [nystudio107\seomatic\helpers\MetaValue::parseMetaString] Error rendering `Confessions of a Griever {Author Reading + Q&A} | 05.28.2020` -> Unexpected character "&" in "__string_template__9495c11c63aa9715182681b75b2b7a6d" at line 1. - Confessions of a Griever {Author Reading + Q&A} | 05.28.2020 {"memory":10317560} ```

Notice there are curly brackets in the entry title above. I can see similar errors in cases where the title has greater than / less than characters. I'm thinking these characters may be playing a roll in the error. Anything we should be doing on our end to resolve this?

- Plugin version: 4.0.27
- Craft version: 4.4.13

**Comment by khalwat** [comment]
This is likely due to SEOmatic trying to parse all of its fields as Twig templates... and the `{` is a signal to Craft that it might be an object template.

Probably there's nothing to do here, I'm not sure there's a good way I can check to see if a given string is actually a Twig template or not, other than telling Craft to try to parse it.

It should be a benign error, my call would just be to ignore it, unless you have any further concerns/suggestions?

**Comment by AdamChlan** [comment]
We did have a CPU spike recently and quite a few of these errors were present around that time, and I could not find anything else suspicious. Any chance these could cause a CPU spike?

**Comment by khalwat** [comment]
I can't imagine how, no.
