### ISSUE TITLE
Sitemap gets generated from web request instead of queue

### ISSUE THREAD

**Issue by bartdigitalpulse** [nystudio107/craft-seomatic#1366]
### Describe the bug
We had an issue where the sitemaps were getting generated by web request when they're not present in the storage/runtime/cache folder. One section had 60.000 entries which caused the server to time out on every sitemap request. We learned the hard way that there's a "Sitemap Limit" setting so that helped. 

Shouldn't the web request trigger a queue job instead of trying to render it on the spot? The "Regenerate Sitemaps Automatically" setting was set to off. We use a cron to generate the sitemap every day at 5am. But when we do a new deploy the "craft clear-caches/data" gets run and this destroys the sitemap cache (didn't know this). We're adding the "seomatic/sitemap/generate" to the deploy commands.

### To reproduce
Steps to reproduce the behaviour:
1. Regenerate Sitemaps Automatically set to off
2. Run craft clear-caches/data
3. Visit /sitemap.xml.
4. The sitemap will be generated on the spot.

### Expected behaviour
Maybe using a queue to generate the sitemap?

### Versions
- Plugin version: 4.0.31
- Craft version: Craft Pro 4.5.5

**Comment by gbowne-quickbase** [comment]
I've also recently noticed that the `--queue` param on `./craft seomatic/sitemap/generate` like `./craft seomatic/sitemap/generate --queue` doesn't put this in the queue, and I've tried `--queue=1`, `--queue 1`

**Comment by gbowne-quickbase** [comment]
Additionally, running the `./craft seomatic/sitemap/generate` at least on my local doesn't guarantee that the section will be returned when I click on it from the sitemap index. I keep getting errors

**Comment by khalwat** [comment]
Yes, it does trigger it via web request if it isn't available at all. This is due to some SEO web crawlers not properly handling the `503`  with the `Retry-After` header that SEOmatic adds.

The good news is that SEOmatic implements a stale while revalidate pattern so it will serve up the cached contents of the sitemaps while new ones are being generated.

**Comment by khalwat** [comment]
@gbowne-quickbase I'm not aware of the `--queue` parameter? When generating sitemaps via console, there's no reason to add them to a queue job, it just generates them immediately.

You say in local dev it you see errors; can you tell me what these errors are, exactly?

In local dev, SEOmatic uses a very short cache duration, so it's pretty normal for the sitemaps to not be in the cache in local dev.

**Comment by gbowne-quickbase** [comment]
@khalwat the `--queue` param shows as an option when you run `./craft help seomatic/sitemap/generate` which is the only reason I tried it. I see that the console runs through and processes everything. 

We turned the auto sitemap off for [reasons] and put in a manually generated one. I wanted to turn it back on for testing so that I could try to get us back to automatic creation from a manually generated sitemap. On my local I went to SEOmatic->Plugin Settings->Sitemaps and turned on "Sitemaps Enabled" and "Regenerate Sitemaps Automatically." Then I ran the console command `./craft seomatic/sitemap/generate` and removed the manual sitemap we'd stashed in the `web/` directory. When I go to the sitemap index, it shows up fine!  
![image](https://github.com/nystudio107/craft-seomatic/assets/39066452/489877b9-e493-4c5e-ba95-388f24106b0d)
But clicking on most of those links throws an error (I've got the canary plugin running which reformats the errors)
![image](https://github.com/nystudio107/craft-seomatic/assets/39066452/b9a4c0ff-7e8f-4bd8-9bf8-5353b8d3b0bd)

In the logs, I see odd errors on each request: 
![image](https://github.com/nystudio107/craft-seomatic/assets/39066452/c1c480ee-be0a-4431-8377-09db8a81aab1)
And further down, after the trace I see the plugins loading
![image](https://github.com/nystudio107/craft-seomatic/assets/39066452/e16af36b-0973-4aae-b133-e9610cb4bc0c)

I did a lot of cache clearing and regeneration, and more show up, but not all of them. I made sure that I removed any Retour redirects that were sending the SEOmatic style sitemap urls to `/` that someone in the marketing team had set up, but oddly everything isn't quite working. Is there another switch I should check?

**Comment by khalwat** [comment]
If you're seeing an error saying the route isn't found for a sitemap page, that doesn't have anything to do with them being cached or not -- it's simply not registering the routes for the sitemaps.

I'd suggest removing the Canary plugin just in case, and see if you get the same error (you probably will but worth checking).

Here is where the routes are registered:

https://github.com/nystudio107/craft-seomatic/blob/develop-v4/src/services/Sitemaps.php#L71

At this point, I'm not sure exactly what you're asking me for or what the issues are here. Can you re-state what are the issues you want me to help you resolve, in what environments you see them, and what the steps to reproduce are?

**Comment by khalwat** [comment]
Will re-open if more information is provided

**Comment by bartdigitalpulse** [comment]
> Yes, it does trigger it via web request if it isn't available at all. This is due to some SEO web crawlers not properly handling the `503` with the `Retry-After` header that SEOmatic adds.
> 
> The good news is that SEOmatic implements a stale while revalidate pattern so it will serve up the cached contents of the sitemaps while new ones are being generated.

@gbowne-quickbase kinda hijacked this issue with another issue. 

Our issue still remains that when the sitemap doesn't exist in the cache it will be generated via web request and if the sitemap is very large it never will be created because of execution time limits. Every web request will trigger this creation.

We needed to add a Sitemap Limit to every site that had sections with more than 500 entries/products. Every time we cleared the cache the server load was too high.

**Comment by khalwat** [comment]
@bartdigitalpulse  It sounds like potentially the server this is running on may be slightly under-powered?

Regardless, using a Sitemap Limit is likely a good idea:

https://nystudio107.com/blog/seo-myths-top-5-sitemap-myths-demystified

If you clear your caches, the sitemaps will be gone, and need to be regenerated. If a bot comes in looking for the sitemap, we can't know you have some other mechanism for generating the sitemaps, so we try to do it via web request right then and there.

You've already mitigated the situation by regenerating the sitemaps on deploy, which I think is a good solution. Also limiting the number of entries in a sitemap is also a good idea, for the reasons described in the above article.

Something we could _also_ look into doing is not generating the sitemaps via web request if Automatically Regenerating Sitemaps is off (that setting really applies to changes in the CMS, but might make sense here too).

Would you prefer that, @bartdigitalpulse ?

**Comment by bartdigitalpulse** [comment]
@khalwat 

Maybe if the sitemaps are missing and needed to be generated by web request you add a limit automatically? Maybe in combination with the "Automatically Regenerating Sitemaps" turned off setting?

Server could be better but we have one site with 50.000 articles (archive) that we only figured in hindsight to add a sitemap limit. Other sites 1000 - 5000 products. Generating a large sitemap like that by web request seems like a bad idea even with a powerfull server. 

Maybe add somewhere in the docs that sitemaps will be cleared when you clear cache en need to be re-generated? And potentially be re-generated by web request.
