### ISSUE TITLE
Clear specific meta data from cache without clearing whole container.

### ISSUE THREAD

**Issue by James-Blake** [nystudio107/craft-seomatic#1370]
### Is your feature request related to a problem? Please describe.
I am updating robots content so my pages aren't crawled when filters are applied. This optimises google crawl budget.
The issue is that i can only clear the entire seomatic cache. I would prefer to be able to clear just the robots meta if possible, so i can keep the page optimised. 

### Describe the solution you would like
allow  {% do seomatic.tag.container().clearCache(true) %}  to include query perams so i can clear just the robots tag.

### Describe alternatives you have considered
currently clear whole container cache instead.

### Additional context
nope :) thanks for the help!!!

**Comment by khalwat** [comment]
Unfortunately, that's not how the cache works. It doesn't cache individual tags. It's a two-level cache that caches the combined metatcontainers for a page, and then also the rendered result of the metadata.

The latter is done on a per-container basis, not on a per-tag basis. I'm not sure your requested change would really make a difference in terms of performance in any event.

As for setting `robots` to `none` dynamically based on filters that are set... I'd need to know more about what you're doing, but I'm not sure that's actually going to help anything in terms of optimizing the crawl budget.

**Comment by James-Blake** [comment]
Thank you for that. This makes sense.
The idea of changing robots dynamically was to switch between "all" (no filters applied) and "noindex, nofollow" (filters applied) to avoid crawling the same page for each filter, the filters are applied via URL.

**Comment by khalwat** [comment]
As long as the canonical URL is set correctly, you won't have any duplicate content issues... and regarding the crawl budget, GoogleBot will prioritize pages that have been changed since it last crawled (with hints from the sitemaps to guide it).

So FWIW unless you have an experiment that proves the changes you're making will have a qualitative impact on how GoogleBot's crawl budget is spent... I'm not sure I'd invest the effort in doing so. But up to you!
