### ISSUE TITLE
Sitemap broken redirect from sitemap index

### ISSUE THREAD

**Issue by mboostrom** [nystudio107/craft-seomatic#1398]
### Describe the bug
Within the sitemap index, if I try to click on one of the specific url's I am getting redirected to an error page. steps taking trying to correct this:
- turn off retour
- clear caches
- rebuild the seomatic sitemaps via CLI

### To reproduce
Steps to reproduce the behaviour:
1. Go to sitemap index from craft url: http://local.quickbase.com/sitemap.xml sitemap index looks like this for me.
![Screenshot 2024-01-04 at 10 22 20 AM](https://github.com/nystudio107/craft-seomatic/assets/67665430/dd1b97ce-953b-4a23-9acc-c7fdf81df7c0)

3. Click on any of the urls generated
4. See error message this is from http://local.quickbase.com/sitemaps-1-section-empowerHome-1-sitemap.xml
this error happens on 90% of the links only a select few actually open the correct sitemap page shown in the expected behavior section. On this error it is redirecting to a page that does not exist and retour is turned off. http://local.quickbase.com/var/www/quickbase/web/
![Screenshot 2023-12-29 at 10 23 39 AM](https://github.com/nystudio107/craft-seomatic/assets/67665430/0199d56f-6819-48dc-99bb-745f1ad1e08a)

### Expected behaviour
when clicking on any of those urls I should see this page instead of an error and being redirected
![Screenshot 2024-01-04 at 10 14 28 AM](https://github.com/nystudio107/craft-seomatic/assets/67665430/6e35f03c-85f1-407a-a573-d2fe4b4e1fe1)

### Versions
- Plugin version: 4.0.36
- Craft version: 4.5.11.1

**Comment by khalwat** [comment]
I'm going to have to guess that this is some kind of a config issue on your end. Perhaps the Craft CMS Site is not set up with a proper URL?

What is your `@web` alias or `CRAFT_PRIMARY_SiTE_URL` `.env` variable set to?

It looks to me like it's set to a path, when it should be set to a URL.

**Comment by khalwat** [comment]
Looking at the sitemap index from your live site, it looks like the URLs in the sitemap are just... wrong:

```xml
<loc>https://www.quickbase.com/about-us/leadership</loc>
```

Are we sure that something in the devops mix here isn't potentially interfering? Because it's missing a whole lot that should be there:

https://github.com/nystudio107/craft-seomatic/blob/develop-v4/src/services/Sitemaps.php#L353

It looks like somehow the sitemap index is being mapped to a particular sitemap. The sitemap index page should look like this:

https://nystudio107.com/sitemap.xml

I can only guess that some kind of devops / redirect / rewrite or such is in the mix here. This isn't what SEOmatic renders for the sitemap index page.
