### ISSUE TITLE
Pagination next/prev with trailing slash

### ISSUE THREAD

**Issue by WHITE-developer** [nystudio107/craft-seomatic#1401]
### Describe the bug
The pagination next/prev meta are getting a trailing slash when using `pageTrigger` with query param (eg ?page) and `addTrailingSlashesToUrls` is enabled. This due to the [UrlHelper.php:L152](https://github.com/nystudio107/craft-seomatic/blob/develop-v4/src/helpers/UrlHelper.php#L152-L154). The passed in url already has the query param [DynamicMeta.php:L102](https://github.com/nystudio107/craft-seomatic/blob/develop-v4/src/helpers/DynamicMeta.php#L102), so we end up with something like `https://site.com/news/?page=2%2F`

### Expected behaviour
Trailing slash shouldn't be added to the query param.

### Versions
- Plugin version: 4.0.37
- Craft version: 4.5.13

**Comment by WHITE-developer** [comment]
@khalwat ?

**Comment by khalwat** [comment]
Will get this addressed shortly.

**Comment by khalwat** [comment]
Fixed in the commits above.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.73”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.43”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.0.0-beta.6”,
```
Then do a `composer clear-cache && composer update`
