### ISSUE TITLE
Make the page "Dashboard" in SEOmatic in the Craft Backend hideable

### ISSUE THREAD

**Issue by neustadt-agentur** [nystudio107/craft-seomatic#1410]
### Is your feature request related to a problem? Please describe.
The dashboard is very confusing for our web customers. So we want to hide the whole page "Dashboard" which is showing in the Backend of Craft CMS under the point "SEOmatic". We already accomplished this, but then we also automatically hide all following pages in this submenu like "Global SEO", "Content SEO", "Site Settings" etc. what we of course do not want to hide. 

<img width="2523" alt="image" src="https://github.com/nystudio107/craft-seomatic/assets/153603802/f0f92209-ed00-4ce3-bbaf-a98c7380a687">

### Describe the solution you would like
We would like to completely hide the navigation point "dashboard" in craft backend but of course keep all the other navigation points.

Is there already a way to accomplish this?

**Comment by khalwat** [comment]
You should be able to hide the Dashboard via user group permissions, I believe?

But more importantly: what can be done to make the dashboard less confusing, and more useful to your customers?

**Comment by neustadt-agentur** [comment]
Hi khalwat. Thanks for your reply. One of our devs will try this tomorrow (to hide the dashboard for certain usergroups).

the dashboard is not helpful and more confusing than something else e.g. because of the reasons i put together in the added screenshot (additionally the color schema used in the "pie charts" on top are not clear at all):
<img width="2175" alt="Bildschirmfoto 2024-01-30 um 10 38 56" src="https://github.com/nystudio107/craft-seomatic/assets/153603802/95de2e99-e067-4430-8d9f-ae2ae6b6cc27">

i hope this helps for you to understand why the dashboard should be massively rebuilt or discarded completely.

**Comment by khalwat** [comment]
So let me explain to you what the Dashboard intends to do, and then I'll get to some of your specific points below. And yes, I understand that the fact that I need to explain to you what it's intended to do could be indicative of a problem.  :)

The Dashboard is intended to give you an overview of how set up SEOmatic is. As such, it points out to you a general score for the completeness of the setup for Global SEO, Content SEO, and the Site Settings.

It also is intended as a roadmap of sorts, providing you with clickable links that take you to the appropriate place to set up a thing that is not fully set up (as indicated by being unchecked).

I think this is all useful information, but I'd be interested in hearing what you do and do not find useful, as well as your suggestions for what it should be if it were "massively rebuilt or discarded completely."

Now on to some more specific points:

* The radial bar chart used for the Content SEO is something that I do think makes sense, but apparently, radial bar charts are hard for people to read. Since there are many sections involved in Content SEO, we can't give just one grade in terms of setup completeness. Instead, we are showing you in the chart how many sections get an A, how many get a B, etc. If you mouse over one of the bars in the radial bar chart, it tells what percentage of sections get that particular grade.

* You state that "SEO Keywords" are not a thing anymore; while it is true that Google ignores them, other search engines do not. And it's trivial to set up a mapping that will cause SEOmatic to automatically generate the keywords for you from CMS content

* You state that "SEO Title", "SEO Description" etc, are not proper terms. These are terms that SEOmatic uses, because the SEO Title and SEO Descriptions are used in more places than just the `<title>` tag and the `<meta name="description">` tags. So they are named appropriately, given that they do not correspond to _just_ those tags.

* The reason why the "SEO Title" and "SEO Description" etc tags stated they are not fulfilled is that they are not set on a global level. The idea beyond the global settings is that they are something SEOmatic will fall back on for pages that don't have anything set up at all for Content SEO (or maybe there is simple no section that corresponds to them). See [The Meta Cascade](https://nystudio107.com/docs/seomatic/overview.html#the-meta-cascade) for more information on how that works

* You state that there should not be checkboxes for things like the Twitter Handle and Facebook Profile ID for companies that don't have them. Since I can't predict what your client does or does not have, they are included to indicate that there's something you haven't filled in (and where to fill it in) that you might not be aware of. It might also spur companies to obtain these profiles. Most clients will get to 100% on the Site Settings Setup, but for ones that don't, that's fine too. It's just showing you what you _might_ want to fill in.

As stated earlier, you should be able to get rid of the dashboard entirely if you choose to do so, via user permissions.

However, I'd be interested in your suggestions of what should be appearing on the dashboard, so that the whole overview is not "more confusing than helpful by any means."

**Comment by simon-masta** [comment]
Unfortunately it does not work if we try to hide the dashboard only by userpermissions. if we disable only the dashboard the user gets an error if he clicks the main menuitem "SEOmatic" in the Craft navigation on the left. I guess it does not route the user to the next available page because the dashboard is the first page which gets shown when a user clicks on the main element "SEOmatic" then gets routed to "Dashboard" which does not exist for this user. but the click on "SEOmatic" should route the user (who has no access to the dashboard) directly to the next available page which would be "Global SEO".

Did we miss something or is it just not possible to only disable the "dashboard" by user permissions?

According your feedback for the dashboard itself: thank you very much for your informations. We just got this feedback from a lot of clients and we as an agency on its own have the same opinion about this. Its nice that you have done this and that for a specific reason. This feedback is just a honest user feedback so you can do with it what you want of course. We love SEOmatic for its features (we just really dislike some namings and the dashboard because of the already discussed issues). We would be really happy if we could just hide the dashboard for the users but let the possibility open to adjust stuff in global SEO, Content SEO and so on. At the moment this is not possible unfortunately.

**Comment by khalwat** [comment]
I very much do appreciate your feedback; I think the dashboard probably is pretty good at what it does, but what it does isn't as useful to clients as it is to developers or SEO consultants who are setting up SEOmatic.

Generally content authors are not given access to the SEOmatic plugin at all, since they typically don't need it. You set up the mappings when you create the site, and content authors usually don't need to change anything... and if they do, it's overriding the mappings you've set up via an SEO Settings field.

That said, I think you pointed out a valid bug, so I've addressed it via the commits above.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.73”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.43”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.0.0-beta.6”,
```
Then do a `composer clear-cache && composer update`

**Comment by simon-masta** [comment]
@khalwat Thank you! We tried it and it works now correctly with the adjustments you did. nice! So we'll wait for the release.
