### ISSUE TITLE
[5.0.0-beta.2] seomatic brakes styling of color preview in card mode

### ISSUE THREAD

**Issue by WHITE-developer** [nystudio107/craft-seomatic#1412]
### Describe the bug
The `.static`  styling in `seomatic-bxoB8j_R.css` is breaking the color field styling in the card view mode
see https://github.com/craftcms/cms/issues/14296

### Screenshots
![image](https://github.com/nystudio107/craft-seomatic/assets/22771556/cd109a99-d559-4c47-a6a3-6ac6183f881b)
![image](https://github.com/nystudio107/craft-seomatic/assets/22771556/9d443239-5dd8-4746-89be-1d249cffb22e)

**Comment by khalwat** [comment]
Here's the culprit: https://tailwindcss.com/docs/position#statically-positioning-elements

I will fix this by prefixing my Tailwind CSS build -- something I probably should have been doing already.

**Comment by khalwat** [comment]
So while I still think prefixing the Tailwind CSS is the right change long-term, my initial go at refactoring it was pretty onerous, because it required trying to find only the Tailwind classes in the `.twig` and `.vue` templates, and manually adding a prefix to them.

So in the interim, I'm fixing it by just adding `static` to the Tailwind CSS `blocklist` so we don't generate that class anymore (it wasn't actually a class we used anyway).

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.70”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.39”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.0.0-beta.3”,
```
Then do a `composer clear-cache && composer update`
