### ISSUE TITLE
robots meta tag isn't respecting settings from SEOMatic field and global or content settings

### ISSUE THREAD

**Issue by dreadfullyposh** [nystudio107/craft-seomatic#143]
Every page is coming up with the meta robots tag set to none, even though I've tried adjusting the field on each entry as well as the global and content settings.

Also can't seem to override using `{% do seomatic.meta.robots("all") %}`

I was able to override from the template using `{% do seomatic.tag.get("robots").content("all") %}` but it seems like something else is awry here.

Any ideas?

**Comment by dreadfullyposh** [comment]
Aha! I didn't notice there was a separate environment setting for SEOMatic.

**Comment by kmgdevelopment** [comment]
Can you elaborate on this @dreadfullyposh ? What environment setting needs to change for the `robots` meta variables to be updated?

**Comment by dreadfullyposh** [comment]
Under SEOMatic -> Plugin Settings in the control panel there's an environment dropdown.

**Comment by kmgdevelopment** [comment]
Ah OK, so the robots meta will only update in a production setting. @khalwat - seems like an unnecessary setting and makes testing difficult.

**Comment by dreadfullyposh** [comment]
Correct. At least at the time I created the issue. Haven't checked again since updating to newer versions. And I agree.

**Comment by khalwat** [comment]
Well, it is done this way so that SEOmatic can automatically set various tags appropriately based on your environment. For instance, on staging, we never want robots to index our site, so that changes as appropriate.

The right way to do it is to set up a multi-environment config file for SEOmatic as discussed here:

https://github.com/nystudio107/craft-seomatic#plugin-settings

...so that SEOmatic knows how to map from whatever your call your various environments to SEOmatic's own internal idea of "live", "staging", and "local"

I'm open to suggestions, but I've seen many staging sites that get accidentally indexed by Google, and that can be _very_ hard to undo in terms of content dilution. And since people can call their various environments whatever they want, there needs to be a way for you to tell SEOmatic what environment it is running in.

**Comment by dreadfullyposh** [comment]
Definitely understand. For me the issue is that one of my main clients is an SEO consultant and so when I put it on staging for her to test she is checking every tag to make sure they're how she wants.

Once I found the setting it made sense, but it was definitely confusing when I first ran into it.

I think for me it would be better to not lump them into environments and instead have settings for "analytics enabled", "meta enabled", "schema enabled" or something like that for all the areas that the environment setting controls.

Then perhaps have a default setting on those that allows them to follow the Craft environment setting and be overridden from there with an explicit enabled/disabled for each.

**Comment by khalwat** [comment]
Yeah, I consider that but unfortunately it doesn't break down in that way. For instance, have a look here:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/seomatic-config/globalmeta/TagContainer.php#L60

It's just that _specific_ tag that needs to change per environment. And then the analytics:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/seomatic-config/globalmeta/ScriptContainer.php#L34

But the way SEOmatic is written, if you don't like the automatic environment mapping, you can remove it entirely by replacing the default settings as described here:

https://github.com/nystudio107/craft-seomatic#config-settings

I was going for something where a collection of settings can change per environment, so that it automatically does "the right thing" based on the environment. For staging environments, for instance, by default it makes sense to have analytics off. You can override this via the multi-environment config in your circumstance, though, and instead use settings in GTM to determine the environment in terms of what to do.

**Comment by khalwat** [comment]
I know it's a bit icky @dreadfullyposh but I'm not sure how else to accomplish it. Totally open to ideas if you have them.

**Comment by dreadfullyposh** [comment]
Let me digest all these and see if I have any suggestion. Obviously it's a complicated situation to deal with so I appreciate your effort in thinking through it and being open to discuss options.

Thanks!

**Comment by kmgdevelopment** [comment]
It seems like the main issue here is the robots html `meta` tag. Why not leave that tag alone but still block the site via `robots.txt` or the `X-Robots-Tag` header when in a non-production environment?

**Comment by khalwat** [comment]
@kgrote I wouldn't feel very happy about that, though, because some bots look at headers, some look at meta tags, some look at both, and so on.

It's also Analytics scripts that are not included by default in environments other than production, which most of the time is a highly desirable thing.

I think the fundamental issue is that some things _should_ be different in a staging environment than in a production environment. We can switch around which things those are, but at some point, someone will run into things being different per environment, and wonder why.

So I'd like to "solve" this in a way that we can have an arbitrary number of things that can be different in various environments... but make it more apparent to people what is going on.
