### ISSUE TITLE
Draft entries show wrong social media preview images

### ISSUE THREAD

**Issue by tommers-walker** [nystudio107/craft-seomatic#1449]
### Describe the bug
Draft entries show global SEO image for social media preview images, even if they're set to pull from another entry field (e.g. entry hero image). Published entries show the correct images.

### Screenshots
<img width="983" alt="draft-entry-seo-images" src="https://github.com/nystudio107/craft-seomatic/assets/25368754/3316823c-0c61-4562-95ee-f7aceadb260a">
<img width="613" alt="draft-entry-social-preview-image" src="https://github.com/nystudio107/craft-seomatic/assets/25368754/f8422055-4fd7-405c-9083-0037d4ffb697">
<img width="489" alt="draft-entry-hero-image" src="https://github.com/nystudio107/craft-seomatic/assets/25368754/c9d6f02c-fb8b-4ecd-9e9d-b3a340cc3a1f">

### Versions
- Plugin version: 3.4.68
- Craft version: 3.9.10

**Comment by khalwat** [comment]
Fixed in the above commits

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.78”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.50”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.0.4”,
```
Then do a `composer clear-cache && composer update`
