### ISSUE TITLE
SEO Meta Descriptions and Page Titles not matching in Google Search

### ISSUE THREAD

**Issue by highway9support** [nystudio107/craft-seomatic#1457]
I am inquiring about an issue using the SEOMatic plugin for Craft CMS 3.7.38

I am finding a discrepancy with multiple pages where the page title and meta description that used in the SEOmatic plug are not what is represented on Google search.

I've attached examples for a specific product page for this particular site here:
![Screenshot 2024-02-26 103402](https://github.com/nystudio107/craft-seomatic/assets/166417341/5b846192-2859-48c1-b109-7aa287ddcb1b)

This is the SEO Preview provided by SEOmatic that also includes "| GD Energy Products" at the end of the page title (I do not know where that setting is to turn it on or off)

Here is what is coming up on Google search:
![Screenshot 2024-02-26 103355](https://github.com/nystudio107/craft-seomatic/assets/166417341/099b207e-2519-44e3-9a45-485affe21a92)

It seems that in the meta description, It is automatically porting in the content title and then using a different meta description that is not the one populated under "SEO Description Source". I have set SEO Description Source to override as well.

Please advise, thank you.

**Comment by khalwat** [comment]
It's up to Google's discretion whether to use the title or description you've provided or not. If it doesn't think your title or description is good, it will use its own description.

Additionally, you should check in Google Search Console to see when the page was last indexed, to ensure that Google has even consumed the page since you made the changes to the description or title.
