### ISSUE TITLE
'Summary from field' on a Matrix field adding whitespace and HTML spaces around the generated text

### ISSUE THREAD

**Issue by we-work-nights** [nystudio107/craft-seomatic#1484]
I am trying to generate a meta description from a field which uses a Matrix field made up of multiple text boxes. The text is correctly displayed, however, extra text spaces are appearing around the text, making the meta description look a bit odd. I have also tried to 

I have set **SEO Description Source** to override.
I have selected **Summary From Field** to use the required Matrix field.

<img width="821" alt="Screenshot 2024-06-25 at 08 32 38" src="https://github.com/nystudio107/craft-seomatic/assets/57918504/bdb492a9-7e01-428a-af6d-154a584fe1a8">

<img width="1471" alt="Screenshot 2024-06-25 at 08 28 57" src="https://github.com/nystudio107/craft-seomatic/assets/57918504/c44cf8d2-6de4-4211-a88d-19634064cc16">

**Versions**
Plugin version: SEOmatic 5.0.4
Craft version: Craft Pro 4.7.4

**Comment by khalwat** [comment]
First, generally this is something I would set up via Content SEO. The SEO Settings field is generally meant to be a per-entry override, and usually doesn't need to be used.

Instead set up the Content SEO for this section to map the SEO Description Source to what you're doing in the SEO Settings field.

As for the additional spaces, I'm not sure exactly where those are coming from. Are we sure they are not present in the original content, but are just invisible due to the way HTML is rendered?
