### ISSUE TITLE
How to Modify ⁠ <lastmod> ⁠ in a generated ⁠ XML-Sitemap.xml ⁠

### ISSUE THREAD

**Issue by Nik-koch-essen** [nystudio107/craft-seomatic#1502]
After reviewing the plugin documentation, I was unable to identify how to modify the ⁠ <lastmod> ⁠ tag in a generated ⁠ XML-Sitemap.xml ⁠. 

I tried using the ⁠ EventHandler ⁠, but it only allows me to add more links, not to modify the existing ones. 

Therefore, my question is: how can I achieve this?

Thank you in advance.

**Comment by khalwat** [comment]
Generally you shouldn't need to do this, because SEOmatic will automatically use the last modified date from the Craft element in question.

What is it you're needing or attempting to do here?

There is the `IncludeSitemapEntryEvent` event: https://nystudio107.com/docs/seomatic/advanced.html#includesitemapentryevent

...where I suppose you could modify the `$event->element->dateUpdated` if you wanted to but... unclear what the use-case would be in making this something other than when the Element was last updated in Craft?
