### ISSUE TITLE
Craft global set fields return NULL when SEOmatic is enabled

### ISSUE THREAD

**Issue by nfourtythree** [nystudio107/craft-seomatic#152]
Still getting the following issue: https://github.com/nystudio107/craft-seomatic/issues/108

Have highlighted it in the following comment: https://github.com/nystudio107/craft-seomatic/issues/108#issuecomment-397195255

Let me know if you need any further info or need to jump on a screenshare or something

**Comment by khalwat** [comment]
So this is something that they fixed in Craft CMS to my knowledge. Are you using the latest version of both Craft CMS and SEOmatic?

If not, you might want to file an issue or check the issues on https://github.com/craftcms/cms/issues because I'm fairly sure this is something on their end. Ping me if you find out otherwise?
