### ISSUE TITLE
Installation of plugin fails with Campaign plugin already installed

### ISSUE THREAD

**Issue by joostwaaijer** [nystudio107/craft-seomatic#1530]
### Describe the bug
When trying to clean install the Seomatic plugin, I'm receiving an error that refers to a different plugin.

### To reproduce
Steps to reproduce the behaviour:
1. Install the Craft Campaign plugin (https://github.com/putyourlightson/craft-campaign)
2. Install Seomatic plugin
3. See the following error: failed to install seomatic: An error occurred while executing the "nystudio107\seomatic\migrations\Install migration: Calling unknown method: putyourlightson\campaign\models\CampaignTypeModel::getSiteSettings()

### Expected behaviour
Seomatic installs without problem when combined with the Craft Campaign plugin.

### Screenshots
<img width="913" alt="image" src="https://github.com/user-attachments/assets/c23df3e7-3111-4bb0-9288-25836193f668">

### Versions
- Plugin version: 4.1.5
- Craft version: 4.11.4
- Craft Campaign: 2.17.1 (Lite)

**Comment by khalwat** [comment]
Interesting. It looks like the [CampaignBehavior](https://github.com/nystudio107/craft-seomatic/blob/develop-v5/src/integrations/campaign/behaviors/CampaignBehavior.php) hasn't been added to the `CampaignTypeModel` yet.

Fixed in the above commits.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.5.6”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.1.6”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.6”,
```
Then do a `composer clear-cache && composer update`

**Comment by joostwaaijer** [comment]
Thank you! Seems to work now!
