### ISSUE TITLE
Don't hide sections without URLs

### ISSUE THREAD

**Issue by colinmeinke** [nystudio107/craft-seomatic#157]
I have a few structure and channel sections that don't explicitly define URLs through settings.

Instead they rely on `config/routes.php` to load in the template. e.g. `'<s:(au|gb|us)>/legal/<p:.+>' => [ 'template' => 'legal' ]`. That template then does some fancy logic to work out which entry to load up.

I guess there are two issues here:

1. I cannot define seo data for these sections, because sections without URLs are now hidden https://github.com/nystudio107/seomatic/issues/332.
2. In the template how would I tell seomatic which section/entry to load data from?

**Comment by khalwat** [comment]
Sections without URLs were always supposed to have been hidden; the reason is that the mechanism SEOmatic uses to automatically figure out what metadata to use is the same one that Craft uses to auto-inject an entry into a given page.

Since you're doing custom routing, you're going to have to either:

1. Manually set the appropriate SEO data via Twig, as discussed here: https://github.com/nystudio107/craft-seomatic#twig-templating
2. Or you can use an SEO Settings field as discussed here: https://github.com/nystudio107/craft-seomatic#seo-settings-field

**Comment by colinmeinke** [comment]
Okay great, I can live with that.

As an aside, would it be possible/sensible to create a plugin that extends SEOmatic, but has a method that returns SEO data based on a given entry. e.g. `$seomatic->getMetaFromEntry($entry)`? I have been thinking a lot about using Craft as a headless CMS via the Element API, and wondered how SEOmatic would fit into that.
