### ISSUE TITLE
[FR] Custom element type support

### ISSUE THREAD

**Issue by Wiejeben** [nystudio107/craft-seomatic#166]
Hi!

I have talked to you about this on Slack before, but I guess posting it here makes this more official. I would like to have integration possibilities for custom element types.

I'd like to be able to integrate SEOmatic from my end, maybe via events?

Thanks!

Greetings,
Maarten

**Comment by khalwat** [comment]
Sure. I'm unsure of how I want to handle custom Element Types. For better or for worse, SEOmatic was built with implicit knowledge about certain element types that are built into Craft. This is so that I can do things like extract the appropriate information out of them automatically.

I'm not sure how this could translate to arbitrary custom ElementTypes, but I'd love to discuss with you ideas for how to best accomplish this.

Ping me on Slack when you're able?

**Comment by khalwat** [comment]
So this is something I wish I'd done from the start but...

I think the right way to do it is to abstract it away into a config file. That includes the built-in element types as well.

**Comment by khalwat** [comment]
So I think what I should do is have a config file that maps from an element's class to the various default settings for it.

I'd backport this to no longer hard code Sections, Category Groups, and Products, but rather just do it based on the `::class`

**Comment by khalwat** [comment]
Implemented via https://github.com/nystudio107/craft-seomatic/blob/develop/src/base/SeoElementInterface.php
