### ISSUE TITLE
Ability to pull in images from an Ansel field as the SEO Image source

### ISSUE THREAD

**Issue by HelgeSverre** [nystudio107/craft-seomatic#192]
It would be neat to be able to use an [Ansel field](https://buzzingpixel.com/software/ansel-craft) as a source for the SEO Image on an entry, if the Ansel plugin is installed.

I'm not sure if adding support for loads of third party plugin field is on the road map or something you'd be interested in doing, If it is out of scope, simply label and close the issue.

**Comment by khalwat** [comment]
Since SEOmatic will do the right transform for you depending on the social media site in question, there probably isn't a big benefit from having it natively support it.

You can always set it to **Custom URL** and put some Twig code in the field like:

```
{entry.myAnselField.url}
```

...and it should just work. c.f.: https://github.com/nystudio107/craft-seomatic#content-seo-admincp-fields

**Comment by HelgeSverre** [comment]
Ahh very neat, thanks.
