### ISSUE TITLE
sitmap.xml on multisite setup not rendering correcly

### ISSUE THREAD

**Issue by codanator** [nystudio107/craft-seomatic#194]
Hi,

i have a Craft install with three differnt sites.
Sitemap.xml configuration shows up correctly in the plugin settings.
But when i visit doamin.com/sitmap.xml the output is completly differnt and mixed with content from the other sites.

What could possible wrong in my setup or is it a bug?

THX

**Comment by khalwat** [comment]
@codanator Are you sure that it's SEOmatic that is providing that `Sitemap.xml`? Can you show me what it looks like?

**Comment by codanator** [comment]
Yes I am sure!

https://www.herzlauf.at/sitemap.xml

**Comment by khalwat** [comment]
So when I view this, I'm seeing:

```

<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>
      https://www.herzlauf.at/sitemaps/2/section/forschungsvereinStartseite/4/sitemap.xml
    </loc>
    <lastmod>
      2018-04-17T09:54:28+02:00
    </lastmod>
  </sitemap>
  <sitemap>
    <loc>
      https://www.herzlauf.at/sitemaps/2/section/herzkinderElternBerichten/4/sitemap.xml
    </loc>
    <lastmod>
      2018-07-18T14:15:54+02:00
    </lastmod>
  </sitemap>
</sitemapindex>
```

Which seems like the right information? Can you tell me what you think is incorrect?

**Comment by codanator** [comment]
Here is Screenshot from the SEOmatic settings.
As you can see the output is not what is configured.

**Comment by khalwat** [comment]
Can you try re-posting that screenshot? It doesn't look like it's showing up here @codanator

**Comment by khalwat** [comment]
@codanator ?

**Comment by khalwat** [comment]
Will re-open the issue if I receive further information.

**Comment by nilsenpaul** [comment]
I don't know if this is caused by the same issue, but when I let SeoMatic create sitemaps for me, I get the following setup (for 2 sites within a multisite, of which I only need site 1 to render in this sitemap):

![schermafbeelding 2018-10-02 om 14 38 27](https://user-images.githubusercontent.com/6794819/46348972-08f93300-c651-11e8-8f29-d09500e1605f.png)

I assume that the last number in the sitemap urls stands for the site that section or categoryGroup is used on. All sitemaps for site 2 have errors in them, because those pages do not exist.

**Comment by khalwat** [comment]
@nilsenpaul So those pages do not exist for some of the sites, then?

**Comment by khalwat** [comment]
If you don't want the sections from another site to render at all, you can disable them via the Sitemap settings for that site via Content SEO.

**Comment by nilsenpaul** [comment]
The problem is, that the content for site B should not be in the sitemap for site A. If I submit site A’s sitemap to Google Search Console, it complains about it having site B’s urls in it. I do have the sitemap before me, as I’m on my phone, but could there be relative URLs in there? So Search Console tries to find site B’s uris in site A’s domain? Will have a closer look when I’m back in the office tomorrow.

**Comment by khalwat** [comment]
So are these entirely separate sites, or are they the same site, translated into different languages?

If the former, SEOmatic keys off of Site Groups so it knows how to relate content, as per: https://github.com/nystudio107/craft-seomatic#multi-site-languagelocale-support

**Comment by nilsenpaul** [comment]
They are the same site, translated into different languages, **but with their own url**. Both sites are in one site group.

**Comment by frontedbe** [comment]
@khalwat Hey Andrew, isn't this related to something you fixed on multi-site sitemap.xml functionality the other day? [in this or any following commit I believe](https://github.com/nystudio107/craft-seomatic/commit/fea717651d557dd8e09eafa119df7292113d9f46)
