### ISSUE TITLE
Duplicate Content SEO Groups

### ISSUE THREAD

**Issue by mackenziep** [nystudio107/craft-seomatic#211]
Hi there, 

I'm seeing duplicate SEO content groups like this:

![image](https://user-images.githubusercontent.com/16430808/44682990-2a3b8380-aa02-11e8-9629-6e2d3679b5ee.png)

I wouldn't care, but it seems that after saving settings on a duplicate line with 0 items, modifications to the real line aren't being applied. For example, I saved the Stories section with 70 entries before it's doppelganger, and everything works as expected; I accidently saved the Homepage and Editions lines that show 0 entries, and now custom settings saved to either the 0 entries line, or the N entries line, aren't being applied to those sections. 

Any insight on this would be appreciated. 

Thanks!

**Comment by khalwat** [comment]
What version of SEOmatic are you using here @mackenziep ?

**Comment by mackenziep** [comment]
@khalwat 

SEOmatic version: 3.1.16
Craft Pro 3.0.21

Thanks for the prompt reply!

**Comment by khalwat** [comment]
Very strange, because it should be culling this automatically. Is there a way you could send me a database dump from this project to: andrew@nystudio107.com 

?

I'd like to see what's going on here... that or we can set up a screen sharing session at some point?

**Comment by khalwat** [comment]
Alright so it looks like what happened here is that at one point there were _two_ sections named `Stories`, with different IDs. Presumably a section named `Stories` was created, then it was deleted, then a new Section named `Stories` was created... because I'm seeing two entries in the `seomatic_metabundles` table for a `Stories` section, but with different IDs for each one.

This is something that SEOmatic just isn't accounting for; I'll have a look at how I can handle a situation like this.

In the meantime, you can open up the db with your favorite tool, and delete the duplicate row in the `seomatic_metabundles` table.

**Comment by mackenziep** [comment]
Ah I see. Yeah I was doing some weird migration stuff, so that doesn’t
surprise me. Thank you so much for looking into it! Great tool!

**Comment by davidkregl** [comment]
Hello @mackenziep I came across the same issue. Did you have a chance to look into that and prevent creating Content SEO record for deleted entries?
