### ISSUE TITLE
Question how to add extra META DATA to JSON-LD

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft-seomatic#219]
Question, we are trying to add extra properties to the additional information for the schema type 'businessEvent' that we use on a 'event' section.

[https://schema.org/BusinessEvent](https://schema.org/BusinessEvent)

We want to add the startDate and endDate of the (event) to the JSON-LD.

So we tried using the `seomatic.jsonLd.add()` but it's not really clear how it works. 
We tried this but that's not really working:

```
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}
{% set myMissingJsonLdInfo = seomatic.jsonLd.create({
  'startTime': entry.eventStartDate|atom,
  'endDate': entry.eventEndDate|atom
}) %}
{% set mainEntity = seomatic.jsonLd.add(myMissingJsonLdInfo, mainEntity) %}
```

What are we doing wrong?

It's not possible from the control panel in SEOMatic to add extra properties with entry data from custom fields to an entity?

**Comment by khalwat** [comment]
So probably you want to do something like this:

```twig
{% set myJsonLd = seomatic.jsonLd.create({
    'type': 'BusinessEvent',
    'key': 'mainEntityOfPage',
    'startTime': entry.eventStartDate|atom,
    'endDate': entry.eventEndDate|atom
}) %}
```

What this does is creates a new JSON-LD object of the type `BusinessEvent` with the key of `mainEntityOfPage` so that it'll overwrite the existing `mainEntityOfPage` (if any).

It's not possible to do this from the AdminCP, primarily because the UI for doing so would be quite involved... because there are over 500 JSON-LD types on schema.org, all of which can have nested schema.org types.

I have dreams of doing something like this at some point though.
