### ISSUE TITLE
[FR] Better representation of the SEO Settings field as an override

### ISSUE THREAD

**Issue by jonlongnecker** [nystudio107/craft-seomatic#248]
Just now getting to use the Craft 3 version of SEOmatic and man, such a big upgrade. Love how you've rethought everything.

One thing that has me stumped is the UI for editing an entries' SEO, though.

For instance, I almost always set the title, description and image to pull from existing fields. But when I flip over to the SEO Tab my defaults are visually not shown. All of them are set to "Custom Text or Image" even though I can tell from the previews that the fields have been pulled in and are being used.

<img width="1139" alt="screenshot 2018-10-23 13 50 08" src="https://user-images.githubusercontent.com/2390/47386732-a54fac00-d6ca-11e8-9b7b-bd2659a4d108.png">

You can see it's pulling the SEO Description and Title from the right fields, but not showing it visually. It's really confusing. 

Surely this is a bug of some sort? SEOmatic for Craft 2 shows the content correctly and in the way I would expect. The settings are correct for that channel, and I've made sure to save the section several times. Anything else I'm missing?

**Comment by khalwat** [comment]
Yeah I agree that it's confusing -- anything that's empty in the Field is viewed as "no change" so it defaults back to whatever things are set to in your Content SEO or Global SEO settings.

The Field is more of an override than anything else. It's done this way so that you can make global changes to an entire section's SEO settings without having to resave all of the entries in the section.

But I agree that the UI should indicate more effectively that the SEO Settings field is an override, and that blank "custom" means "no change"

**Comment by khalwat** [comment]
Also in general... I think SEO Settings fields aren't usually needed.

I think the best way to set it up is to set up the Content SEO Settings for each Section/Category/whatever to pull from existing content.

The only time an SEO Settings field is needed is when the client _needs_ to override things on a per-entry basis, which should be rare.

Usually it’s SEO consultants who want to try to tweak things by hand, and they will want an SEO Settings field to override things… but in most cases, I think this isn’t necessary or helpful

**Comment by jonlongnecker** [comment]
For sure - you'd be surprised how often my clients and their SEO firms like to override things, though. Shoot, I override stuff all the time. For instance, this page is the /about page, but for SEO reasons it's title is "History of the School" because they've been around over 200 years and it's an important part of their story.

I manually went in and changed the UI to what makes sense to me - it tells me which pieces are coming from where. The problem with the UI right now is that unless I set it up over in SEOmatic settings, I have no idea where the pieces are coming from. And even then, let's be honest, keeping track of all of it is difficult. 

<img width="1139" alt="screenshot 2018-10-23 15 08 40" src="https://user-images.githubusercontent.com/2390/47390942-cb2e7e00-d6d5-11e8-900b-398cba3534f0.png">

I guess I'm saying that if I'm having trouble keeping track of the pieces and I built it, my clients are going to be incredibly confused. If the UI from the previous version of SEOmatic isn't possible anymore (sounds like it would be a pain in the butt) maybe some additional text telling the user where the field is pulling from currently would help.

**Comment by khalwat** [comment]
> For sure - you'd be surprised how often my clients and their SEO firms like to override things, though. Shoot, I override stuff all the time. For instance, this page is the /about page, but for SEO reasons it's title is "History of the School" because they've been around over 200 years and it's an important part of their story.

Right, and you can do this using the SEO Settings field. I'm saying it's a better practice for modern SEO that the title reflects the content... and presumably the `entry.title` is used somewhere on that page as well? If so, it'd be best if the title was changed there.

> I guess I'm saying that if I'm having trouble keeping track of the pieces and I built it, my clients are going to be incredibly confused. If the UI from the previous version of SEOmatic isn't possible anymore (sounds like it would be a pain in the butt) maybe some additional text telling the user where the field is pulling from currently would help.

Hrm, maybe part of it is getting used to the new setup -- I find the new UI much, much simpler to understand.

But I agree with you that in this case, for the SEO Settings field, I need a better way to present it.

While I could have it so that when a Field is first instantiated, it inherits the Content SEO settings... but then that'd mean you could no longer make global changes to the Section via Content SEO.

So I think a better way to do it is have the Field more clearly represent itself as an override, and show what the current setting are for Content SEO.

I'm going to re-open this as a FR.

**Comment by jonlongnecker** [comment]
Yeah I didn't mention, but splitting the pieces up in Social Media and Sitemap tabs is so much cleaner. I love that part of it. Just this one part that confuses me.

**Comment by khalwat** [comment]
I always appreciate your feedback @jonlongnecker -- and I think you're right on this one too!

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-seomatic/commit/b41240b902b42ef53180d29c5cf6281ffd73907c

So the way it works now is probably the way everyone expected it to work from the start: SEO Settings fields will now default to their parent element's Content SEO settings.

From then on, the SEO Settings field will retain its values as you'd expect.

This makes a whole lot more sense, in that the SEO Settings field will reflect what things are set to already for your Content SEO, but then you can change them as you see fit later on.
