### ISSUE TITLE
meta and link tags using subdomains instead of WWW

### ISSUE THREAD

**Issue by egockel** [nystudio107/craft-seomatic#276]
For some reason, intermittently, our meta og:url and link/canonical tags are having the WWW swapped out with various inactive subdomains. You can see evidence of it in our various social media posts 
https://www.facebook.com/27453774561/posts/10155947380999562

Can this be managed somewhere?

![screen shot 2018-11-26 at 3 03 56 pm](https://user-images.githubusercontent.com/1335645/49042206-1502fc00-f18d-11e8-87a5-7d4144f4c6d3.png)

![screen shot 2018-11-26 at 3 03 44 pm](https://user-images.githubusercontent.com/1335645/49042207-1502fc00-f18d-11e8-8d1c-d538024c9729.png)

**Comment by khalwat** [comment]
So this very likely is due to how you're determining your `siteUrl` -- are you using `@web` for it, perchance?

The reason I ask is that SEOmatic doesn't do anything special in terms of figuring out the appropriate URLs to use, so that's coming from Craft or more specifically, Yii2.

Instead of using `@web` I'd suggest that you specifically set your `siteUrl` either through aliases, or through a `.env` setting that is used in your `config/general.php`
