### ISSUE TITLE
No domain in sitemap urls

### ISSUE THREAD

**Issue by almeric** [nystudio107/craft-seomatic#288]
I've already mentioned this in #278 (https://github.com/nystudio107/craft-seomatic/issues/278#issuecomment-448990261), but posting as a new issue for visibility:

The urls in the sitemap are missing the domain when using the Craft 3 Multi Environment setup:

*general.php*:
```php
'siteUrl' => getenv('CRAFTENV_SITE_URL'),
```

*.env.php*:
```php
$httpHost = $_SERVER['HTTP_HOST'] ?? '';
...[snip]...
'SITE_URL' => $protocol . $httpHost . '/',
```

If I for instance change the `httpHost` definition like so:
```php
$httpHost = $_SERVER['HTTP_HOST'] ?? 'fallbackvalue';
```
`fallbackvalue` will be used in the `sub-level` sitemaps.

We could solve this by just using a string as siteurl, but this is a bit of a pita with deployment and review environments

You can see the problem here: https://www.mixedemotionslive.nl/sitemaps/1/section/lineUp/1/sitemap.xml

**Comment by khalwat** [comment]
So I think what you should be doing is _explicitly_ defining your domain, rather than trying to figure it out programmatically at runtime. This is the same reason why Craft CMS isn't recommending that you use `@web` anymore: https://twitter.com/nystudio107/status/1074429502615379968

The same code that Yii2 uses to determine `@web` is what is being used in my Multi-Environment setup. I'll be revising that soon-ish.

So instead, set:

```
'SITE_URL' => 'https://example.com
```

The reason is that
