### ISSUE TITLE
Image shown in the Twitter/Facebook preview is different from the one in <head>

### ISSUE THREAD

**Issue by pierrestoffe** [nystudio107/craft-seomatic#293]
The image that is added to the <head> of all pages on a website I'm working on is not the right one. The funny thing though is that the correct image is shown in the preview provided by SEOmatic, in the CP.

Here is what I see on the preview in the CP:
<img width="841" alt="screenshot 2019-01-07 at 15 57 24" src="https://user-images.githubusercontent.com/1706605/50774980-38918a00-1295-11e9-97c4-903c42eadc6f.png">

The image I see there is the one that I expect to see and is defined in the "SEO Image Source" field using this "Custom URL": `{seomatic.helper.socialTransform((object.entry.seoImage[0]|default(object.entry.mainImage[0])), "base", 1, "crop")}`.

And here is the image I see when the page is rendered.
![screenshot 2019-01-07 at 15 57 13](https://user-images.githubusercontent.com/1706605/50774982-38918a00-1295-11e9-86f9-7c576e2d4521.png)

The image I see here is the one defined in the "Global SEO" tab, but it should be overwritten by the first image.

Note that I didn't define anything in the template. Everything has been defined in the CP.
Also, I cleared the caches (server and client) but this didn't solve the issue.

**Comment by khalwat** [comment]
I'm suspecting that the Twig code may not be rendering what you think it is; the reason you're seeing the global image is probably because the Twig code returns an empty result.

Try simplifying the code to ensure that it works in general. It's probably easiest to put the code into your actual page Twig template, and get it to work there first (removing the `object.` prefix when testing it.

**Comment by khalwat** [comment]
Any help @pierrestoffe ?

**Comment by pierrestoffe** [comment]
Hi @khalwat. I'll test your suggestion over the weekend and let you know. Thanks!

**Comment by pierrestoffe** [comment]
Hi @khalwat. So here is what I tested and the result of the tests.

Goal: Set the OG image to the main image of the news entry.

**1. Global configuring using the CP only**

Steps:
- in Global SEO/General => SEO Image Source is set to "Custom image" (let's call it _Image A_)
- in Global SEO/Facebook => Facebook OpenGraph Image Source is set to "Same as SEO Image"

Result:
- the OG image preview in the CP is showing _Image A_, which is expected at this point
- the SEO image in the JSON-LD output is using _Image A_, which is expected at this point
- the OG image in the <head> is using _Image A_, which is expected at this point

**=> All good.**

**2. Content configuration using the CP only (on top of the above)**

Steps:
- in Content SEO/General => SEO Image Source is set to `{entry.newsMainImage[0].url}` (or `{object.entry.newsMainImage[0].url}`, the result is the same)
- in Content SEO/Facebook => Facebook OpenGraph Image Source is set to "Same as SEO Image"

Result:
- the OG image preview in the CP is showing the image in `entry.newsMainImage[0].url`, which is expected at this point
- the SEO image in the JSON-LD is using _Image A_, which is **not** expected at this point
- the OG image in the <head> is using _Image A_, which is **not** expected at this point

**=> Unexpected results**

**3. Defining seoImage in the news/_entry template (on top of the above)**

Steps:
- `{% do seomatic.meta.seoImage(_Image B_) %}`

Result:
- the SEO image in the JSON-LD is using _Image B_, which is expected at this point
- the OG image in the <head> is using _Image A_, which is **not** expected at this point

**=> Unexpected results**

**4. Defining ogImage in the news/_entry template (on top of the above)**

Steps:
- `{% do seomatic.meta.seoImage(_Image B_) %}`

Result:
- the SEO image in the JSON-LD is using _Image B_, which is expected at this point
- the OG image in the <head> is using _Image B_, which is expected at this point

**=> All good**

From what I understand, the issue is that when defining an SEO image for a content type in the CP, that image is not propagated to the OG/Twitter images even when the "Same as SEO image" option is selected for OG/Twitter images.

Let me know if anything isn't clear.

**Comment by khalwat** [comment]
> **2. Content configuration using the CP only (on top of the above)**
> 
> Steps:
> - in Content SEO/General => SEO Image Source is set to `{entry.newsMainImage[0].url}` (or `{object.entry.newsMainImage[0].url}`, the result is the same)
> - in Content SEO/Facebook => Facebook OpenGraph Image Source is set to "Same as SEO Image"
> 
> Result:
> - the OG image preview in the CP is showing the image in `entry.newsMainImage[0].url`, which is expected at this point
> - the SEO image in the JSON-LD is using _Image A_, which is **not** expected at this point
> - the OG image in the <head> is using _Image A_, which is **not** expected at this point
> 
> **=> Unexpected results**
> 

That's really interesting that you're seeing the correct thing displayed in the preview, but not on the frontend. Thanks for the reproducible test case, I'm going to have a look.

> **3. Defining seoImage in the news/_entry template (on top of the above)**
> 
> Steps:
> - `{% do seomatic.meta.seoImage(_Image B_) %}`
> 
> Result:
> - the SEO image in the JSON-LD is using _Image B_, which is expected at this point
> - the OG image in the <head> is using _Image A_, which is **not** expected at this point
> 
> **=> Unexpected results**
> 

So this is actually an expected result. The reason is that people wanted the ability to have separate images for the `og:image` and `twitter:image`; so you'll need to explicitly change those as well.

There's a discussion on that here:

https://github.com/nystudio107/craft-seomatic/issues/253

**Comment by khalwat** [comment]
> **2. Content configuration using the CP only (on top of the above)**
> 
> Steps:
> - in Content SEO/General => SEO Image Source is set to `{entry.newsMainImage[0].url}` (or `{object.entry.newsMainImage[0].url}`, the result is the same)
> - in Content SEO/Facebook => Facebook OpenGraph Image Source is set to "Same as SEO Image"
> 
> Result:
> - the OG image preview in the CP is showing the image in `entry.newsMainImage[0].url`, which is expected at this point
> - the SEO image in the JSON-LD is using _Image A_, which is **not** expected at this point
> - the OG image in the <head> is using _Image A_, which is **not** expected at this point
> 
> **=> Unexpected results**
> 

I tried to reproduce this, but can't. Let me know what I might have done wrong.

I have a Single with the following Asset field in it:

<img width="367" alt="google chromescreensnapz330" src="https://user-images.githubusercontent.com/7570798/51289426-21a61280-19ce-11e9-968a-e03c55e08663.png">

Then in Content SEO for my Single, I set the SEO Image Source to:

<img width="269" alt="google chromescreensnapz331" src="https://user-images.githubusercontent.com/7570798/51289448-37b3d300-19ce-11e9-8eea-0e7b110065fa.png">

...and I verified that Facebook OpenGraph Image Source was set to pull from the SEO image:

<img width="279" alt="google chromescreensnapz332" src="https://user-images.githubusercontent.com/7570798/51289468-4c906680-19ce-11e9-86d5-551cf65fa75e.png">

...and in the generated HTML I see the correct transformed version of the image for the `og` tag:

<img width="1063" alt="google chromescreensnapz333" src="https://user-images.githubusercontent.com/7570798/51289496-62059080-19ce-11e9-9787-830e398f4396.png">

...which is the same as what I'm seeing in the JSON-LD:

<img width="607" alt="google chromescreensnapz334" src="https://user-images.githubusercontent.com/7570798/51289511-6fbb1600-19ce-11e9-8ea4-f3fd62257f18.png">

**Comment by pierrestoffe** [comment]
Thanks for looking into it @khalwat. That's weird indeed. I'll debug this over the weekend on a clean-install where I'll gradually replicate the config with the one from the faulty website.

**Comment by pierrestoffe** [comment]
I tested on a very light install and I'm experiencing the same issue. In this install I have 3 Sites, and it only works correctly when no Global SEO Image is defined. I'll email you a .zip of the project + db, should be easier to debug.

**Comment by khalwat** [comment]
Thanks yeah I am not sure what is going on, since I can't reproduce it. The db dump will help!

**Comment by pierrestoffe** [comment]
@khalwat I sent you the dump and files on Jan 20th at this address: info (at) nystudio107.com. Can you confirm you received it? Subject is "SEOmatic - Issue #293". If not can I send it to you some other way?

**Comment by khalwat** [comment]
@pierrestoffe I'm not seeing it; can you re-send please?

**Comment by pierrestoffe** [comment]
@khalwat Sure, just sent it.

**Comment by khalwat** [comment]
So I'm reviewing the database dump that you sent, and it looks like the issue is that:

1) You have the SEO Image set to Custom URL with some custom Twig code to extract the image from an existing field
2) You have the Facebook set to "Same as SEO Image"

So the problem here is that to do the SEO Images, SEOmatic wants to try to transform the images to be right right size. Unfortunately, it can't transform an image without having an `id` for the asset to be transformed.

The problem is that the all that is in the field is arbitrary text (Twig code in this case); but even if we parse the Twig code down, we don't get an ID out of it.

Now what is _supposed_ to be happening is it will just blindly use the textual value of what is in the SEO Image field in this case. I'm investigating why that's not happening.

You can fix this now two ways:

1) Set the Facebook Image to be the same custom url you have now in the SEO Image settings: `{entry.theImage[0].url}`

2) Set the Facebook Image to the custom url: `{seomatic.helper.socialTransform(object.entry.theImage[0].id, "facebook", 1, "crop")}` so that it's scaled appropriately

3) (Preferred) I'd also suggest that since all it is really doing is pulling the image from an asset field, you can just set it to pull the SEO image from that asset field, and everything will work (instead of using Custom URL).
