### ISSUE TITLE
Script Template not finding user object

### ISSUE THREAD

**Issue by Coysh** [nystudio107/craft-seomatic#294]
Hi,

I'm trying to edit my gtag.js config to include a user id - it's a custom field on the User Object.
Trying to access `currentUser` from the Tracking Script just returns the user's name - not the object.

`{% if (currentUser) and (currentUser.membershipID) %}
    {% set seo_user_id = currentUser.membershipID %}
{% else %}
    {% set seo_user_id = 0 %}
{% endif %}
{%- set gtagConfig = "{"
    ~ "'send_page_view': #{pageView ? 'true' : 'false'},"
    ~ "'anonymize_ip': #{ipAnonymization.value ? 'true' : 'false'},"
    ~ "'link_attribution': #{enhancedLinkAttribution.value ? 'true' : 'false'},"
    ~ "'allow_display_features': #{displayFeatures.value ? 'true' : 'false'},"
    ~ "'user_id': #{ seo_user_id }"
    ~ "}"
-%}
gtag('config', '{{ googleAnalyticsId.value }}', {{ gtagConfig }});`

`seo_user_id` is always black. If I try to output `currentUser.membershipID` anywhere else I get the correct number.

**Comment by khalwat** [comment]
Yeah that's not going to work, because the scripts template is rendered in its own context. It's not like a template that you `{% include %}` in your other templates (though potentially, that _might_ be possible as a FR.

What I'd suggest doing is just edit the gtag script in SEOmatic to only load the script, and then write your own code elsewhere in your templates that does this additional logic, and the sends the page view.

**Comment by bymayo** [comment]
Similar to this I wanted to output a conversion event similar to:

`gtag('event', 'conversion', {'send_to': 'XXXXXXXX/XXXXXXXXX'});`

I tried doing 

```
{% if entry is defined and (entry.id == 20338 or entry.id == 17632) %}
gtag('event', 'conversion', {'send_to': '{{ googleAdWordsId.value }}/XXXXXXXXX'});
{% endif %}
```

But this didn't work because of the issue you mentioned. But as a FR it would be good to be able to manage all events etc within SEOMatic, so that we don't lose track of where these events are being fired.
