### ISSUE TITLE
[Bug] Multi-language/sites issue with social media asset paths

### ISSUE THREAD

**Issue by cole007** [nystudio107/craft-seomatic#296]
I'm experiencing a potential bug using Seomatic on a multi-site/language Craft 3 build when specifying an asset field for social media image previews.

Scenario:

1. we have a multi-site build where the sites are accessed via sub-paths for language, eg English > `/en`, German > `/de`, etc.
1. The SEO image field used for social media images (as defined in Seomatic > Global SEO > Twitter, for example) is set to be site-specific (eg the same entry can have different images based on context/site)
2. When Seomatic is applying transforms and generating the image paths for these it is applying the resource path based on the site URL rather than the resource URL so what should be `http://domain.com/path/image` is generated as `http://domain.com/en/path/image`. This path doesn't exist so the image preview is throwing a 404 error.

Above is using the default seomatic template/hook.

**Comment by khalwat** [comment]
So what SEOmatic does to get the URL to the transformed image is:

```
            $url = $assets->getAssetUrl($asset, $transform);
```
https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/ImageTransform.php#L103

This should be returning a full URL, but it's potentially possible that if you don't have your Asset Volume URLs set to full URLs that it will be just a path. Because relative URLs are not allowed for social media URLs, SEOmatic then tries to make a full URL out of it.

So that's my _guess_ as to what is happening. Try setting up your `volumes.php` in a multi-environment way to explicitly set the Asset Volume `baseUrl`s.

There's no template or hook in the Craft 3 version of SEOmatic btw. So you can safely remove the old Craft 2.x `{% hook %}` from your templates.

**Comment by cole007** [comment]
Many thanks and apologies - I hadn't appreciated this issue was down to the asset path/route set for the volume. I have updated to include `@web` and this seems to have fixed the problem.

Many thanks - please consider this issue closed.
