### ISSUE TITLE
Update destroys custom tracking scripts additions

### ISSUE THREAD

**Issue by alanski66** [nystudio107/craft-seomatic#299]
Sad to say that adding tracking script additions in the GA tracking script template is overwritten by updates to its default. 
I assumed this was stored in the db - in which case its a bug as the update is resetting the template to default. I hadn't noticed for a month (yes that's a month of data gone)
If default behaviour is to read the template then where can we safely override in version controlled multi environments?

**Comment by khalwat** [comment]
So, this is a tough one. It is stored in the db, but there were some changes a while back that necessitated changing how things were stored with scripts. This only should have happened if you were updating from a specific version many moons ago.

I apologize, I didn't find out that it was a side-effect until after. Since the changes you make are stored in the db, you should not run into this again.
