### ISSUE TITLE
Upgrade from v2

### ISSUE THREAD

**Issue by redkrupp** [nystudio107/craft-seomatic#30]
Hello,

How does the upgrade procedure (craft v2 + seomatic fieldtype) look like? I haven't found anything in the docs. Please advise.

**Comment by khalwat** [comment]
@EmptyStreets Currently the way to upgrade is just to install the new plugin; because there is no Field in SEOmatic for Craft 3, there really isn't much to upgrade.

You'd just install the plugin, and set up the Global SEO and Content SEO settings, and away you go.

See here for the Field discussion:

https://github.com/nystudio107/craft-seomatic/issues/14

That said, if I do implement a Field (which seems likely) there will be some data that can be migrated.

I'll add something to the docs to this effect.

**Comment by khalwat** [comment]
I added this to the docs:

### Upgrading from SEOmatic 1.x for Craft CMS 2.x

If you are upgrading a site from Craft CMS 2.x to Craft CMS 3.x that used the older SEOmatic plugin, here's what you need to know.

SEOmatic for Craft CMS 3 is a complete re-write and re-architecture from scratch of the plugin. This allowed us to take what we learned from SEOmatic 1.x, and rebuild it with a much more robust and extendable architecture.

This also means that SEOmatic for Craft CMS 3 has little in common with the older plugin, both from a code point of view, and also conceptually. As such there isn't a way to migrate data in a way that makes sense; instead, you should just set up SEOmatic for Craft CMS 3 fresh.

Thankfully, due to the new architecture, this is quite easy to do. If we do [bring back the SEOmatic Field](https://github.com/nystudio107/craft-seomatic/issues/14) (which is looking very likely), then there will be a data migration.

Still, we think the best way to update sites using SEOmatic is to start fresh, and explore how the conceptual changes in the plugin affect how you use it. In most cases, you don't even need to use an SEOmatic Field, and the setup is cleaner and easier without it! We hope you love it!
