### ISSUE TITLE
[FR] Multiple SEO Images

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-seomatic#307]
I've had a client request to have multiple SEO images added to a single page.

I don't believe SEOmatic currently supports this, but it appears to be valid by the OG spec: http://ogp.me/#array

E.g., I believe on Facebook if there are multiple, it allows the sharer to click through and select.

**Comment by khalwat** [comment]
Yep, this could be supported for OpenGraph

**Comment by bossanova808** [comment]
Would be great for products, too, which support multiple images in the json-ld https://developers.google.com/search/docs/data-types/product

**Comment by elivz** [comment]
Is this possible yet? I have a client asking about the same thing....

**Comment by khalwat** [comment]
It's possible via Twig (and always has been) but not via simple CP settings (yet)

**Comment by elivz** [comment]
Is that documented anywhere? I tried setting `seomatic.meta.seoImage` to an array of image urls, which didn't work...

**Comment by khalwat** [comment]
I think it's not documented, and it should be... but you'd basically just do something like this:

```twig
{% set ogImage = seomatic.tag.get('og:image') %}
{% do ogImage.content([
    'http://example.com/image1.jpg',
    'http://example.com/image2.jpg',
]) %}
```

...and it'll generate a tag for each one, such as:

```html
<meta content="http://example.com/image2.jpg" property="og:image">
<meta content="http://example.com/image1.jpg" property="og:image">
```

Or at least it used to do that, until I broke it by accident, so I guess "always" was a strong word :) . Fixed in -> https://github.com/nystudio107/craft-seomatic/commit/fac9fa85cdcc7644f3ae8e889c8ebc86ef589d37

Also added an example to the docs -> https://github.com/nystudio107/craft-seomatic/commit/4e03ed64736effff7e097b5e0bd3472571cd1f9e

It only works for the various OpenGraph tags, because they are the only ones that allow for multiple of the same thing in this manner.

Will leave this ticket open tho, because I think the intent is to have a nice way to do it in the GUI as well.

**Comment by elivz** [comment]
Awesome, thanks Andrew! I will give this a shot tomorrow after I have a chance to upgrade my install.
