### ISSUE TITLE
Add some clarity on Google Analytics, gtag.js and Google Tag Manager

### ISSUE THREAD

**Issue by engram-design** [nystudio107/craft-seomatic#311]
Just because I'm a completionist at heart, I want to tick all the things. It's be good to add a little extra clarity, or success sign when setting up these 3 items.

For instance, Ideally people would use GTM, which means GTAG and GA aren't needed. It'd be cool to see these as "on", or some hint text saying it's all good. Likewise for GTAG, you don't need GA because its the newer thing.

Cheers!

**Comment by khalwat** [comment]
So I'm a little torn on this one... because while best practice would be that GTM is used to then load either `gtag` or `ga`, I don't really want to make any assumptions. Who knows what setup people might be using?

Additionally, none of the analytics tracking scripts "know" about each other. So there isn't really a great way for one to look at the state of the other, at least currently.

I think I'll probably solve this via revisions to the docs.
