### ISSUE TITLE
Option to transform the SEO Images to JPG

### ISSUE THREAD

**Issue by michalbulla** [nystudio107/craft-seomatic#321]
Hey Andrew, in SEOMatic for Craft 2, there was an option to choose the Image Transformation from the list of all Assets Transformations. This way, it was possible to convert the SEO Images to JPG. In the new version for Craft 3, there are just 3 options: Crop, Fit and Stretch. One customer is uploading logos as transparent pngs and since Facebook is adding black background, it doesn't look good. Is there any way to transform the images so the customer doesn't have to re-upload them ?

Thanks!!

**Comment by khalwat** [comment]
So ironically, SEOmatic used to automatically convert images to JPEG for social sharing, but we had people complain because they had clients who were uploading PNGs, and they really and truly wanted them to be PNGs.

Since the SEOmatic fields accept Twig code, you could do write some code to do the type of image transformation you're talking about in Twig (either in your template, or in the SEOmatic fields) and use that for the `.ogImage`

So roughly something like:

```twig
{% set transform = {
    mode: 'crop',
    width: 1200,
    height: 600,
    quality: 75,
    format: 'jpeg'
} %}

{% do seomatic.meta.ogImage(entry.someasset.getUrl(transform)) %}
```

**Comment by michalbulla** [comment]
Thanks Andrew!
