### ISSUE TITLE
Setting custom title doesn't work

### ISSUE THREAD

**Issue by lenvanessen** [nystudio107/craft-seomatic#353]
Using i'm trying to override a title
`{% do seomatic.meta.seoTitle("Some Title") %}`

But it's not working, what can be the issue?
Using version `3.1.45`

**Comment by lenvanessen** [comment]
This is the issue on a 404 route. But actually it matches a template for our Craft Commerce checkout, so we're trying to prevent the title being 404. How can we solve this

**Comment by khalwat** [comment]
So the above code definitely should let you change the title. Can you elaborate on what you mean about it being a 404 route that matches a template?

**Comment by lenvanessen** [comment]
@khalwat when craft doesn't find a entry with a certain slug, it looks in the templates folder if it can match a twig file.

If that is the case, it will load the twig file (if it isn't prefixed by _).

So in our case:
SITEURL.nl/webshop/checkout/addresses shows /templates/webshop/addresses.twig

So technically it isn't a 404, a valid template is shown. But it's giving a 404 as a title, so we wanted to override it using the mentioned method, no luck.

**Comment by khalwat** [comment]
Okay, the part I don't understand here is... where is this `404` coming from that the title is set to? It must be coming from somewhere?

**Comment by XianHain** [comment]
I had the same issue earlier. I needed to clear the seoMatic caches and it rendered as expected.

**Comment by khalwat** [comment]
Yes, if you change the title via Twig, you will need to clear the caches (once) for it to work properly. Since clearing caches is generally done on deploy as a best practice, this shouldn't be an issue normally.

Make whatever changes you need via Twig, push the changes, your deploy process clears the data caches, and everything "just works".

If you are setting it dynamically in some way that it can change (for the same URI) from request to request, then you'll need to clear the level 2 cache @CRHain88 via:

```twig
{% do seomatic.tag.container.clearCache(true) %}
```

Again, the above is almost never needed. You'd only need to clear the cache in that manner if you dynamically change the title in such a way that you want it to be different for the same URI.

**Comment by khalwat** [comment]
@lenvanessen I'm leaving this open because I still don't fully understand the issue you're having?

**Comment by lenvanessen** [comment]
@khalwat the clear cache worked! so we can close it,
thanks for the hint
