### ISSUE TITLE
Google Analytics code not rendering in latest update

### ISSUE THREAD

**Issue by apitel** [nystudio107/craft-seomatic#371]
After updating to the lastest version of SEOMatic (3.1.47), the Google Analytics tag is no longer rendering in templates. No other changes have been made other than updating the plugin. Caches were cleared on all fronts.

**Comment by khalwat** [comment]
Is `devMode` on for your production environment? What is the name of your production environment? What value do you have set in SEOmatic -> Plugin Settings for **Environment** ?

**Comment by apitel** [comment]
devMode is not on. I'm not sure what you mean by "name of my production environment." 

For Plugin Settings, the value for Environment is: live

**Comment by khalwat** [comment]
So in your multi-environment config, what do you have the Craft `.env` `ENVIRONMENT` variable set to?

If you go to SEOmatic -> Tracking Scripts is GA listed there as being enabled?

**Comment by apitel** [comment]
I define the `ENVIRONMENT` variable in `index.php` as `define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');`

I am not using a multi-environment config and do not have a `.env` file. 

Google Analytics is enabled under Tracking Scripts and my Google Analytics Tracking ID is defined. This has not changed since I first set up the plugin a year ago. The only change was an update to SEOMatic.

**Comment by khalwat** [comment]
What is `getenv('ENVIRONMENT')` returning? The reason I'm asking about all of these environmental questions is that Tracking Scripts and a few other things do not render in certain environments, to protect people against sending tracking information from a dev/staging site, etc.

A change made in 3.1.47 was to attempt to make it smarter about actively detecting the environment, because many people were not setting their SEOmatic Environment properly:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/Environment.php#L67

So I'm wondering what your `ENVIRONMENT` is actually set to, and if this isn't the cause of the issue, or if there's some kind of bug/regression in the SEOmatic code that does the detection.

**Comment by apitel** [comment]
Hm. It's showing up at `dev` in the Craft Control Panel's PHP Info. Very odd considering I have `'devMode' => false,` in the general.php file.

**Comment by khalwat** [comment]
It's possible that the multi-env config in `general.php` isn't set up right. A common thing that I see is there is no `'*'` key present, which is required for Craft to parse it as a multi-env config.

**Comment by apitel** [comment]
`ENVIRONMENT` variable in `.env` changed to production and caches clear. Issue resolved.

**Comment by khalwat** [comment]
Great glad to hear!
