### ISSUE TITLE
[Bug] Paginate helper in multi-site showing pages that do not exist in other sites

### ISSUE THREAD

**Issue by stevepsharpe** [nystudio107/craft-seomatic#375]
So we have a multi-site setup which has English, German, French and Spanish.

We are paginating an authors articles in a blog. The author may have many articles in english spanning multiple pages, but not many in German for example, so no need to paginate the results.

We are using the paginate helper.

`{% do seomatic.helper.paginate(pageInfo) %}`

Here's an example
https://www.applause.com/blog/author/dan-haggerty/p2

When viewing the source you can see it's including the following, even though additional pages do not exist for those languages.

![Screenshot 2019-04-24 at 10 20 16](https://user-images.githubusercontent.com/2507/56648238-d78e9600-667a-11e9-88d3-f3deff4a1138.png)

I would only expect it to show the links for the languages that have content on those pages.

Any help would be greatly appreciated :)

**Comment by khalwat** [comment]
What version of SEOmatic are you using?

**Comment by stevepsharpe** [comment]
Hey @khalwat, 3.1.48

**Comment by khalwat** [comment]
Please update to 3.1.49, and let me know if your issue was fixed here -> https://github.com/nystudio107/craft-seomatic/blob/v3/CHANGELOG.md#3149---20190422

**Comment by stevepsharpe** [comment]
Great, thanks. Will do.

**Comment by chasegiunta** [comment]
@khalwat Updated the site's SEOmatic version to 3.1.49, and cleared caches, but unfortunately this issue is still present.

**Comment by khalwat** [comment]
I don't believe you. :)

**Comment by chasegiunta** [comment]
Haha that's fair 😄

**Comment by khalwat** [comment]
But seriously... can you give me something to go on? Try checking those traces we did earlier?

**Comment by chasegiunta** [comment]
@khalwat Yeah I'll try to dig in again and see what you changed and do a little bit of troubleshooting. The same page Steve shared is applicable https://www.applause.com/blog/author/dan-haggerty/p2 .

**Comment by khalwat** [comment]
Right, but he's using the version _prior_ to the fix.

**Comment by chasegiunta** [comment]
We're working on the same site. I just updated it for him to 3.1.49

**Comment by khalwat** [comment]
I'm confused, but okay! LMK what you uncover. I did test the changes I made, and they worked as expected in my tested, but that doesn't mean something isn't wrong "in the wild" here.

**Comment by chasegiunta** [comment]
I'm trying to think of the best way to word this correctly, and to accurately relay the problem.

I think to put it simply, upon generating the `rel=alternate` links, the `pageInfo.currentPage` isn't taken into account - and it may be that the paginated elements may not be taken into account at all, and instead the rel=alternate links are being generated based on the current template's `entry`, not the paginated elements...?

In this case, Dan is an entry within an Author's section. This page (https://www.applause.com/blog/author/dan-haggerty) is showing all English blog posts related to the template's `entry`, Dan. The pagination query being executed here is on a completely different section than the current template's `entry`. 

Dan has written articles in all the languages:
https://www.applause.com/de/blog/autor/dan-haggerty
https://www.applause.com/fr/blog/auteur/dan-haggerty
https://www.applause.com/es/blog/autor/dan-haggerty

But he hasn't written enough (there's not enough related blog post entries) to justify a `p2`, so `p2` alternate links for those pages shouldn't be generated.

I could be wrong here, but I think the fix you put in might be looking at whether the section is enabled for the current template's `entry`, rather than elements queried for pagination.

Infact, if I disabled the other sites for the Blog section completely, the links are _still_ generated for Dan.
![image](https://user-images.githubusercontent.com/1377169/56931258-08b8fd00-6aa5-11e9-8fb7-4c57445a31a5.png)

![image](https://user-images.githubusercontent.com/1377169/56931283-179faf80-6aa5-11e9-8be0-96910c5ab48a.png)

I only see a difference when I disable the sites for the Author section, which is **not** what we're paginating through:
![image](https://user-images.githubusercontent.com/1377169/56931375-651c1c80-6aa5-11e9-8281-0fa32f0cfd5c.png)
![image](https://user-images.githubusercontent.com/1377169/56931387-6f3e1b00-6aa5-11e9-83ff-51c776fa24c2.png)

(technically ^^^ even that may not be correct, as it possibly shouldn't be be pointing to the homepage)

Best I can do!

**Comment by khalwat** [comment]
Very helpful! Can you show me the SEOmatic code you're using in terms of... where are you putting:

```
{% do seomatic.helper.paginate(PAGEINFO) %}
```
...and what are you passing into it?

**Comment by chasegiunta** [comment]
```
{# Author template (blog/_author.twig) #}

{% set entries = craft.entries.relatedTo(entry).orderBy('postDate desc') %}

{% if entries | length %}
    {% paginate entries.limit(10) as pageInfo, authorEntries %}

    {% do seomatic.helper.paginate(pageInfo) %}
{% endif %}
```

**Comment by chasegiunta** [comment]
I'm realizing how complicated that link generation functionality could become, because it needs to behave differently based on whether you've landed on an `entry` template, thus needing to grab alternate info for said entry, or whether you've landed on an index template, and it's having to generate links based on elements being paginated over. 😅 

Anyway, hit me up on discord tomorrow if you want screenshare & dig into this case.

**Comment by khalwat** [comment]
well, FWIW you can change it to be/do anything you want. Have a look here:

https://github.com/nystudio107/craft-seomatic#link-meta-object-examples

```twig
    {% set alt = seomatic.link.get('alternate') %}
    {% do alt.href([
            'http://example.com',
            'http://example.com/es'
        ]).hreflang([
            'x-default',
            'es',
        ])
    %}
```

Perhaps that's the best option here?

**Comment by khalwat** [comment]
So let's see if we can't unpack this a bit.

the `<link rel="alternate" hreflang>` tags should express links to pages in other languages of the _current page_.

So for an entry page, it should be links to that _entry_ page in another language. For an index page, it should be links to an _index_ page in another language.

So you are correct that the `<link rel="alternate" hreflang>` on an index page should totally ignore the paginated entries. They aren't relevant to the discussion, because these tags are presenting alternative versions of the _current page_ in different languages.

And in this case, the current page is an index page the lists other entries.

So this being the case... what is not working as expected?

**Comment by khalwat** [comment]
Okay so based on some articles I've read:

https://support.google.com/webmasters/answer/189077?hl=en

https://www.link-assistant.com/news/10-hreflang-issues.html

https://webmasters.stackexchange.com/questions/88622/shall-i-add-hreflang-on-pagination-sites-which-are-using-rel-prev-and-rel-nex

And here's what I think. Right now we have:

```html
<link href="https://www.applause.com/blog/author/dan-haggerty" rel="canonical">
 
<link href="https://www.applause.com/es/blog/autor/dan-haggerty" rel="alternate" hreflang="es">
<link href="https://www.applause.com/fr/blog/auteur/dan-haggerty" rel="alternate" hreflang="fr">
<link href="https://www.applause.com/de/blog/autor/dan-haggerty" rel="alternate" hreflang="de">
<link href="https://www.applause.com/blog/author/dan-haggerty" rel="alternate" hreflang="en">
<link href="https://www.applause.com/blog/author/dan-haggerty" rel="alternate" hreflang="x-default">
```
and then on page 2 of the paginated page, we have:

```html
<link href="https://www.applause.com/blog/author/dan-haggerty/p2" rel="canonical">
 
<link href="https://www.applause.com/es/blog/autor/dan-haggerty/p2" rel="alternate" hreflang="es">
<link href="https://www.applause.com/fr/blog/auteur/dan-haggerty/p2" rel="alternate" hreflang="fr">
<link href="https://www.applause.com/de/blog/autor/dan-haggerty/p2" rel="alternate" hreflang="de">
<link href="https://www.applause.com/blog/author/dan-haggerty/p2" rel="alternate" hreflang="en">
<link href="https://www.applause.com/blog/author/dan-haggerty/p2" rel="alternate" hreflang="x-default">
```

Based on what I've read, I believe the _right_ answer is that even for Page 2, the `canonical` and `hreflang` links should be:

```html
<link href="https://www.applause.com/blog/author/dan-haggerty" rel="canonical">
 
<link href="https://www.applause.com/es/blog/autor/dan-haggerty" rel="alternate" hreflang="es">
<link href="https://www.applause.com/fr/blog/auteur/dan-haggerty" rel="alternate" hreflang="fr">
<link href="https://www.applause.com/de/blog/autor/dan-haggerty" rel="alternate" hreflang="de">
<link href="https://www.applause.com/blog/author/dan-haggerty" rel="alternate" hreflang="en">
<link href="https://www.applause.com/blog/author/dan-haggerty" rel="alternate" hreflang="x-default">
```

In other words, the canonical URL should always point to the non-paginated page, and the `alternate` links should _also_ always point to the non-paginated page.

For the same reason.

Which is that for paginated pages, the pages themselves can be localized in a variety of languages, but the _content_ may be different because the paginated results can vary from localization to localization.

Relevant excerpt:

> alternate+hreflang should only be used for translations. But if your English page 3 could contain the items {A, B, C, D} and your Swedish page 3 could contain the items {B, D, E, F}, they aren’t really translations of each other. It wouldn’t make sense for a user to switch from English p. 3 to Swedish p. 3, because it could list totally different items (e.g., most of the items the user already saw on the English p. 2), and so it wouldn’t make sense for search engines to understand or show them as translations.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/11846dbd05df201124f56c2ae9f14319145f45ce

Okay so with these changes, what was this:
```html
<link href="http://craft3.test/es/bloges/p2" rel="alternate" hreflang="es">
<link href="http://craft3.test/blog/p2" rel="alternate" hreflang="en-us">
<link href="http://craft3.test/blog/p2" rel="alternate" hreflang="x-default">
<link href="http://craft3.test/blog" rel="prev">
<link href="http://craft3.test/blog/p3" rel="next">
```

Now becomes this:
```html
<link href="http://craft3.test/es/bloges" rel="alternate" hreflang="es">
<link href="http://craft3.test/blog" rel="alternate" hreflang="en-us">
<link href="http://craft3.test/blog" rel="alternate" hreflang="x-default">
<link href="http://craft3.test/blog" rel="prev">
<link href="http://craft3.test/blog/p3" rel="next">
```
