### ISSUE TITLE
Rendering Metadata from another Route

### ISSUE THREAD

**Issue by LouisCuvelier** [nystudio107/craft-seomatic#386]
Hi,

After your answer in #376, you tell to « [Render Metadata from another Route](https://nystudio107.com/blog/tips-for-using-seomatic-effectively#rendering-metadata-from-another-route) », but how this solution is managing the sitemap ? Or, how can I manage the sitemap automatically ?

Thanks for your time 👌

**Comment by khalwat** [comment]
So because you have custom routes, you're going to need a custom sitemap. SEOmatic has hooks for letting you do that via code, or you can just add in the URL to your additional sitemap (generated however you choose) via SEOmatic → Site Settings → Sitemap

If you want to do it via code, check out:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/SitemapIndexTemplate.php#L39

and

https://github.com/nystudio107/craft-seomatic/blob/v3/src/models/SitemapIndexTemplate.php#L39
