### ISSUE TITLE
Robots content remains none inside the API endpoint

### ISSUE THREAD

**Issue by Wiejeben** [nystudio107/craft-seomatic#391]
I can reproduce this issue on some sites but not all...

The website is set to production, the environment in plugin settings is set to live and the entry with the global and content SEO are all set to "All - Index this page and follow links (default)".

When looking at the tags inserted into the `<head />` by SEOmatic, it shows
```html
<meta name="robots" content="all">
```

However from the `/actions/seomatic/meta-container/all-meta-containers?asArray=true&uri=/` and `/actions/seomatic/meta-container/all-meta-containers?uri=/` endpoints it gives back that my robots are set to none.

I have cleared the cache, updated Craft and plugins, tested it on my local environment (which has a different PHP and MySQL version), but am unable to get the robots to become all.

PHP 7.1.28
Craft Pro 3.1.25
SEOmatic 3.1.50

**Comment by khalwat** [comment]
So here are two live sites that are using SEOmatic 3.1.50

nystudio107 -> https://nystudio107.com/actions/seomatic/meta-container/all-meta-containers?uri=/

devMode.fm -> https://devmode.fm/actions/seomatic/meta-container/all-meta-containers?uri=/

If you search on "robots" you'll find the tags, which both have `content="all"` -- so I'm going to think this has something to do with your environment.

You won't be able to get it to work in your local dev environment, because if `devMode` is on, it will force the environment to be `local` (which causes the meta robots to be `none`).

Similarly if you have a dev-sounding `ENVIRONMENT` it's also going to force it to be `local` -> https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/Environment.php#L32

So this is very likely going to be something with your `ENVIRONMENT` or with `devMode`, if I had to guess.

**Comment by Wiejeben** [comment]
I have send you a ZIP on Discord containing an environment experiencing this issue. Hopefully you'll be able to recreate it!

**Comment by Wiejeben** [comment]
As discussed on Discord. After resaving the Global SEO it changed the value for the API endpoint to `all` as it is supposed to be.

I think (but you would probably know better) this was maybe because some JSON in the database was still from an older version of SEOmatic and needed to be resaved.

You may close this issue. Included in the ZIP I had put an SQL export for you to have a look at.

**Comment by johnfoland** [comment]
I'm having the same issue, but modifying the content of fields and resubmitting / resaving the "Global SEO" form doesn't fix the problem.  My `ENVIRONMENT` is `live` and I'm not in `devMode`.

**Comment by khalwat** [comment]
@johnfoland have you gotten this addressed?

**Comment by johnfoland** [comment]
@khalwat Thanks for following up!  Yes, this was ultimately fixed by setting the environment variable explicitly within the swarm, although we never got to the bottom of where the `dev` was coming from in the first place.  Kind of weird that there is no (effective) manual override possible within the application via database.
