### ISSUE TITLE
Selecting CreativeWork -> Article -> BlogPosting only saves CreativeWork and Article

### ISSUE THREAD

**Issue by dreadfullyposh** [nystudio107/craft-seomatic#397]
When creating a new entry and selecting CreativeWork -> Article -> BlogPosting as the Main Entity of Page, CreativeWork and Article are saved, but the BlogPosting is not saved.

Adding BlogPosting again after the first save and then saving again will save BlogPosting correctly.

Craft 3.1.27
SEOMatic 3.1.50

**Comment by khalwat** [comment]
So this is using the SEO Settings Field?

**Comment by dreadfullyposh** [comment]
Yes, sorry. The SEO Settings field.

**Comment by khalwat** [comment]
Wow that's a weird one. Just replicated it. So strange.

**Comment by khalwat** [comment]
So this was a fun one. It ends up being that the issue only happens when one of the menus or sub-menus is dynamically updated via JavaScript. In that case, the `value` has the visual padding intended for the menu display:

![Google ChromeScreenSnapz002](https://user-images.githubusercontent.com/7570798/58189319-4534de80-7c88-11e9-930e-a09899ccedad.png)

This caused it to be unable to find a schema of that type, and so it wouldn't save. The reason it works the second time around is the menu is not added dynamically.

Fixed in https://github.com/nystudio107/craft-seomatic/commit/1b07fab17050cabb7ac7ed26363cd2bddb171c9e
