### ISSUE TITLE
Using the JobPosting subtype on SEOMatic field includes fields that produce warnings in Google's structured data testing tool

### ISSUE THREAD

**Issue by dreadfullyposh** [nystudio107/craft-seomatic#400]
I am using the SEOMatic field on a section and setting the Main Entity of Page to Intangible -> JobPosting

When running the page through Google's structured data testing tool, there are a number of warnings about fields in the JobPosting entity that aren't recognized for the JobPosting type.

These are the fields throwing warnings:
dateModified	
datePublished	
headline	
inLanguage	
author	
copyrightHolder	
creator	
publisher

I realize Google's interpretation may not match the spec exactly, so that could make it tricky to pull these out automatically. 

Is there a way I can remove them manually from within a template, similar to how I can add?

**Comment by khalwat** [comment]
So the issue here is actually that some changes in the SEO Settings field caused it to override the JSON-LD model type improperly, so the model wasn't actually a `JobPosting` (which doesn't have these attributes).

Fixed in https://github.com/nystudio107/craft-seomatic/commit/1ca809b7c80903fbabb509fd8a27ba4778e3e5c5

(I know the commit message seems unrelated, but this is fixed with this commit as well)
