### ISSUE TITLE
Wrong Open Graph Image and errors

### ISSUE THREAD

**Issue by LouisCuvelier** [nystudio107/craft-seomatic#425]
Hi,

I'm facing a problem quite annoying. Sometimes, the og:image (same for Twitter) come from another page.

I suppose the problem comes from the fact that SEO image keeps the URL of the generate transform and not the image itself.

For exemple : 
```html
<meta content="https://www.coursierjob.com/index.php?p=actions/assets/generate-transform&transformId=17" property="og:image">
```

In addition, it gave me a lot of « Anomaly during the exploration » in the Search Console because of the transform URL.

Any idea why ?

**Comment by khalwat** [comment]
So what's probably happening is that the image transform hasn't been generated yet, and you don't have [generateTransformsBeforePageLoad](https://docs.craftcms.com/v3/config/config-settings.html#generatetransformsbeforepageload) set to `true` so when the page first renders, it has to url the URL that the transform service returns.

This is exactly what would happen if you had an image transform in your templates, the difference being that Craft does a bit of magic to make sure that it _doesn't_ cache anything if the image transform isn't generated, whereas SEOmatic does not.

**Comment by khalwat** [comment]
So originally I had SEOmatic passing in a flag telling Craft to generate the SEO image transforms _now_ but for people using it on single threaded PHP local dev environments, this cause Craft to hang. This was down in the bowels of Craft's Asset Transform Service, where it was waiting for another process to finish... which it never did, because single threaded PHP.

But this got me thinking that since SEOmatic knows about environments, I could have it so that as long as we're not in `local` dev, it'd tell the transform to be generated before page load. That should neatly fix this issue for you.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/f2a4b0ec5885f438e5e9b625b3db1b1fad002bc8

**Comment by LouisCuvelier** [comment]
Hi @khalwat,
I was waiting to get results since your first answer. It has not be very long, but it seems to work !
I added generateTransformsBeforePageLoad to true on the prod config, as you said.

Anyway, thank you for the deep fix to this issue ! I will update !
If SEOmatic handles this, should I keep generateTransformsBeforePageLoad to true or not ?

**Comment by khalwat** [comment]
Up to you whether to keep that setting on or not; I typically have it on.

**Comment by LouisCuvelier** [comment]
So, I will follow you 😉
