### ISSUE TITLE
URLs in generated sitemap are incomplete

### ISSUE THREAD

**Issue by romainpoirier** [nystudio107/craft-seomatic#453]
URLs in generated sitemap are incomplete and are generating error in the Google Search Console.

Example:
1. [https://www.charleroi.be/sitemap.xml](https://www.charleroi.be/sitemap.xml): check [https://www.charleroi.be/sitemaps-1-section-news-1-sitemap.xml](https://www.charleroi.be/sitemaps-1-section-news-1-sitemap.xml)
2. Check `loc` nodes: URLs does not contains the root URL (example: [http:/actualites/63e-anniversaire-de-la-catastrophe-du-bois-du-cazier](http:/actualites/63e-anniversaire-de-la-catastrophe-du-bois-du-cazier) instead of https://www.charleroi.be/actualites/63e-anniversaire-de-la-catastrophe-du-bois-du-cazier)

**Comment by khalwat** [comment]
Probably your `siteUrl` or the URLs in your asset volumes are not set up correctly.

SEOmatic just asks the assets for their URLs:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/jobs/GenerateSitemap.php#L421

**Comment by romainpoirier** [comment]
The `siteUrl` is correctly set: I get `https://www.charleroi.be` when I use this variable within a template.

All volumes are setup correctly. For example, when I go to Assets → Preview file, I can show it up and open the file on a new window without any problem. Same within a template, I can output a file.

Below is an example of how this paths are set up from `config/general.php` file:
```
$basePath  = $_SERVER['DOCUMENT_ROOT'];

$uriScheme = (isset($_SERVER['HTTPS'])) ? 'https://' : 'http://';

$baseUrl = $uriScheme.$_SERVER['HTTP_HOST'];
$rootUrl = $baseUrl;

$assetsFolder = '/assets';
$assetsBaseUrl = $baseUrl.$assetsFolder;
$assetsBasePath = $basePath.$assetsFolder;

$siteUrl = $rootUrl;
```

**Comment by khalwat** [comment]
The sitemaps are created via queue job -- are you perhaps running your queue jobs in a background task or such where the siteUrl might not be correctly set?

**Comment by khalwat** [comment]
Oh I see yeah you probably don't want to do this:
```php
$basePath  = $_SERVER['DOCUMENT_ROOT'];

$uriScheme = (isset($_SERVER['HTTPS'])) ? 'https://' : 'http://';

$baseUrl = $uriScheme.$_SERVER['HTTP_HOST'];
$rootUrl = $baseUrl;

$assetsFolder = '/assets';
$assetsBaseUrl = $baseUrl.$assetsFolder;
$assetsBasePath = $basePath.$assetsFolder;

$siteUrl = $rootUrl;
```

Instead you should define your `$baseUrl` to something explicit. The method you're using (in addition to not working via the CLI) can introduce cache poisoning, because it depends on the incoming `$_SERVER` data being set correct.

Check out the `@web` warning here: https://docs.craftcms.com/v3/sites.html#creating-a-site

> WARNING
> 
> Don’t ever use the @web alias when defining your sites’ Base URLs. It could introduce a cache poisoning vulnerability, and Craft won’t be able to reliably determine which site is being requested.

The same thing applies here, for the same reasons.

**Comment by romainpoirier** [comment]
The `runQueueAutomatically` Craft config is set to `false` because the `queue/run` console command is fired every minute using a cron job (instead of being triggered when a user is logged to the CP).

**Comment by khalwat** [comment]
Right, which is fine -- but see above re: your dynamically attempting to determine the `$baseUrl` via the `$_SERVER` super global. You're going to want to instead put it in an `.env` variable and define it explicitly.

Not just because it won't be set at all when running via the CLI (which is how the SEOmatic queue jobs are run in your case), but also because of the cache poisoning issue.

Also you might consider using `queue/listen` instead as per the [Robust queue job handling in Craft CMS](https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms) article.

**Comment by romainpoirier** [comment]
Thank you for your advice and solutions Andrew! Now the `loc` nodes are correct.
