### ISSUE TITLE
Document exactly was the environment config setting does

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-seomatic#472]
The docs are a bit vague…"This setting controls whether certain things render; for instance…"

It is unclear to me why this setting exists (vs just `devMode`), and especially what "staging" would mean.

**Comment by timkelty** [comment]
FWIW - I think having the `environment` concept in SEOmatic is unnecessary and overly confusing…between multi-env configs Craft's `devMode`, SEOmatic's devMode, and the renderEnabled/sitemapsEnabled, etc there are more than enough tools to configure things the way you want.

**Comment by khalwat** [comment]
I agree is is confusing, but it is necessary.

It solves the following problems:

1. SEOmatic needs to map your names for local development and staging environments to a normalized internal naming scheme for them. You can name them whatever you want, so there needs to be some way for SEOmatic to figure out what is what.

2. The additional setting is needed in general because we want to do different things on a per-environment basis, independent of `devMode` or not (tho `devMode` does force it to the local development environment). This is to avoid having staging sites being indexed by Google (extremely common), having local dev/staging sending analytics or other data when it should not, etc.

**Comment by timkelty** [comment]
> to do different things on a per-environment basis

I think at least the docs need to state specifically what those things are. Is it only robots/indexing and GA?

**Comment by khalwat** [comment]
I'll double-check that they do, but I'm pretty sure it's in there... and there's a new UI element that mentioned this as well.

Any container can in theory do different things based on the environment. Currently the only things that SEOmatic changes out of the box is:

1. Robots tag settings
2. `robots.txt` output
3. All script containers

**Comment by timkelty** [comment]
Are there separate config options to toggle each of the things it does? If so, it would be nice for someone like me who would rather control these things with more precision, and I could just ignore `environment`

**Comment by khalwat** [comment]
Nope, there is not.

**Comment by khalwat** [comment]
Updated docs in https://github.com/nystudio107/craft-seomatic/commit/3fa2500ef5e6c95a074a77e7bc28e12a52b706d9

**Comment by khalwat** [comment]
If you really wanted to change this behavior yourself, you can via:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/seomatic-config/globalmeta/TagContainer.php#L65

https://github.com/nystudio107/craft-seomatic/blob/v3/src/seomatic-config/globalmeta/ScriptContainer.php#L36

...and this template is editable:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/templates/_frontend/pages/robots.twig#L4
