### ISSUE TITLE
Potential Server Side Injection Issue

### ISSUE THREAD

**Issue by bryantAXS** [nystudio107/craft-seomatic#477]
A client of ours had a security scan done on their site and they called out a potential vulnerability. In this case, if we had the URL https://examplesite.com?token={{ 7 * 10 }}, "70" was being returned in the HTML response. 

I took a closer look and the output itself was happening inside some JSON-LD data from SEOMatic. https://cl.ly/b7a650d61490

Is this an actual problem? Is it an SEOMatic issue? Craft?

Thanks for the help!

**Comment by khalwat** [comment]
@bryantAXS what version of Craft, and what version of SEOmatic? This was fixed in https://github.com/nystudio107/craft-seomatic/releases/tag/3.2.19

It was also fixed in recent versions of Craft, which would error with that as being an invalid token.

So the fix is to update to the latest Craft CMS, and the latest SEOmatic. I just tested it with the above URL, and it errored as expected.

**Comment by bryantAXS** [comment]
Thank you!
