### ISSUE TITLE
[FR] Fix field settings always overriding "Content SEO" settings

### ISSUE THREAD

**Issue by engram-design** [nystudio107/craft-seomatic#488]
I don't consider this a feature request, but a bug - but I know you've stated a few people complained about the original behaviour. I would like to hear from those people, as I find the current behaviour pretty confusing for a client.

Here's the scenario - we have a channel of content called "Pages". This is general content, and ranges from "About us" to "Terms & Conditions" to landing pages and other entry types. We want to setup sane defaults in the Content SEO area, but also allow clients to override anything on a per-entry basis. For example, maybe they build a landing page for a campaign, and have very specific description/titles. Or maybe they want to no-index certain pages.

This seems easy enough with adding the SEOmatic field to the section - great! The only issue is that once the field has been added to the section, it will always use those values, and disregard any changed to the Content SEO.

Take the following example. 

In Content SEO for Pages, I have the "SEO Title Source" set to "Source Field: Page Heading" - a custom plain text field. Having added the SEOmatic field to the pages section, the field also shows this, the preview is fine, and the output on the page is correct.

I decide later on that I want to change the global title to some custom text. I update this on Content SEO, save and go to look at my entry. It still shows the value from Page Heading, because its using the setting for the field, not the global Content SEO.

What I propose is that by default, the field should have a "Use global value" that can be changed per-entry. That way, when you save the entry, it'll be always referring back to the Content SEO settings, rather than taking a snapshot of them at the time, and using them forever. Otherwise, we have to customise the SEO for every single entry in a channel, which isn't going to happen.

What are your thoughts? I don't think this should be a breaking change?

**Comment by khalwat** [comment]
So in general, I like this idea. The change was originally made from the behavior that you want (which mostly existed already) to the current behavior because people complained that the "override" wasn't obvious.

However, I think if we had a field that clearly said "Use Content SEO Setting" or something like that, perhaps that'd be ideal.

**Comment by engram-design** [comment]
@khalwat I can see how that might be confusing, but at the moment its very much either use the Content SEO settings, or the field - using both doesn't really work nicely! I think "Use Content SEO Setting" would be valid for the dropdown options.

Not sure if you recall the original complaints, but maybe good to get their opinion?

**Comment by khalwat** [comment]
I think it's primarily because I chose poor UX, in that the field were just blank by default. People expected them to show whatever was set in the Content SEO settings.

But if we put "Default" or "Same as Content SEO" or what have you, perhaps that's enough of a cue to make it nice for everyone.

**Comment by khalwat** [comment]
Alright so I dove in thinking this would be a quick easy change, but now I remember the issue.

What _really_ should happen here is when settings are in a Field context, there should be:

1. A preview of the current setting (whether text or image or whatever)
2. An Override light switch that toggles:
  a. Hides the preview of the current setting
  b. Shows the UX letting people override the setting

This is how I've _really_ wanted to do this, because I think it's better UX, and more clearly shows what is going on.

**Comment by engram-design** [comment]
@khalwat Sounds about right to me!

**Comment by davidhellmann** [comment]
We run into the same problem.
Content Seo `robots` is set to none. We've also a SEO Field on each entry and now each entry set the Robots settings to `all (default)`. For me the default value must be the first on `blank` what mean it uses the content seo settings. Or do I miss something here?

![image](https://user-images.githubusercontent.com/764292/68676884-453cd980-055b-11ea-933c-5d3dc804d8a4.png)

**Comment by khalwat** [comment]
@davidhellmann you're right, it should be defaulting to the blank value. Fixed in https://github.com/nystudio107/craft-seomatic/commit/b83d299b86845c194423d167f262ca5cbf339618

Note that you can fix it yourself via the `seomatic-config` as described here: https://nystudio107.com/blog/tips-for-using-seomatic-effectively#customized-setup

**Comment by davidhellmann** [comment]
I wait for the release, thanks!

**Comment by khalwat** [comment]
The original issue that @engram-design mentioned has been addressed in: https://github.com/nystudio107/craft-seomatic/commit/ab3502a4e6536aac6550d03d80378090949f52a7

Also I've made a new FR to discuss better ways to handle the observability issues that caused me to go down this path to begin with:

https://github.com/nystudio107/craft-seomatic/issues/535

I still want to add some migration code so that you can re-save a Section, and it'll update any SEO Settings fields by looking to see if the field values match the Content SEO values, and if so, set the Field values to `''` so that overrides will work retroactively.

I'll close this issue once that code is in place.

**Comment by khalwat** [comment]
When an entry is saved, if the value in an SEO Settings field matches the value in Content SEO for that section, the field is set to an empty value to allow for overriding -> https://github.com/nystudio107/craft-seomatic/commit/e8e3610e17ab9022717f2f1f2870949f4512a9d8

**Comment by karensg** [comment]
I agree that the value should stay empty if it is same as inherited. Is it an idea to display under it which value it actually is? In case of `Robots` field it is not really clear at this moment.

Would be great for sites where there are more people working on the SEO setup.

**Comment by khalwat** [comment]
@karensg yes have a read here: https://github.com/nystudio107/craft-seomatic/issues/535
