### ISSUE TITLE
SEOmatic caches meta content with "generate-transform" action urls

### ISSUE THREAD

**Issue by danwill** [nystudio107/craft-seomatic#490]
Our site recently encountered an issue with the Blitz plugin where image paths containing `asset/generate-transform` URLs were being cached as part of the page content: https://github.com/putyourlightson/craft-blitz/issues/125

We have now observed this behavior in the page metadata generated and cached by SEOmatic. SEO images that use the "Transform SEO Image" option can output a transform URL, which is then cached by SEOmatic. Our site receives a fair amount of traffic, so this issue was adding hundreds of image transform jobs to the queue – ultimately bringing the site to a crawl. Manually clearing the SEOmatic metadata caches ultimately resolved the issue. As a precaution, we have disabled any "Transform SEO Image" option in the SEOmatic settings.

As mentioned in the Blitz issue above, Craft will not [cache template content that contains `asset/generate-transform` URLs](https://github.com/craftcms/cms/blob/3.1/src/services/TemplateCaches.php#L272), and Blitz has also [added this check](https://github.com/putyourlightson/craft-blitz/commit/9795a1d965ed5c94c047fabe958d340b7cb58e2f#diff-8b5559e10f0eaedb50032cd4a980c292). Can this also be added to SEOmatic?

**Comment by khalwat** [comment]
Would a fix on my end solve anything here @putyourlightson ? if Blitz is caching the metadata I'd think that any changes I made wouldn't matter here?

From the link, it looks to me that Blitz is only looking in the body for these URLs?

**Comment by danwill** [comment]
Apologies if I wasn't clear. The issue with Blitz has been resolved, but we have since noticed the same issue with the metadata that is being cached by SEOmatic. Image transform URLs are seemingly getting cached by the plugin, which is resulting in a number of tasks getting added to the queue on each page view.

**Comment by putyourlightson** [comment]
The request seems to be to only cache metadata provided it does _not_ contain an image transform. Here is how we do this in Blitz: 
https://github.com/putyourlightson/craft-blitz/blob/9795a1d965ed5c94c047fabe958d340b7cb58e2f/src/services/GenerateCacheService.php#L170-L174

**Comment by khalwat** [comment]
What I was trying to clarify is whether SEOmatic is caching the data, or Blitz is caching the data.

Lacking context, I'm looking at the comment in @putyourlightson 's code:

```
// Don't cache if there are any transform generation URLs in the body
```
Which I thought meant that it would only not cache data if a transform URL was in the _body_ but perhaps it is the entire output, including the `<head>` (where most of SEOmatic's output goes).

In any event, it's a little more involved for SEOmatic to attempt to catch every case of this, because there isn't one monolithic output chunk we can parse, it'd need to do the check in each container's MetaItem.

Another solution would be to just set `generateTransformsBeforePageLoad` to `true` in your `general.php` -> https://docs.craftcms.com/v3/config/config-settings.html#generatetransformsbeforepageload

**Comment by danwill** [comment]
@khalwat SEOmatic was caching the metadata, but it's a good point to clarify. We made 100% sure we weren't looking at an asset cached by Blitz. Once we tracked the issue down to transform urls in the page metadata, we were able to fix the issue by manually clearing the SEOmatic metadata cache in Utilities > Clear Caches.

But, to your point, I'm unsure if Blitz would have also cached the page if there was a transform URL present in `<head>`. We disabled Blitz once the site started to struggle, and flushed the cache prior to re-enabling.

Thank you for the heads-up on the `generateTransformsBeforePageLoad`. I think we will go ahead and enable that as a safeguard.

I certainly appreciate that the issue may be a complex solve. But to possibly help you triage, this issue effectively brought down the site for an extended period of time. The site can receive 16k+ page views/hour at its average peak time, and the transform tasks getting repeatedly added to the queue were overwhelming the servers.

I'd be happy to provide any other information.

**Comment by khalwat** [comment]
Safeguard added in https://github.com/nystudio107/craft-seomatic/commit/d6e8a73f79c7a7e7530e5da021085fb722cc6434

@danwill I'm sympathetic to your plight, and I wasn't attempting to abdicate responsibility, rather just a broader point. Which is that plugging this leak downstream in this manner is going to leave you open to it happening again.

In other words, the pending image transforms leaked out into Blitz; a patch was put in place. Pending image transforms leaked out into SEOmatic; a patch was put in place. There will very likely be something in the future that also then caches these URLs, and a patch will have to be made there as well.

IMO at least, a fix upstream via `generateTransformsBeforePageLoad` is probably the best way to solve it, that or using a service like Imgix or [Setting Up Your Own Image Transform Service](https://nystudio107.com/blog/setting-up-your-own-image-transform-service) so that image transforms are done immediately.

Anyway I hope the above patch helps!

**Comment by khalwat** [comment]
Oh also for queue handling, check out: [Robust Queue Handling in Craft CMS](https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms)

**Comment by khalwat** [comment]
This work for you @danwill ?

**Comment by danwill** [comment]
Yes, thank you @khalwat...this patch combined with the `generateTransformsBeforePageLoad` setting should hopefully do the trick. We will test this out and I'll let you know if we run into any further issues.

I also appreciate the additional article links. We do have the async-queue plugin installed, but you've helped illuminate some alternate approaches we may take on future sites. I'm becoming more interested in using headless Craft with a JAMstack setup, so many of your recent articles have been very interesting to follow. 

Thanks again for your attention on this issue.

**Comment by benjamin-smith** [comment]
Is it worth exploring a SEOmatic specific variable that does the same thing as `generateTransformsBeforePageLoad` but only for images the SEOmatic adds to a page's markup? I think there are a lot of advantages to keeping `generateTransformsBeforePageLoad` off, but for the `og:image`, it won't be generated until the page is shared on social media, whereas all other assets on a given URL will be generated when the page is rendered that first time.

See https://github.com/putyourlightson/craft-blitz/issues/226 for related conversation.

**Comment by khalwat** [comment]
So SEOmatic does this:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/ImageTransform.php#L120

```php
            // If we're not in local dev, tell it to generate the transform immediately so that
            // urls like `actions/assets/generate-transform` don't get cached
            $generateNow = Seomatic::$environment === EnvironmentHelper::SEOMATIC_DEV_ENV ? null : true;
            if ($volume instanceof Local) {
                // Preflight to ensure that the source asset actually exists to avoid Craft hanging
                if ($volume !== null && !$volume->fileExists($asset->getPath())) {
                    $generateNow = false;
                }
            } else {
                // If this is not a local volume, avoid a potentially long round-trip by
                // being paranoid, and defaulting to not generating the image now
                $generateNow = false;
            }
```

It does this weird dance to avoid a state where Craft would hang waiting for the pending image to transform.

**Comment by Coysh** [comment]
Commenting on an absolutely ancient issue - but this issue has cropped up for me. I've got `generateTransformsBeforePageLoad` set to `true` on all environments, and even after clearing all caches etc still getting this in the meta.

**Comment by suprim-simple** [comment]
#2025 anyone having issue 

Found fix for me, it was in identity & creator Entity Brand asset don't add remove it (Seomatic & blitz)

**Comment by khalwat** [comment]
@suprimsimple can you elaborate? What fixed the issue for you?
