### ISSUE TITLE
SEOmatic cache behavior / cache key

### ISSUE THREAD

**Issue by hiasl** [nystudio107/craft-seomatic#499]
In your blog article "Advanced SEOmatic Tips" you have a chapter about SEOmatic's cache behavior and how to bust the cache (https://nystudio107.com/blog/tips-for-using-seomatic-effectively#caching-and-cache-busting).

The use case is a cookie consent, which has an influence on Google's tag manager integration and the solution is to bust the cache if some SEOmatic setting are different under the same URL.

We have exactly the same issue here but I would rather prefer not to bust the cache each time but instead add something to the cache key, e.g. in the example above simply add the cookieConsent boolean to get 2 different versions of the cache.

Is that possible? Thanks!

**Comment by khalwat** [comment]
mmmm currently no, but what you could do is treat whatever is the common case as cached.

In other words, only clear the cache if they _haven't_ consented to the cookie, and otherwise they get the cached version of the page.

Though I will say that at some point, if you are adding a bunch of logic, it may end up being easier to just include the GTM JavaScript yourself, and do whatever logic you need/want to do via JS.
