### ISSUE TITLE
[FR] Have the SEOmatic social preview reflect the changes made in Twig templates

### ISSUE THREAD

**Issue by ColinDorr** [nystudio107/craft-seomatic#526]
**Issue**:
I'm refactoring a old project and have made a seo macro, that checks multiple SEO fields like the Title and compares multiple data fields in my CMS (title, custom title, hero title, etc.) and choses the latest fields, else it uses a fallback field (seomatic global site fallback). This check works and allows the customer to have a little more controle over the SEO data. 

The problem is, that overriding all seo data in my template. If I inspect the head it show alle the expected fields and values.

But in the SEO previewer in Craft it still shows the seo data based on the page title field.

```
	{% do seomatic.meta
  	.seoTitle(seoTitle)
  	.seoKeywords(seoTitle ? seoTitle :seomatic.meta.seoKeywords)
  	.seoDescription(seoDescription)
  	.mainEntityOfPage(entryData.neoProductBrand ? "Product" : seomatic.meta.mainEntityOfPage)
  	.robots(entryData.neoFollow)
	.canonicalUrl(seoCanonicalUrl)
	
  	.seoImage(seoImage)
	.seoImageWidth(seoImageWidth)
  	.seoImageHeight(seoImageHeight)
	.seoImageDescription(seoImageDescription)

	.ogType(entryData.neoProductBrand ? "Product" : seomatic.meta.ogType)
	.ogDescription(seoDescription)
	.ogImage(ogImage)
	.ogImageWidth (ogImageWidth)
	.ogImageHeight (ogImageHeight)
	.ogImageDescription(seoImageDescription)

	.twitterCard(seoDescription)
	.twitterTitle(seoTitle)
	.twitterDescription(seoDescription)
	.twitterImage(twitterImage)
	.twitterImageWidth(twitterImageWidth)
  	.twitterImageHeight(twitterImageHeight)
	.twitterImageDescription(seoImageDescription)
%}
```

**Expected result**:
I would expect, that if the head meta changes and shows the correct data, that the previewer would also use the correct data. 

**Actual result:**
De Craft previewer only listens to the title field and ignores the changes that happen in the page template.  

**Steps to reproduce**:
- Create a custom field ('seoTitle')
- Place the `{% do seomatic.meta.seoTitle(entry.seoTitle) %}` in the head
- Check the CMS previewer vs the Code in the head.

**Comment by khalwat** [comment]
Yeah this is a downside of doing everything via Twig template. Currently SEOmatic does not parse your page templates and then preview the results.

For that to work, I'd need to somehow render the template inside of the already rendered CP template, and then pull out the resulting variables.

That, or just plain render the page and then scrape it for data ala the Twitter Card validator and Facebook OpenGraph debugger.

For it to actually work, it'd need to be done asynchronously in a separate request, because of state concerns.

I'd consider this to be a FR.

**Comment by toddpadwick** [comment]
This would be a much desired feature request. We add lots of multi level image fall back logic in the templates to populate the twitter and OG images. And I often have to explain to the client why the SEO preview is in-correctly saying 'no image' assigned, even though there is. 

Would it be possible to somehow pull in the preview from the url itself, so that it's an actual rendition of the live SEO preview rather than pulling in the SEOMatic fields?

**Comment by khalwat** [comment]
The only way this would be possible is if you put the Twig code in one of the fields in the CP.

There's no great way to tell it to render an arbitrary page, and then scrape the Twig state for the result, in order to get the preview.
