### ISSUE TITLE
FR: De-duplicate queue jobs for sitemap regeneration

### ISSUE THREAD

**Issue by Mosnar** [nystudio107/craft-seomatic#528]
There are a lot of scenarios where elements can be resaved in massive quantity, which in some cases can result in a lot of extra queue jobs. In particular, when importing content using Feed Me or Bulk Editing data. 

Ideally, when a sitemap needs to be regenerated, SEOmatic should check to see if a queue job has already been dispatched for a similar set of elements & cancel the old job prior to starting a new one.

**Comment by khalwat** [comment]
SEOmatic already looks to see if a bulk action is happening, such as re-saving elements:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/services/MetaBundles.php#L371

We check for the `Element` scenario `Element::SCENARIO_ESSENTIALS` (which is set when re-saving elements in Craft) and prevent sitemap duplication in that case.

I worked with Josh when he owned Feed Me to ensure that importing also set that scenario.

As for checking to see if the job is already in the queue, I know of no way to do this. I looked into it because I figured I could just pop queue jobs out that were already in there, but the queue is opaque as far as I was able to determine.

If you find otherwise, I'd definitely be interested.

**Comment by Mosnar** [comment]
Perhaps it's a conflict elsewhere, but I was running a Feed Me update on some Commerce products for some new pricing and ended up with a few thousand Sitemap jobs. I implemented something similar to de-dupe jobs for our Compress plugin. I wanted to dispatch the jobs to generate zip files as soon as they're requested, but only run them as needed. In the case of someone requesting a zip file before a job is completed, I wanted to cancel the job to prevent unnecessary overhead. I did this by storing the job reference in a cache key when it's dispatched:
https://github.com/venveo/craft-compress/blob/master/src/services/Compress.php#L84

Then we use the Craft-specific `release` method to cancel the job:
https://github.com/venveo/craft-compress/blob/master/src/controllers/CompressController.php#L59


Maybe it's not worth it, but maybe it is.

**Comment by khalwat** [comment]
Interesting idea. In my case I think I'd want to release any existing queue jobs, and then just push the new ones. I'll give it a go!

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/52130525fa9c39775d485019fb8b53eb87126255

Code reviews welcome :)

**Comment by Mosnar** [comment]
Looks great, that's exactly what I had in mind! 🔥
