### ISSUE TITLE
Breadcrumbs not fully rendering 

### ISSUE THREAD

**Issue by bartroelands** [nystudio107/craft-seomatic#532]
Hi, 

I have a similar issue as mentioned in issue #228, but I have a single site setup. I have a mix of single and channel sections. The home and all the entry element breadcrumbs are rendered correctly, but for the channel part in the uri no breadcrumb is generated. I verified with a couple of dumps in the source code and the array generated only has entries for home en actual entries. 

Setup is as followed : I have created a section for a team with base uri format set to 'teams/{slug}' and pointing to a twig templates at teams/_teammember.

In the template directory I have a directory called teams with an index.twig template the generates a list of teammembers that link to an individual teammember.twig template to render the corresponding teammember details... This all works fine and, as I understand being new to craft, a standard setup. 

The url looks as expected http://<site-name>/teams/team-member-slug 

I render the breadcrumbs using the function `seomatic.jsonLd.get('breadcrumbList').itemListElement` iterating through the array not getting the 'teams' entry.

Breadcrumb renders for url https://<site-name>/member --> only home appears
for url http://<site-name>/member/team-member-slug --> i get : home / team-member-slug 

I would expect to have home / teams /  and home / teams / team-member-slug 

I am missing something trivial or is this behavious as designed ?

Am currently on craft version Craft Pro 3.3.19 and SEOMatic version 3.2.38
Am also running on PostgreSQL 11.5

Thans for looking into this. 

Bart

**Comment by khalwat** [comment]
It sounds like expected behavior, but it's tough to say without seeing code and your internal structure.

To generate the breadcrumbs, SEOmatic loops through the URL segment by segment, to see if there is a Craft element that corresponds to the given URL. As an example, for the URI `/blog/my-cool-story`, it'll check for an element existing at:

  * /blog/my-cool-story
  * /blog
  * /

If no element has a URI for `/blog` then it'll skip it; if you make a Single for this URI, then it'll find it.

The reason it works this way is it has no real way of knowing what URLs are actually valid (because of how complicated routing setups can be), unless it did a request for each one at runtime, which would be terrible for performance.

So instead it just looks for elements existing that have the given URI.

So you can either create a Single that has the URI of that interim URL, or you can manually add it to the breadcrumbs yourself: 

https://nystudio107.com/docs/seomatic/Using.html#json-ld-meta-object-functions-seomatic-jsonld

**Comment by bartroelands** [comment]
Hi,

Thank you very much for the clear explanation.

Just for my understanding, by element you mean an entry with actual data in
the database, right ? That would be in your example the 'my-cool-story'
element ...
What would be the 'blog' element in your example ? also an entry ?

I indeed also thought to add the entry in the json-meta object myself ...
Could you recommend where and how I would best do this ?
Can I inject an entry in the array per page (in my case the list-page) or
do I need to read out the array and completely replace the breadcrumbs as
in the docu?

Thanks

Bart

**Comment by khalwat** [comment]
The `Blog` element would be a Single, as mentioned.

This link has examples of how to use SEOmatic's API to manipulate JSON-LD and the like yourself via Twig templates:

https://nystudio107.com/docs/seomatic/Using.html#json-ld-meta-object-functions-seomatic-jsonld
