### ISSUE TITLE
seomatic.script.render() now outputting encoded json string instead of html

### ISSUE THREAD

**Issue by danieltott** [nystudio107/craft-seomatic#547]
Prior to [3.2.39](https://github.com/nystudio107/craft-seomatic/releases/tag/3.2.39), calling `seomatic.script.render()` in twig (as per [the docs](https://nystudio107.com/docs/seomatic/Using.html#script-meta-object-functions-seomatic-script)) returned a string. After 3.2.39, it is returning an encoded json object. This is contrary to the docs and resulted in a breaking change for anyone using that twig function.

I'm not sure what the solution is - the solution I used is to change my code to something like this:

```twig
{% set script = seomatic.script.render() %}
{{script.script}} {# inside head #}
{{script.bodyScript}} {# inside body #}
```

My use-case specifically is that I am using Craft as a headless CMS and pumping seomatic `<head>` information into a string that the client then outputs.

This may end up just being an issue that is closed; I'm not sure what the right call is here. I just wanted to note it for anyone else that runs into it (maybe I'm the only one that uses it 😀)

**Comment by danieltott** [comment]
Actually I had to `json_decode` the results of render.

```twig
{% set script = seomatic.script.render()|json_decode %}
```

**Comment by khalwat** [comment]
Thanks for opening a new ticket for this, it'll be useful in case anyone else runs into this. I actually was thinking about the `.render()` function when I made this change, but I thought "nah, no one is using this anyway". Clearly I was wrong.

If Craft is headless, how is Twig rendering anything? I guess I'm confused about the setup you have here, because if Craft was headless, I would think you'd use one of the Controller API endpoints to obtain said information? 

https://nystudio107.com/docs/seomatic/Advanced.html#meta-container-api-endpoints

How is Twig in the mix here?

**Comment by danieltott** [comment]
I'm using twig to output JSON. But it's a pretty simple api, in that I'm using twig to render html and then output it in json form to the requesting server:

```json
{
  "head": "...",
  "body":"..."
}
```

I'm sure I could use the APIs you linked, but I actually _want_ seomatic to render the `<head>` html, because it can and because I trust it.

**Comment by danieltott** [comment]
Just as a note, the service requesting this stuff inserts the results inside its own layout, I'm not just outputting `<head>{{cms.head}}</head><body>{{cms.body}}</body>` 🙂

**Comment by khalwat** [comment]
Gotcha. Okay, that makes sense. The "solution" here is to do what you did, which is to `json_decode` the result (which puts this container inline with how data is returned from the other containers too).

Thanks @danieltott -- sorry for the inconvenience.
