### ISSUE TITLE
How do you set a dynamic title for search queries?

### ISSUE THREAD

**Issue by jonlongnecker** [nystudio107/craft-seomatic#555]
I have a search results page where I need to pass the page title and description through to SEOmatic that include the query itself. 

But I can't figure out the syntax to get it to display. Trying something like this:

````
{% set query = craft.app.request.getParam('q') %}
{% set entries = craft.entries.search(query).orderBy('score').section('blog') %}

{% do seomatic.meta
  .seoTitle("Search Results for {query}")
  .siteNamePosition("after")
  .seoDescription("Check out the search results for {query}")
  .mainEntityOfPage("SearchResultsPage")
%}
````
It outputs "Search Results for "

**Comment by khalwat** [comment]
Try:
```twig
{% do seomatic.meta
  .seoTitle("Search Results for " ~ query)
  .siteNamePosition("after")
  .seoDescription("Check out the search results for " ~ query)
%}
```

I'm not sure what you're trying to do with this part: 
```twig
  .mainEntityOfPage("SearchResultsPage")
```

But you can't just change the type of a JSON-LD object. So the easiest thing to do is create a Single or something for this page, and set the type of MainEntityOfPage there.

**Comment by jonlongnecker** [comment]
So the key here is the ~ character and the variable have to be outside of the quotation marks. Other than forcing a &nbsp; after "for" that got it to work, thanks.

Re: mainEntityofPage - I have multiple pages not part of a structure, entry, or category. From what I can tell, this does get passed through to the JSON-LD for the type of page, and it's listed in the docs as a variable: https://nystudio107.com/docs/seomatic/Using.html#meta-variables-seomatic-meta. 

What am I missing for setting this via a template?

**Comment by khalwat** [comment]
MainEntityOfPage doesn't work like you think it does -- the actual `.mainEntityOfPage()` setting is a URL... saying that this JSON-LD entity is the main entity of the page at the following URL.

What it sounds like you want to do is dynamically change the JSON-LD type that is used as the main entity of the page. For that, you'd do something like this:

What you should do in this case is create a new JSON-LD object to represent the mainEntityOfPage and swap it in.

You cannot just change the type of the JSON-LD object because it's an actual PHP object, just like you couldn't magically change a EntryModel into an SiteModel or whatever.

```twig
{% set newMainEntity = seomatic.jsonLd.create({
    'key': 'mainEntityOfPage'
    'type': 'FAQPage',
    'url': entry.url,
}) %}
```

You're creating a new JSON-LD object of the type FAQPage and using the key param, you're telling it to overwrite the existing mainEntityOfPage

If you're changing the type of the JSON-LD object, you need to create a new object, you can't transform an existing object into another object type
