### ISSUE TITLE
Content SEO Global Fallback not displaying?

### ISSUE THREAD

**Issue by mikestecker** [nystudio107/craft-seomatic#56]
I'm not sure if this was the was you designed it or not, but the way I understood the some of the "Global SEO" fields were to display on pages where the "Content SEO" is either missing or not specified?

I could be understanding this wrong though.

I have set my primary Twitter/FB preview images in the "Global SEO" section and in my "News" content section I have a few different post types: news article, announcement, notice. In SEOmatic Content Settings for my News section, I set my "Primary Image" field as the image to use for Twitter/FB but some only the "news article" post type gets this field. Announcement and Notice don't get this field, and I assumed they would get the image I configured in the "Global SEO" config, but I don't see this actually happening. Am I wrong to assume this?

**Comment by khalwat** [comment]
No, you are correct. It should fall back on whatever Global SEO settings you have configured as a default.

I'm actually not sure what happens if you have multiple post types, some of which do not have a particular field that you're pulling from. I think what is happening is the Section is still set to pull from that field, so there *is* something set, so it overrides the Global SEO settings...

...however when it goes to render the result, the result is nothing since the field doesn't exist, so nothing is shown on the frontend.

**Comment by khalwat** [comment]
btw, a solution for you in the Interim is you could use an SEO Settings Field

**Comment by mgburns** [comment]
@khalwat Should it also be falling back to the Global value when the Content SEO Image / Description Source is set but returns no value? For instance, a `From Asset` source that has no asset set in the asset field or a `Custom Text` source with a Twig expression that returns no value?

**Comment by evanwarner** [comment]
Definitely a huge issue for a site I'm working on. The client wants to just use some defaults for now and fill them out post-launch. But no page, not even the homepage, inherits the defaults.

Oddly, some of the sections in Content SEO _were_ inheriting the globals until I started configuring parts of them I did want to customize (setting up their title, but wanting to inherit the global description). Now I get nothing unless it's specifically set for that section.

**Comment by khalwat** [comment]
@evanwarner They should all inherit the defaults; if you leave fields empty in the Content SEO.

What happens is if you configure the Content SEO to pull from existing fields, the SEO settings then are not empty, but rather contain Twig code that _once parsed_ may or may not be empty based on whatever the values are set from the fields they are pulling from.

So what I've been mulling over for this would be to evaluate the _result_ of the parsed data when combining the containers, which would have the effect that you desire.

**Comment by khalwat** [comment]
So then you might say "well, that's silly, why _aren't_ you just parsing everything before merging?"

One of the powerful things about how SEOmatic works is that each variable can have Twig code in it. So that you can have multiple tags that have their `content=` (or whatever) set to `{seomatic.meta.description}`

So then if we do what SEOmatic does currently, which is it doesn't parse until the last minute, that lets you do something like:

`{% do seomatic.meta.description("woof") %}` and you'll be assured that _everywhere_ that uses the  `{seomatic.meta.description}` will be updated in one fell swoop.

 If in Content SEO you set up the SEO Description to _pull_ from another field, what is actually put into that SEO Description is something like: `{seomatic.helper.extractTextFromField(entry.someField)}` which means we again are evaluating this lazily, which is great.

This all works great; but an unintended side-effect is what is being mentioned here, is that then the SEO Description isn't empty, it has Twig code in it, so when SEOmatic merges the containers, the Content SEO setting overrides the Global SEO setting... and then it gets lazily parsed to being empty (if the field it is pulling from is empty).

Mostly just describing what is actually going on here so that you can understand it isn't that I'm being lackadaisical about it, it's a bit of a sticky problem that I'm trying to work out the best solution to.

**Comment by khalwat** [comment]
Another thing you might say is "Well, fine, but then why not just revert to the Global setting if the parsed Content SEO setting ends up being empty?"

It's not quite that simple, SEOmatic works on the concept of an arbitrary number of containers that get coalesced together. First the Global SEO container is added, then we layer on top any Content SEO containers, and then we layer on top any Field SEO containers.

An arbitrary number of these containers can be layered together, so special-casing things seems bad.

I have a few ideas in mind of how to approach this, I just want to figure out a good solution that works well from an architectural point of view.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/76ba339712a2edbe505eeefaae249514badce858

**Comment by khalwat** [comment]
Took me a bit to think about this properly, and come up with a good solution... but this is fixed in SEOmatic 3.0.13
