### ISSUE TITLE
Why is Preview disabled when I disable "Add Social Media Preview Target"

### ISSUE THREAD

**Issue by vaughn-taylor** [nystudio107/craft-seomatic#596]
Andrew, when I toggle off "Add Social Media Preview Target", the "Preview/Share" buttons in an entry disappear all together. Maybe I don't completely understand what's going on here, or maybe it's a bug?

**Comment by khalwat** [comment]
Probably because you have no targets set up for previewing for that Section? Craft disables the Preview button if there are no preview targets set. Check your Section settings.

I think there was some kind of upgrade bug at some point that caused Craft to lose default preview targets; check the Craft CMS issues on Github

**Comment by vaughn-taylor** [comment]
Yes, this was correct. There were no default preview targets available. Thanks!
