### ISSUE TITLE
Feature Request: Make sameAsLinks bust cache when used for links in cached templates

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft-seomatic#60]
Using `{{ seomatic.site.sameAsLinks['twitter']['url'] }}` in my footer with `{% cache globally using key 'footer' %}` and changes to my **sameAsLinks** don't get updated.

Ideally, this would work exactly like global fields and trigger a cache clear.

**Comment by khalwat** [comment]
So without getting into a super-long explanation of how Craft's caching mechanism works, I think a more generic solution is in order. For instance, I use a FastCGI Cache... it'd be nice if *that* was busted when saving settings, too.

Craft keeps track of when to bust the cache by tracking elements; so if you change an Entry element, it knows to bust the cache. In SEOmatic's case, it's not using custom elements for anything. In theory, a faux element could be used, but it'd get pretty involved.

For now, since this information won't be changing very often, you can just clear the template caches after changing it.

c.f.: https://craftcms.stackexchange.com/questions/16395/define-elements-that-bust-cache-on-save

**Comment by jsunsawyer** [comment]
What if I was able to get something like a "lastUpdated" timestamp for the Social Media settings page? I could then pass that into my cache key and force cache clears that way without getting into any of the entry element stuff.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/fcdae2bd0a8db84800d310304db59d887ae9f30e
