### ISSUE TITLE
Sitemaps re-generate even though it's disabled in the plugin's settings

### ISSUE THREAD

**Issue by pierrestoffe** [nystudio107/craft-seomatic#604]
I don't want to re-generate the sitemap every time an entry is saved. It used to be the case, now it's taking too long and I realize we don't need it anymore since we're only editing the existing entries, not adding new ones.

So I turned off the "Regenerate Sitemaps Automatically" option in the Plugin Settings page, but it has no effect. Every time I save an entry the associated sitemap is re-generated.

We don't have any configuration for Seomatic in our config folder so I think the CP setting is maybe ignored.

Note that the "Sitemap enabled" lightswitch in the Content SEO of all sections is enabled, which is what I want. I need the existing sitemaps to stay where they are, but don't want to re-generate them anymore.

**Comment by khalwat** [comment]
Editing an existing entry will cause the date modified on it to change, which will cause it to bubble up to the top of the sitemap, so that Google knows to index the changed things first.

That said, the "Regenerate Sitemaps Automatically" setting should prevent sitemaps from being automatically regenerated:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/services/MetaBundles.php#L345

I just tested the setting locally, and after saving and edited entry, it is not regenerating the sitemap here.

So let's figure out what is different. What version of Craft CMS are you using, and what version of SEOmatic are you using?

**Comment by pierrestoffe** [comment]
Hi @khalwat, I see now that although it doesn't work in prod where I'm using Craft 3.4.11 and Seomatic 3.2.49, it does work correctly in my local environment with Craft 3.4.15 and Seomatic 3.2.51.

I can't update the prod now but in any case, if updating doesn't solve the issue once I can do it, my problem would then seem to be environment-related. So I'll close this issue for now. Thanks for getting back to me quickly.
