### ISSUE TITLE
Canonical tag in HTML and HTTP Header

### ISSUE THREAD

**Issue by keyurshah** [nystudio107/craft-seomatic#611]
Hello,

Looks like Seomatic is setting the canonical tag in the html and header.

In running an audit through sitebulb, it indicates that following [low grade warning](https://sitebulb.com/hints/indexability/canonical-tag-in-html-and-http-header
)

Wondering if this can set as an option to determine the output?

Thanks!

**Comment by khalwat** [comment]
I disagree with their recommendation:

> It is considered best practice to only specify canonicals using a single method on any given URL. This is because using both methods makes the configuration more open to human error.

> Imagine you implement a canonical on Page A which points to Page B as the canonical URL, using BOTH a tag in the <head> and in the HTTP header. Some time passes, and you introduce a new page, Page C, which will also become the new canonical for Page A. You change the canonical in the <head> but completely forget about the existence of the canonical in the HTTP header, and so do not change it.

This is not going to happen with SEOmatic, since it handles them identically. Google, also, doesn't care if you have them set in both places.

However, all of that said, if you really do want to turn it off, you can go to SEOmatic -> Plugin Settings -> Tags and turn off **HTTP Headers Enabled** setting.

**Comment by keyurshah** [comment]
thanks for your insight! makes perfect sense
