### ISSUE TITLE
robots none on exception templates

### ISSUE THREAD

**Issue by bymayo** [nystudio107/craft-seomatic#627]
We've had a **massive** issue hit our site where our homepage got a 500 error in production due to an image transform error.

Because of this, it seems like the meta data was cached with `<meta name="robots" content="none">`. Looking through the code I can see:

```
    public function prepForRender(&$data): bool
    {
        $shouldRender = parent::prepForRender($data);
        if ($shouldRender) {
            // Set meta robots tag to `none` for http status codes >= 400
            if (Craft::$app->getResponse()->statusCode >= 400) {
                $data['content'] = 'none';
            }
        }

        return $shouldRender;
    }
```

This is the only reason I can see why our page got a robots of none attached to it. But because we fixed the issue, then never resaved that entry (Or clear the cache for SEOmatic Meta Caches) this meta data has sat on our site for over a week now, resulting in the site not being indexed.

Is there any reason why this code would be in there? Speaking to our SEO team, theres no benefit to telling exception templates not to index using robots.

But also, if you think it's better to keep it in. Is there no way of fixing this so that it gets cleared once the errors are resolved. Without having to think to save the entry, or clearing Meta caches.

Craft CMS: 3.4.16
SEOmatic: 3.2.51
PHP: 7.1.33

**Comment by darylknight** [comment]
Guessing this might be related to https://github.com/nystudio107/craft-seomatic/issues/622

**Comment by khalwat** [comment]
I don't think it is related @darylknight

**Comment by khalwat** [comment]
@bymayo so in general, I would suggest that as part of your deployment process, you clear all caches on deploy. It will side-step issues like this (not just with SEOmatic).

The reason it sets it to `none` is that we don't want Google et al to index pages that have >= 400 as a status code.

Some crawlers do, some crawlers don't -- but there's never a case I can think of where we want search engines to index pages that are returning errors.

The issue here is a caching issue. IMO it should be fixed by doing what I mentioned above, clearing caches on deploy just as a best practice.

But something else that could be done is I could make the cache duration configurable, so it would _eventually_ become uncached and be regenerated.

Thoughts?

**Comment by khalwat** [comment]
@bymayo Will re-open if you decide you want the option of setting the cache duration that SEOmatic uses, file a FR for it and I can do it!

**Comment by bymayo** [comment]
@khalwat Sorry for not replying to this.

Yeah the cache duration does sound like a good idea, considering we didn't have any auto clearing of cache setup (We do now though!) It will just combat any issues arising like this, because not having our site indexed for over 7 days was not good, as we vanished from Google.

If you want me to test this feature out, let me know.

**Comment by khalwat** [comment]
Added in https://github.com/nystudio107/craft-seomatic/commit/422c66ff783f87d70309a8101292f1acd59fb1cc

<img width="1095" alt="Screen Shot 2020-05-18 at 4 35 18 PM" src="https://user-images.githubusercontent.com/7570798/82257640-632e3100-9926-11ea-8003-1d4d0bdec49a.png">
