### ISSUE TITLE
Content SEO settings not saving or retaining default values

### ISSUE THREAD

**Issue by brianlarson** [nystudio107/craft-seomatic#642]
After editing Content SEO settings for a Section the Main Entity and Robots values do not seem to retain their values and Robots appears to be stuck for just one of my sections in Content SEO. Subsequently when creating a new Entry in this section (entitled _Pages_) the default Entity value shows up as _(unknown)_ and needs to be set to _WebPage_ manually. This value when saved is retaining in the new Entry. However, in the Robots select menu the default value is blank instead of being set to All. When manually selecting the All value for Robots and saving the Entry it is not retained and shows up as blank again and on the front end it is set to None (`<meta name="robots" content="none">`). Setting Robots to a different value however is retained in the Entry. [Here is a Dropbox link to a 2 min. screen recording demonstrating these issues](https://www.dropbox.com/s/i8lg9whtax5a2s2/Screen%20Recording%202020-05-19%20at%201.14.52%20PM.mov?dl=0). These issues seem to be happening across all Sections on my project as well.

_All sections in Content SEO. Other sections are showing All as the Robots default but Pages is stuck on none even though when opening and saving it is set to All like the others:_
![Screen Shot 2020-05-19 at 1 28 22 PM](https://user-images.githubusercontent.com/436809/82364257-a7780a80-99d4-11ea-897f-ed98729f7c1b.jpg)

_Robots default value when creating a new Entry in the Pages section shows up as blank. When changing it to All and saved it does not retain the value. Other values however can be retained:_
![Screen Shot 2020-05-19 at 1 27 46 PM](https://user-images.githubusercontent.com/436809/82364263-a8a93780-99d4-11ea-89d3-248682908fc7.jpg)

_The default Entity should be WebPage but shows up as (unknown). Manually changing this to WebPage and saving does retain the value. I believe it should not need to be set manually though:_
![Screen Shot 2020-05-19 at 1 27 25 PM](https://user-images.githubusercontent.com/436809/82364265-a8a93780-99d4-11ea-9382-437a2a1739fa.jpg)

**Comment by khalwat** [comment]
So this is all actually intentional, but not optimal. In the video, we're conflating the Content SEO settings with the field settings in an SEO Settings field.

The SEO Settings field is intended to be an _override_ so you _should_ be seeing blank values for just about everything. It's a bug that "unknown" is being displayed, that should just be displaying an empty value too.

In general, I discourage the use of the SEO Settings field unless your client really truly does need to override the mappings you've set up via Content SEO (and in that case, provide them access only to the things that they need to change, like perhaps the SEO Title or SEO Description).

https://nystudio107.com/docs/seomatic/Fields.html#seo-settings-field

I plan to address it in this issue, that will make the override nature of the field more clear:

https://github.com/nystudio107/craft-seomatic/issues/535

**Comment by khalwat** [comment]
The reason it "reverts" to blank when you save them is if the setting is the same as the Content SEO setting, it is not doing anything. It's setting it to the same value, so it is not overriding anything.

**Comment by khalwat** [comment]
Related: https://github.com/nystudio107/craft-seomatic/issues/643
