### ISSUE TITLE
Values from some fields are not outputting correctly

### ISSUE THREAD

**Issue by zizther** [nystudio107/craft-seomatic#669]
I have noticed the output from a couple of fields are not working correctly.

I have the creator `Entity Name` set to `{{ siteName }}`
This outputs correctly in a view template, but does not output correct in the humans.txt file.

I have the creator `Entity URL` set to `$DEFAULT_SITE_URL` (This field accepts ENV vars I presume as it has an option to select them if you start typing)
This outputs the input value, rather than getting the value of the ENV var.
This does not output correctly in the template view or humans.txt for example.

**Comment by khalwat** [comment]
So I spent a bit of time looking into this, only to realize that this is expected behavior.

The way SEOmatic work is that it injects all of its variables into your templates in unparsed form. This is so that you can freely modify them as you see fit, as well as modifying other variable that they may access.

It's not until the metadata is actually rendered that they are parsed as Twig templates / environment variables. This is the way all of the SEOmatic variables work.

If you need the actual parsed value, you can use `.parsedValue('valueName')`, e.g.:

```twig
{{ seomatic.site.parsedValue('siteName') }}
```

https://nystudio107.com/docs/seomatic/Using.html#seomatic-variables
