### ISSUE TITLE
seomatic json-ld image transforms error

### ISSUE THREAD

**Issue by csgrant83** [nystudio107/craft-seomatic#671]
Checking web.log, was finding a number of seomatic errors related to incorrect content in json-ld fields. Checking into it I found a number of SEO image transforms with urls ending in `.jpeg?mtime=1589315584` or `index.php?p=actions/assets/generate-transform&transformId=1`

Seems like transform code is getting its way into the url. Is this an issue on my end or the plugin, or craft?

SEOmatic v.3.3.8

**Comment by khalwat** [comment]
I'm unclear what the issue here is? Is something not displaying correctly on the frontend?

**Comment by csgrant83** [comment]
The issue is the URL being given for the SEO image includes transform information that should not otherwise be there. The seomatic plugin is giving me an error stating that the URL is invalid for JSON-LD format, which is correct from my understanding—the URL should be the final transformed image and not include transform code.

Expected:
`mywebsite.com/images/image.jpeg`

What I am getting:
`mywebsite.com/images/image.jpeg?mtime=1589315584`
or
`mywebsite.com/index.php?p=actions/assets/generate-transform&transformId=1`

From an actual page JSON payload:

`           
 "image": {
                "@type": "ImageObject",
                "url": "https://mywebsite.com/assets/images/manufacturing/_1200x630_crop_center-center_82_none/cable-assembly.jpg?mtime=1588369193"
            },
`

There is no display issue on the front end.

**Comment by khalwat** [comment]
This is part of the normal Craft operation for image transforms. SEOmatic will by default resize your SEO images using Craft CMS image transforms, so that they are sized appropriately for the social media platform.

The transform URLs mean that the transform hasn't happened yet. Once it does, a regular image URL will be swapped in for it.

You can disable the image resizing for SEO images if you like via the **Transform** settings in SEOmatic, but it doesn't sound like it's causing an actual issue here.
