### ISSUE TITLE
Query strings still appearing within the rel=next and rel=previous link tags

### ISSUE THREAD

**Issue by mtwalsh** [nystudio107/craft-seomatic#692]
### Describe the bug
Query strings are still appearing within the `rel=next` and `rel=previous` link tags in the head (generated by the paginate helper) when a page is later requested without a query string.

### To reproduce
Steps to reproduce the behaviour:
1. Go to a paginated section index page (that contains `{% do seomatic.helper.paginate(...) %}`) with a query string, I'm using `https://www.domain.com/some-section?token=blahblah`
2. If you view the source you'll notice the query string has been included like so: `<link href="https://www.domain.com/some-section/p2?token=blahblah" rel="next">`, this is expected.
3. Now access the same URL _without_ the query string and the same `<link>` tag _with_ the query string is output, this is not expected, the links should no longer include the query string.

### Expected behaviour
Whilst it is expected that query strings should be passed through in paging links they should not remain in place when the page is subsequently request without a query string.

### Versions
- Plugin version: 3.3.8
- Craft version: 3.4.25

**Comment by khalwat** [comment]
This is probably because the SEOmatic cache does not take query strings into account when caching the SEO data for the request (otherwise you'd end up with some fairly monstrous caches with all of the various query strings that can be passed in).

**Comment by mtwalsh** [comment]
OK, that makes sense. How about adding a check within the paginate helper to see whether the request has a query string and then ensuring if it does not, that the `<link>` tags it generates are also stripped of query strings?

**Comment by khalwat** [comment]
This should all be sorted now, it preserves query strings in the pagination.

**Comment by mtwalsh** [comment]
Thanks @khalwat!

**Comment by masonry47** [comment]
Hi there, we are seeing this issue as well.  Was it addressed in an update? It seems the fix was in 3.3.39 but it seems that since the dynamic metadata gets cached, the rel="next" link tag just shows whatever is cached which would be the wrong url at times.  

So for example if you went to https://url.com/resources/

The next link would be <link href="https://url.com/resources/p2/" rel="next">

Then if you went to "https://url.com/resources/?topic=news"

The next link should be <link href="https://url.com/resources/p2/?topic=news" rel="next">

But instead it shows <link href="https://url.com/resources/p2/" rel="next">, because that is stored in the cache. If you clear the metadata cache, the correct "next" link will show, but then it is cached, which would make the opposite scenario, show the incorrect "next" link. 

Thanks for any info!

**Comment by khalwat** [comment]
@masonry47 separate issue -- can you open a new issue please?
