### ISSUE TITLE
Robots.TXT isn't updating + Issue with "noindex" tag being added

### ISSUE THREAD

**Issue by wakemanaust** [nystudio107/craft-seomatic#703]
### Describe the bug
Our website was recently hacked. Google, for a time, was indexing some random website that was not ours and we're trying to fix the issue. I've resubmitted their sitemap, however, when I go to submit the home page directly via Search Console, Google is telling me that there is a "noindex" tag on the page.

When you inspect the page, there is no "noindex" tag to be found.

Secondly, I've made some changes to our robots.txt file that are not being reflected.

**Comment by wakemanaust** [comment]
An update on this issue. 

Despite the plugin being configured to allow crawling and indexing, SEOmatic is adding this tag to each page:

<meta name="robots" content="none"> which translates to No index, no follow.

**Comment by michtio** [comment]
@wakemanaust are you sure your environment is set to production, and not staging?

**Comment by khalwat** [comment]
This is almost always due to the setup not being configured correctly. SEOmatic automatically sets it to <meta name="robots" content=“none”> if:

— devMode is on
— the environment is set to dev or staging

It does this to prevent Google et al indexing pages on development/staging sites inadvertently, which is a much stickier problem to undo.

You can see more on how SEOmatic should be configured for various environments here:

https://nystudio107.com/docs/seomatic/Configuring.html#multi-environment-config-settings

Go to the Dashboard page, and click on the (i) next to Environment, and it’ll show you some information:

<img width="1016" alt="Screen Shot 2020-08-03 at 11 50 16 AM" src="https://user-images.githubusercontent.com/7570798/89203064-ea805d80-d581-11ea-8785-df9df2bf6483.png">

My guess is that they either have devMode enabled, or the .env file for the product has environment=dev in it
