### ISSUE TITLE
Text not filtered when setting the meta seoTitle 

### ISSUE THREAD

**Issue by ashleybaird** [nystudio107/craft-seomatic#727]
### Describe the bug
When you set the seoTitle using seomatic.meta.seoTitle, the text inside of that is not filtered. If the title is set using user input, that input can run functionality and display it in the payload.

### To reproduce
1. Use seomatic.meta.seoTitle and set the title with functionality such as {{7*7}}
2. Reload the page and look to see what the title is in the payload in the Web Inspector

### Expected behaviour
The text should be a string where no functionality is run.

### Versions
- Plugin version: 3.3.16
- Craft version: 3.3.19

**Comment by khalwat** [comment]
This is normal and expected behavior. SEOmatic parses the values it uses as Twig templates. In places where you set this manually to user input, you'll need to filter it as appropriate.

I've added a Twig function `seomatic.helper.sanitizeUserInput ` to make that easier for you: https://github.com/nystudio107/craft-seomatic/commit/93ceb1a2c78662cc14a176cb21a5bb67f135515a
