### ISSUE TITLE
Very high, intermittent TTFB (30+ seconds) on MetaContainers service

### ISSUE THREAD

**Issue by ammonhaggerty** [nystudio107/craft-seomatic#728]
I'm seeing an intermittent issue where MetaContainers services are causing the site to hang for 30+ seconds before loading. The behavior seems to surface somewhat randomly - every 2-3 page loads. Otherwise, the time is just under 1 second (which still seems high).

### Screenshots
![timeline](https://user-images.githubusercontent.com/597849/91104425-a46b6680-e622-11ea-89d3-1714c879c671.png)
![profiling](https://user-images.githubusercontent.com/597849/91104427-a503fd00-e622-11ea-8795-1e0af90fdefa.png)

### Versions
- Plugin version: 3.3.16
- Craft version: 3.5.5

**Comment by ammonhaggerty** [comment]
Update: I've continued to hunt for the problem and still stumped. I deleted the Vendor directory, updated composer, and updated Craft. I cleared all the SEOMatic-related caches and reviewed all the cache/template setting. FWIW, I resolved the errors that are seen in the screenshots above, and there's no difference.

**Comment by khalwat** [comment]
In local dev, it's normal for it to be a little slow, because of all the logging, and because SEOmatic's caches only last 30 seconds.

However, if you're saying it takes 30 seconds for a page to load, something is wrong -- it's almost always going to be something with the devops end of things, perhaps an image transform that isn't working, or the like.

So given that this is typically an environmental issue, and not a bug in SEOmatic -- tell me more about the environment. Is it local or production, what are you running, etc.?

**Comment by ammonhaggerty** [comment]
It's in our prod environment. It's running though Cloudflare and, as far as I can tell, all the caching settings are default. It's a fairly vanilla Craft config — no overrides for prod. I do have quite a few plugins - here are ones that could have an impact on content rendering: S3, Asset Rev, Contact Form, Cookies, Imager X, Inlin, Retcon, SEOmatic, Sprout Redirects. 

As for image transforms, I did have an issue within SEOMatic where the company logo was an SVG and was throwing a transformation error, but this has since been resolved as I replaced it with a PNG. I've double checked all the SEO images used. I'm using Imager X for all other image transformations on the site. The issue is consistent across all pages in the site. There are only two images used in the SEOMatic settings (company logo and a universal SEO image) — all other images are defined in page/section config. 

As of today I'm on SEOMatic 3.3.17. I updated all plugins to their latests version this morning.

Let me know if there's any specific environment settings I can share. Thank you for any insights!

**Comment by khalwat** [comment]
Do you also experience this very high page load times on the staging server, or in local dev for this project?

**Comment by ammonhaggerty** [comment]
My local dev environment does not have the issue - the same services are showing 200-400ms.

**Comment by ammonhaggerty** [comment]
After some additional investigation, I think I'm seeing the same issue locally, except that it's resulting in a Gateway Timeout rather than a slow load. It's intermittent, so it seems to be happening in maybe 1/10 page loads.

**Comment by khalwat** [comment]
I haven't experienced a similar slowdown on a number of sites that are using SEOmatic, so I'm going to assume this is something specific to your project or the local environment its running in.

At this point, I'd try turning off the image transforms for social images, for instance, to see if you can help narrow down what's going on.

I'd also check _all_ of your log files, searching for errors that might point to clues. This can help you with that:

https://nystudio107.com/blog/zen-and-the-art-of-craft-cms-log-file-reading

**Comment by ammonhaggerty** [comment]
Thanks @khalwat! I can't find any reference to where image transforms can be disabled in SEOMatic.

**Comment by khalwat** [comment]
SEOmatic -> Global SEO -> General -> Transform SEO Image
SEOmatic -> Global SEO -> General -> Transform Twitter Image
SEOmatic -> Global SEO -> General -> Facebook OpenGraph Image Source

SEOmatic -> Content SEO -> XXX Section -> General -> Transform SEO Image
SEOmatic -> Content SEO -> XXX Section -> General -> Transform Twitter Image
SEOmatic -> Content SEO -> XXX Section -> General -> Facebook OpenGraph Image Source

**Comment by ammonhaggerty** [comment]
After turning off transforms I'm getting this error: 

142 | 12:38:02.513 | < 22s 781ms > | error | nystudio107\seomatic\helpers\MetaValue::parseMetaString | Error rendering `{seomatic.helper.socialTransform(5178, "base", 1, "crop")}` -> An exception has been thrown during the rendering of a template ("Error executing "GetSessionToken" on "https://sts.amazonaws.com"; AWS HTTP error: cURL error 6: Could not resolve host: sts.amazonaws.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)") in "__string_template__b6e69f089610c76c1b56d9e6c2ff8f7bc2441f8faad6c32f1136c01ebcdf7382" at line 1. - {seomatic.helper.socialTransform(5178, "base", 1, "crop")}

Any ideas?

**Comment by khalwat** [comment]
Check out the url they note:

https://curl.haxx.se/libcurl/c/libcurl-errors.html

Also if it rendered that string, it looks like transforms are still on. But I think you found the source of the issue.

Seems like maybe the wrong region is set? Seems related:

https://github.com/craftcms/aws-s3/issues/16

**Comment by baileydoestech** [comment]
Possibly related (was about to raise a seperate issue but will comment here)

We have seen a fairly large increase in the load times of our production site since updating to Craft 3.5 (along with latest SEOMatic at the same time). Times have gone from around 500-600ms load time to over 1000ms.

![image](https://user-images.githubusercontent.com/3185073/91450417-31f1c500-e874-11ea-88c3-80b21953a5cd.png)

Not reports of slowness on the Craft issue list but noticed this bug could be related, in the profiler we have a consistently high duration for the following SEOMatic items:

![image](https://user-images.githubusercontent.com/3185073/91450612-62396380-e874-11ea-8036-f67c97743379.png)

**Comment by khalwat** [comment]
@lukebailey Sounds entirely unrelated. 

One other change in Craft 3.5 is that the template caches were moved to use the Yii2 cache (which is what SEOmatic uses as well).

Ensure that the data caches are not being cleared erroneously on your site, because that long timing your seeing to me is indicative of an uncached render. Subsequent renders for the same page should then be significantly quicker.

If you have a large site, I'd suggest using Redis for your caching method. Feel free to start a new issue if you want to continue the discssion.

**Comment by ammonhaggerty** [comment]
@khalwat - thanks for your help and insights! The issue turned out to the an intermittent S3 authentication failure and was hanging on the asset query. Not sure why the SEOMatic services take the heat in the profiler, but we now have it resolved!

**Comment by khalwat** [comment]
Great news @ammonhaggerty !
