### ISSUE TITLE
Different index / sitemap setting for different entry type on Channel/Struture

### ISSUE THREAD

**Issue by ryotadialpad** [nystudio107/craft-seomatic#740]
### Question
Is there any way to enable indexing and sitemap on one of entry type on Channel/Structure and disable it on other entry type?

we have post and post author built using same structure and section is index and sitempa enabled, but need to disable it just for post author. Is there ability to this within Seomatic's UI or is it possible to do so with API?

**Comment by khalwat** [comment]
The problem is, these URLs are still publicly available.

Google will eventually find them and index them anyway. Just not listing them in the sitemap isn't going to hide them from Google, unless you specifically set the `robots` to `none` for these as well (which will automatically exclude them from the sitemap).

You can do this by either changing the settings on a per-entry type basis in Content SEO or by using an SEO Settings field.

The dropdown in the upper-left corner of the Content SEO page lets you switch between settings for different entry types.
