### ISSUE TITLE
Bug in product availability after fixing #780

### ISSUE THREAD

**Issue by VBMart** [nystudio107/craft-seomatic#797]
### About the bug
Product availability is OutOfStock for Unlimited products.
There is a bug in commit: [Added better checks for `InStock` for Product JSON-LD schema](https://github.com/nystudio107/craft-seomatic/commit/8cb459d288104eefd50d8bd4a9c73fa646e64ae8)

There is no **unlimitedStock** property in Product. Product has **hasUnlimitedStock** property.

### Versions
- Seomatic version: 3.3.24
- Craft version: 3.5.16
- Craft Commerce version: 3.2.12

**Comment by khalwat** [comment]
This is fixed in https://github.com/nystudio107/craft-seomatic/commit/22ac47f108fbbc37c64ea7726bfcc88372fcdba8

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.2.27",
```

Then do a `composer update`

You will also need to delete the `seomatic_metabundle` table for your Products so that SEOmatic can re-populate it with the updated code
