### ISSUE TITLE
Tracking Scripts tab blanco without admin rights

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft-seomatic#82]
Users who are not admin, but do have full access to all SEOmatic options are not able to see the options in the Tracking Scripts tab in SEOmatic.

Craft edition & version | **Craft Pro 3.0.3.1**
SEOmatic | **3.0.0**

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/aa3908d6b8793ad15c5a8caf5a6a3bc3c277ea46

**Comment by boldenamsterdam** [comment]
Hi @khalwat 

I installed the new update and tested if the issue was solved but it looks like the issue is still playing.
Clearing the caches didn't help.

**Comment by khalwat** [comment]
That's... very strange. Investigating.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/1046aa739860abdeb1fcba2c8f5b7115d1c9c221

It ends up being a silly regression where the tracking scripts sub-properties weren't properly added as permissions. I set up a test case, here are the permissions:

![google chromescreensnapz1143](https://user-images.githubusercontent.com/7570798/39200658-bfa6e112-47ba-11e8-925a-82fcc320288e.png)

...and this is what the non-admin user is able to see:

![google chromescreensnapz1142](https://user-images.githubusercontent.com/7570798/39200668-c9c9f6b6-47ba-11e8-9f2c-99896a2f6516.png)
