### ISSUE TITLE
Outputting Keywords in a template

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#820]
### Question
My seo field handle is `seo` and I'm trying to output the keywords into an xml template but nothing is getting output. Looking at the source of an entry I can see keywords in the keyword meta tag but in the xml feed those are not getting output.

What I've tried based on the docs https://nystudio107.com/docs/seomatic/Fields.html#template-access

```twig
{{entry.seo.metaGlobalVars.seoKeywords }}
```

and

```twig
{{entry.seo.metaGlobalVars.parsedValue('seoKeywords') }}
```

### Additional context
Add any other context or screenshots about the support request here.

**Comment by khalwat** [comment]
Yeah this isn't going to work... because the SEO Settings field is only one of many meta containers that are combined together to generate the keywords (and other things).

I'd recommend against it, but if you _really_ want to do this, you'd probably need to use the `seomatic.helper.loadMetadataForUri()` function: https://nystudio107.com/docs/seomatic/Using.html#helper-functions-seomatic-helper

...and then look at the `{{ seomatic.meta.keywords }}`
