### ISSUE TITLE
SEOmatic shouldn’t be running the queue

### ISSUE THREAD

**Issue by brandonkelly** [nystudio107/craft-seomatic#845]
There’s no point in adding a job to the queue if you’re going to run it immediately. If you really want something to happen _right away_, then make it a service method and call it. By adding the job to the queue and running the queue, you’re risking triggering other queue jobs as well (e.g. https://github.com/craftcms/cms/issues/6383#issuecomment-786949173), which may not be appropriate to run in a web request. (Which is why content-heavy sites are often encouraged to run the queue via a daemon or cron job.

https://github.com/nystudio107/craft-seomatic/blob/419d3c81ec7e9b47ef1ed0d58eb155b88a46936a/src/models/SitemapTemplate.php#L162

**Comment by khalwat** [comment]
Well, it normally needs to be run as a queue job because it can be so long/intensive.

In this case, a request is coming in for a sitemap that doesn't exist yet, and that sitemap is generated via queue job.

So in an attempt to service that immediately if possible, it pushes it and then runs the queue.

Ideally I just want one code path here.

**Comment by khalwat** [comment]
Since this is an edge case that only exists as a fallback, gonna close this.

Eventually it should be refactored to work more like `craft\services\Elemenst::resaveElements()`. it fires before/after events for each individual element, and sets a position property on the events. So the `ResaveElements` queue job can listen to the before event and call `setProgress()` based on `$event->position`
