### ISSUE TITLE
Configure SEO image transform location

### ISSUE THREAD

**Issue by matthillco** [nystudio107/craft-seomatic#851]
### Is your feature request related to a problem? Please describe.
I'm using Craft and Blitz to output a self-contained static site for later deployment on Netlify or Vercel.

I discovered that the location of SEOMatic social image transforms is problematic for this use case, as they are stored relative to their source volume folder. As I'm only using the source folder to generate transformed images in a _different_ output folder, I don't want to include the source folder in the final static output.

It would therefore be useful to have these transformed images stored in a user specified folder instead. I'm thinking along the lines of how Blitz and Imager require a folder to be specified in their respective configs, or how Asset volume paths are defined.

### Describe the solution you would like
Allow the location of SEOMatic image transforms to be specified by config file, or using a field in the control panel UI.

**Comment by khalwat** [comment]
Yes, SEOmatic uses Craft's built-in image transforms to do the social media image transforms.

This is unlikely to change, because we want to leverage the system as much as possible, and do things in a standard way.

However, you can disable the image transform scaling, and/or provide your own custom SEO image however you like (including using Imager), because you can set it to "Custom URL" and put Twig code in the field as per: 

https://nystudio107.com/docs/seomatic/Configuring.html#content-seo

**Comment by matthillco** [comment]
Ah that's great thanks, I didn't realise that was possible. I'll try it that way, cheers.

**Comment by matthillco** [comment]
Just wanted to add that I'm now using a twig include in the Custom URL field, and that include does all the image processing using Imager. Works brilliantly! Thank you so much for making such a flexible system.

**Comment by khalwat** [comment]
Awesome, glad to hear it!
