### ISSUE TITLE
Setting unknown property: nystudio107\seomatic\models\MetaBundle::title

### ISSUE THREAD

**Issue by mbanta88** [nystudio107/craft-seomatic#88]
https://www.useloom.com/share/ab6863763bf7490a878592cf6fad1017
---------------

2018-04-24 16:45:27 [75.50.55.134][1][39d75da9258539b5d0389dce43b111c5][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: nystudio107\seomatic\models\MetaBundle::title in /home/web/vhosts/stoneridge/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /home/web/vhosts/stoneridge/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('title', '')
#1 /home/web/vhosts/stoneridge/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(nystudio107\seomatic\models\MetaBundle), Array)
#2 /home/web/vhosts/stoneridge/vendor/nystudio107/craft-seomatic/src/models/MetaBundle.php(133): yii\base\BaseObject->__construct(Array)
#3 /home/web/vhosts/stoneridge/vendor/nystudio107/craft-seomatic/src/fields/SeoSettings.php(180): nystudio107\seomatic\models\MetaBundle::create(Array)
#4 /home/web/vhosts/stoneridge/vendor/craftcms/cms/src/base/Element.php(1904): nystudio107\seomatic\fields\SeoSettings->normalizeValue('{"title":"","de...', Object(craft\elements\Entry))
#5 /home/web/vhosts/stoneridge/vendor/craftcms/cms/src/base/Element.php(761): craft\base\Element->normalizeFieldValue('seo')
#6 /home/web/vhosts/stoneridge/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(587): craft\base\Element->__get('seo')
#7 /home/web/vhosts/stoneridge/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(147): nystudio107\seomatic\services\MetaContainers->loadFieldMetaContainers()
#8 [internal function]: nystudio107\seomatic\services\MetaContainers->nystudio107\seomatic\services\{closure}(Object(yii\caching\FileCache))
#9 /home/web/vhosts/stoneridge/vendor/yiisoft/yii2/caching/Cache.php(575): call_user_func(Object(Closure), Object(yii\caching\FileCache))
#10 /home/web/vhosts/stoneridge/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(153): yii\caching\Cache->getOrSet('seomatic_metaco...', Object(Closure), 1, Object(yii\caching\TagDependency))
#11 /home/web/vhosts/stoneridge/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(227): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('contact', 1)
#12 /home/web/vhosts/stoneridge/vendor/nystudio107/craft-seomatic/src/Seomatic.php(659): nystudio107\seomatic\services\MetaContainers->previewMetaContainers('contact', 1, true)
#13 /home/web/vhosts/stoneridge/vendor/craftcms/cms/src/web/View.php(1225): nystudio107\seomatic\Seomatic->nystudio107\seomatic\{closure}('<span class="st...')
#14 /home/web/vhosts/stoneridge/storage/runtime/compiled_templates/c9/c9915cdc93998e14caf7ec186815069c8f9f74455ce8926c5f92e400f2212b46.php(618): craft\web\View->invokeHook('cp.entries.edit...', '<span class="st...')
#15 /home/web/vhosts/stoneridge/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_164b15694eda9b1337d4dc6e1e226a0715ca6356b1d331b539237f766270186f->block_details('<span class="st...', Array)
#16 /home/web/vhosts/stoneridge/vendor/twig/twig/lib/Twig/Template.php(255): Twig_Template->displayBlock('details', Array, Array, true)
#17 /home/web/vhosts/stoneridge/storage/runtime/compiled_templates/ec/ec7ac436f7d035f4b662788e5f76ae7fdba173790c6d8a870ca6628cdd5129c8.php(81): Twig_Template->renderBlock('details', Array, Array)
#18 /home/web/vhosts/stoneridge/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_745b2ba35ca24e7f456a272b718497d440ecfdfba9a15155fdcf37c1c0ea1d9b->doDisplay(Array, Array)
#19 /home/web/vhosts/stoneridge/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#20 /home/web/vhosts/stoneridge/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#21 /home/web/vhosts/stoneridge/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#22 /home/web/vhosts/stoneridge/storage/runtime/compiled_templates/c9/c9915cdc93998e14caf7ec186815069c8f9f74455ce8926c5f92e400f2212b46.php(62): craft\web\twig\Template->display(Array, Array)
#23 /home/web/vhosts/stoneridge/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_164b15694eda9b1337d4dc6e1e226a0715ca6356b1d331b539237f766270186f->doDisplay('[<span class="s...', Array)
#24 /home/web/vhosts/stoneridge/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#25 /home/web/vhosts/stoneridge/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#26 /home/web/vhosts/stoneridge/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#27 /home/web/vhosts/stoneridge/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#28 /home/web/vhosts/stoneridge/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#29 /home/web/vhosts/stoneridge/vendor/craftcms/cms/src/web/View.php(305): Twig_Environment->render('entries/_edit', Array)
#30 /home/web/vhosts/stoneridge/vendor/craftcms/cms/src/web/View.php(352): craft\web\View->renderTemplate('entries/_edit', '[<span class="s...')
#31 /home/web/vhosts/stoneridge/vendor/craftcms/cms/src/web/Controller.php(128): craft\web\View->renderPageTemplate('entries/_edit', '[<span class="s...')
#32 /home/web/vhosts/stoneridge/vendor/craftcms/cms/src/controllers/EntriesController.php(373): craft\web\Controller->renderTemplate('entries/_edit', Array)
#33 [internal function]: craft\controllers\EntriesController->actionEditEntry('contact', 2, NULL, NULL, NULL, Object(craft\elements\Entry))
#34 /home/web/vhosts/stoneridge/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#35 /home/web/vhosts/stoneridge/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#36 /home/web/vhosts/stoneridge/vendor/craftcms/cms/src/web/Controller.php(76): yii\base\Controller->runAction('edit-entry', Array)
#37 /home/web/vhosts/stoneridge/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
#38 /home/web/vhosts/stoneridge/vendor/craftcms/cms/src/web/Application.php(267): yii\base\Module->runAction('entries/edit-en...', Array)
#39 /home/web/vhosts/stoneridge/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/edit-en...', Array)
#40 /home/web/vhosts/stoneridge/vendor/craftcms/cms/src/web/Application.php(256): yii\web\Application->handleRequest(Object(craft\web\Request))
#41 /home/web/vhosts/stoneridge/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#42 /home/web/vhosts/stoneridge/web/index.php(21): yii\base\Application->run()
#43 {main}

**Comment by khalwat** [comment]
This ends up being this:

https://github.com/craftcms/cms/issues/2800

**Comment by khalwat** [comment]
Safeguards against this have been put into place in SEOmatic 3.0.3:

https://github.com/nystudio107/craft-seomatic/releases/tag/3.0.3

**Comment by mikefrancis** [comment]
I am halfway through an upgrade and have just installed `3.1.18.1` and am getting the same error, can't access the control panel or website.

Is there any way to suppress this? I don't mind starting from scratch inputting the content again if there's no way to migrate from v2 to v3 but at the moment I can't do anything.

**Comment by khalwat** [comment]
@mikefrancis Can you give me the details of the exact error, with a stack trace?

**Comment by khalwat** [comment]
@mikefrancis After installing SEOmatic, did you create any SEO Settings fields?

**Comment by mikefrancis** [comment]
The stack trace was pretty much the same as @mbanta88. This was after trying to upgrade a fully functioning Craft v2 site with SEOmatic data.

I've managed to get around it by doing something to the effect of:

```sql
UPDATE craft_fields SET settings = "{}" WHERE type = "nystudio107\seomatic\fields\Seomatic_Meta"
```

Means we lose all the settings but site is working again now 🤷‍♂️

**Comment by matt-adigital** [comment]
I'm also seeing this issue after upgrading from Craft 2 to Craft 3. Using SEOmatic 3.1.36 with Craft 3.0.35, the issue only shows on the dev site, but not on the live site. I've merged the live database into the dev site in attempts to fix this to no avail.

This error shows on every page of the dev site on front end and back whether logged in or not so I've had to disable SEOmatic to use the dev site. Any suggestions to fix this would be appreciated as I suspect that the error also exists silently on the live site and isn't being shown because dev mode is disabled.

The files and databases are the same between the 2 environments and the only seo field I have is a single Seo Settings field. This was the deprecated Craft 2 field but the live site allowed me to update this to the newer one before merging the databases in an attempt I made to fix this but without success.

The full stack trace is included below:

yii\base\UnknownPropertyException: Setting unknown property: nystudio107\seomatic\models\MetaSiteVars::additionalSitemaps in /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('additionalSitem...', Array)
#1 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(nystudio107\seomatic\models\MetaSiteVars), Array)
#2 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/nystudio107/craft-seomatic/src/models/MetaSiteVars.php(42): yii\base\BaseObject->__construct(Array)
#3 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/nystudio107/craft-seomatic/src/models/MetaBundle.php(166): nystudio107\seomatic\models\MetaSiteVars::create(Array)
#4 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/nystudio107/craft-seomatic/src/models/MetaBundle.php(136): nystudio107\seomatic\models\MetaBundle->normalizeMetaBundleData(true)
#5 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(120): nystudio107\seomatic\models\MetaBundle::create(Array, true)
#6 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(696): nystudio107\seomatic\services\MetaBundles->getGlobalMetaBundle(1)
#7 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(198): nystudio107\seomatic\services\MetaContainers->loadGlobalMetaContainers(1)
#8 [internal function]: nystudio107\seomatic\services\MetaContainers->nystudio107\seomatic\services\{closure}(Object(yii\caching\FileCache))
#9 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/yiisoft/yii2/caching/Cache.php(575): call_user_func(Object(Closure), Object(yii\caching\FileCache))
#10 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(206): yii\caching\Cache->getOrSet('seomatic_metaco...', Object(Closure), 1, Object(yii\caching\TagDependency))
#11 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(47): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('dashboard', '1')
#12 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/twig/twig/lib/Twig/ExtensionSet.php(339): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#13 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/twig/twig/lib/Twig/Environment.php(903): Twig_ExtensionSet->getGlobals()
#14 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/twig/twig/lib/Twig/Environment.php(923): Twig_Environment->getGlobals()
#15 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/twig/twig/lib/Twig/Template.php(367): Twig_Environment->mergeGlobals(Array)
#16 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#17 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#18 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#19 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('_components/wid...', Array)
#20 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/craftcms/cms/src/widgets/Feed.php(95): craft\web\View->renderTemplate('_components/wid...', Array)
#21 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/craftcms/cms/src/controllers/DashboardController.php(70): craft\widgets\Feed->getSettingsHtml()
#22 [internal function]: craft\controllers\DashboardController->actionIndex()
#23 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#24 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#25 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('index', Array)
#26 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#27 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('dashboard/index', Array)
#28 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('dashboard/index', Array)
#29 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#30 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#31 /srv/users/winander-leisure/apps/windermere-lakecruises-dev/public/index.php(21): yii\base\Application->run()
#32 {main}

Please let me know if you need anything else to find the cause of the issue.

**Comment by khalwat** [comment]
So this is actually a different error @matt-adigital -- can you please ensure that you've done a `composer update` on the local dev installation? It looks to me on the surface that you have new data (from the latest version of SEOmatic) that's being handled by an older version of SEOmatic where that property doesn't exist on the model.

**Comment by matt-adigital** [comment]
I ran composer update earlier but it didn't resolve the issue. However, I've just nuked the vendor folder and ran composer update again and it seems to have fixed it now. I guess there was something going on with the model as you've suggested. Thank you for your help.

**Comment by khalwat** [comment]
No worries. I'm always on the fence about whether it should try to "protect" against this type of thing. But at some point, I think we just need to keep the dependencies in sync. Composer doesn't always make that as easy as it should be. :)

**Comment by matt-adigital** [comment]
I find that it can be too easy to fall into the trap of trusting composer when checking version numbers between environments, especially when composer update doesn't report any issues either. Thanks again.

**Comment by khalwat** [comment]
I hear ya. My distrust has extended to the point where whenever I do an update, I do:

```
rm -rf vendor/ && rm composer.lock && composer update
```
