### ISSUE TITLE
Update from 3.4.0 to 3.4.1 shows Composer error

### ISSUE THREAD

**Issue by peteeveleigh** [nystudio107/craft-seomatic#886]
Attempting to update from 3.4.0 to 3.4.1 using `php craft update seomatic` and getting the following Composer error

> Problem 1
>     - Root composer.json requires nystudio107/craft-seomatic 3.3.41 -> satisfiable by nystudio107/craft-seomatic[3.3.41].
>     - nystudio107/craft-seomatic 3.3.41 requires nystudio107/craft-plugin-manifest ^1.0.4 -> satisfiable by nystudio107/craft-plugin-manifest[1.0.4] from composer repo (https://repo.packagist.org) but nystudio107/craft-plugin-manifest[1.0.0, 1.0.1, 1.0.2, 1.0.3] from composer repo (https://composer.craftcms.com) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.

Do I need to manually install the plugin-manifest also?

### Versions
- Plugin version: 3.4.0 ->  3.4.1
- Craft version: 3.6.13

**Comment by Timusan** [comment]
Experienced the same update error just now.

**Comment by ben-honcho** [comment]
Ditto

**Comment by khalwat** [comment]
So based on the error where it says:

> satisfiable by nystudio107/craft-plugin-manifest[1.0.4] from composer repo (https://repo.packagist.org) but nystudio107/craft-plugin-manifest[1.0.0, 1.0.1, 1.0.2, 1.0.3] from composer repo (https://composer.craftcms.com) has higher repository priority

That says to me the issue is that Craft is injecting their own Composer repo (to handle Craft plugins), and it has a higher priority:

https://getcomposer.org/repoprio

...because the version is tagged, and definitely there:

https://packagist.org/packages/nystudio107/craft-plugin-manifest

Seems like this is what should be happening:

> There are however a few cases where you may want to specifically load some packages from a given repository, but not all. Or you may want a given repository to not be canonical, and to be only preferred if it has higher package versions than the repositories defined below.

...and maybe it used to, but now:

> By default in Composer 2.x all repositories are canonical. Composer 1.x treated all repositories as non-canonical.

I will ping Pixel & Tonic on this one. It's possible that the repo just hasn't mirrored yet, or it's possible they need to manually tweak something on their end.

**Comment by khalwat** [comment]
Yep. The powers that be are addressing this.
