### ISSUE TITLE
Setting unknown property: nystudio107\seomatic\models\MetaSiteVars::facebookSiteVerification

### ISSUE THREAD

**Issue by denisyilmaz** [nystudio107/craft-seomatic#916]
### Describe the bug
After updating to SEOmatic 3.3.43 (from 3.3.35) we get the following error when saving an entry.
The erro appears in the queue when seomatic attempts to generate the sitemap:
```html
Generating homePage sitemap
ID	642
Status	Failed
Error	Setting unknown property: nystudio107\seomatic\models\MetaSiteVars::facebookSiteVerification
Progress	0%
```

### Versions
- Plugin version: 3.3.43
- Craft version: 3.6.17 (solo licence)

**Comment by khalwat** [comment]
This is likely because SEOmatic is not updated to the current version in all environments.

That's a property that was added, so it's in the database... but the error is showing you that the installed version of SEOmatic is not up to date.

Please verify the installed version of SEOmatic in all environments.
