### ISSUE TITLE
SEOMatic Not Respecting generateTransformsBeforePageLoad

### ISSUE THREAD

**Issue by bryantAXS** [nystudio107/craft-seomatic#949]
### Describe the bug
We're running SEOMatic on a site using Blitz, and we're seeing a bunch of performance issues because many of the pages across the site have "asset/generate-transform" URLs inside SEOMatic meta data.

On my end, I disabled Image Transforms on all SEOMatic Content settings, but I'm still seeing them in the HTML that's rendered. I'm setting `generateTransformsBeforePageLoad` to true, as mentioned in this thread (https://github.com/nystudio107/craft-seomatic/issues/490), but that's not being respected by SEOMatic.

I did see something about local versus remote assets. We have all of our SEO Images stored on S3... not sure if that's an issue?

### Expected behaviour
SEOMatic meta-data rendered without asset transforms

### Versions
- Plugin version: 3.3.48
- Craft version: 3.7.8

**Comment by khalwat** [comment]
SEOmatic uses image transforms for a number of things, and you don't want to disable the transforms in most cases.

With remote assets, SEOmatic does not immediately generate the transforms, because the operation can be quite lengthy.

However, the next time the page is loaded, the transforms should be generated already. I believe that Blitz has some magic that it does to ensure that `asset/generate-transform` URLs are never cached?

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/04ec5d2b0f25c674e45a0abe3c26c3028d703c88

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.0”,
```
Then do a `composer clear-cache && composer update`

**Comment by bencroker** [comment]
> However, the next time the page is loaded, the transforms should be generated already. I believe that Blitz has some magic that it does to ensure that `asset/generate-transform` URLs are never cached?

For the record, Blitz will not cache a page if its output contains any transform generation URLs with a simple string comparison.
https://github.com/putyourlightson/craft-blitz/blob/fac649e3857dcf74a73f803a148071fb643f78a2/src/services/GenerateCacheService.php#L258-L264

**Comment by bryantAXS** [comment]
Right @bencroker , and that's my problem here. All of the pages across the site have "asset/generate-transform" in the SEOMatic metadata, and thus none of the pages are being cached. 

Again, I have `generateTransformsBeforePageLoad` set to true, which alleviates this issue on other image transforms (using Imager-X), but not with SEOMatic metadata.

@khalwat is that use case being accounted for in 3.4.0?

**Comment by bryantAXS** [comment]
I just installed on our production machine and it still seems to be an issue.

**Comment by khalwat** [comment]
Yes, please try the above version

**Comment by khalwat** [comment]
@bryantAXS something isn't right, then. Because even if a page wasn't being cached because of that pending image transform, once the transform was made, it should no longer be a problem.

So maybe something isn't quite set up right with your asset volumes? My guess is that this is a general "Craft image transform" problem, and not an SEOmatic or Blitz problem.
