### ISSUE TITLE
Section SEO Image from field

### ISSUE THREAD

**Issue by baileydoestech** [nystudio107/craft-seomatic#95]
Hi Andrew, 

Firstly wanted to say great plugin, becoming a core part of any website built on Craft. 

I don't think this is expected behavior but we are having difficulties setting the SEO Image Source for a section. My understanding is that, unlike in Craft 2 version, you do not need to add the SEO field explicitly but instead configure this from the Content SEO areas of the CP. 

Below is an example of trying to set this on a section, I would have expected to see three options: 

1. Standalone Asset field
2. Asset field in a Matrix Block 
3. (hopefully) Asset field in a Super Table (3rd party plugin). 

![image](https://user-images.githubusercontent.com/3185073/39468348-75c92f8a-4d2a-11e8-9ac1-5b472a96edea.png)

Unfortunately we seen nothing:

![image](https://user-images.githubusercontent.com/3185073/39468318-5730e6c6-4d2a-11e8-9f9a-803e890fc473.png)

Versions:
Craft CMS 3.0.4
SEOMatic 3.0.9

**Comment by khalwat** [comment]
You will see any Asset fields that are in your Section in the list of fields that you can pull the images from.

You will _not_ however see any Asset fields that are embedded in Matrix blocks, nor any Asset fields that are embedded in SuperTable or other third-party fields.

This is the same as the Craft 2.x version in that regard, but in the Craft 3 version you can still do either via Twig in the fields:

https://github.com/nystudio107/craft-seomatic#content-seo-admincp-fields

The reason you don't see a UX for picking from an Asset embedded in a Matrix block is the UI would be fairly messy. You'd need some kind of a "block picker" to choose _which_ block type and then _which_ block to pull the image from.

**Comment by baileydoestech** [comment]
That makes sense, however when adding a vanilla asset field to a section the Content SEO drop-down for image is still blank (screenshot below):

**Comment by baileydoestech** [comment]
![image](https://user-images.githubusercontent.com/3185073/39518671-c811041c-4dfb-11e8-8ccc-3e3611041f45.png)

**Comment by wihodges** [comment]
So just to clarify, there is no way to pull the SEO description from matrix or supertable field? Am I understanding that correctly?

**Comment by wihodges** [comment]
Ok so scratch my previous comment, I see that I can set SEO Description Source to custom text and use a value like: {entry.customSupertable.customDescription }.  But for the SEO Image Source, I can't seem to do the same thing for the Custom URL value e.g. { entry.customSupertable.customImage.one() }.  Is it possible to do this?

**Comment by wihodges** [comment]
Woot nevermind, I figured it out. This works:
{seomatic.helper.extractTextFromField(object.entry.customSupertable.customImage.one().getUrl())}

**Comment by khalwat** [comment]
Awesome! Glad you got it sorted!

**Comment by wihodges** [comment]
Ok for posterity sakes: a couple more caveats to this custom image from Supertable field process. I noticed that I needed to update the Content SEO settings specifically for Twitter and Facebook settings panels for this to actually render in template - otherwise the default og site image still shows up. Not sure what the Content specific 'General' settings SEO image actually does b/c Facebook seems to override the generic og:Image...?  The strange thing is that the SEO preview panel in the entry showed the new custom image url for both twitter and facebook, but the sourcecode still have the generic site image url. Nevertheless setting all settings panels to custom url updates the source code correctly.

The next part that I'm still trying to figure out is if its possible to leverage the seomatic.helper.socialTransform to automatically transform these custom url images. I just can't imagine how the syntax of this would work. EG: {seomatic.helper**.socialTransform('facebook')**.extractTextFromField(object.entry.customSupertable.customImage.one().getUrl())}

Or if it's better to just add some custom Asset Transforms and call it via: .getUrl('customTwitterCrop')
