### ISSUE TITLE
Split Generate Sitemap into seperate Jobs

### ISSUE THREAD

**Issue by lenvanessen** [nystudio107/craft-seomatic#968]
### Is your feature request related to a problem? Please describe.
We run a large mutlisite, with over 70k entries. We have the servers to allow all the processes to have plenty of resources, but generating sitemaps takes a long time. I think we could greatly speed this up if we where to seperate the jobs into smaller jobs, for instance, per site, or per section. This would mean that Supervisord could spin up a seperate process and run the tasks alongside of each other.

Would something like this be possible?

**Comment by khalwat** [comment]
So.. I think a better question would be... is this desirable?

Sitemaps are about _discovery_. It's a way to point Google at URLs that are new, or have changed, and you want indexed.

If a URL isn't in a sitemap, it very well may be _discovered_ in another way, such as crawling pages, and index.

If a page is removed from the sitemap, it still remains in Google's index.

So the sitemap really are hints to Google in terms of what URLs its GoogleBot should spent its crawl budget on for your site.

What many people are doing--and this comes from Moz working with me on SEOmatic--is they have only the most recent XXX URLs in the sitemap. Since SEOmatic automatically sorts by last modified, this ensures that it is always aware of the URLs you want indexed or re-indexed.

There's no benefit to. maintaining a massive sitemap, assuming it is going to largely contain URLs that are already in Google's index anyway... and it can be counter-productive, in terms of giving Google too much to try to consume.

So while what you're discussing is _technically_ possible to do, it wouldn't be desirable, and could even be counter-productive.

We discuss this very topic in this podcast if you're interested: https://devmode.fm/episodes/web-developers-you-dont-know-seo
