### ISSUE TITLE
Site Name Position in Global SEO position doesn't change

### ISSUE THREAD

**Issue by thaoms** [nystudio107/craft-seomatic#99]
I would like to put sitename.be after the Event name.
But no matter what option I choose the sitename stays before.

`<title>sitename.be | Event Name</title>`

**Comment by khalwat** [comment]
Where are you attempting to make the change? In the SEO Content settings? Or in the SEO Global settings or...?

**Comment by khalwat** [comment]
So I tested this. In Global SEO, this is with the **Site Name Position** set to **Before**:

<img width="349" alt="google chromescreensnapz132" src="https://user-images.githubusercontent.com/7570798/39551492-2b22e8ea-4e33-11e8-97ce-eaeeb1491006.png">

...and this is with the **Site Name Position** set to **After**:

<img width="349" alt="google chromescreensnapz131" src="https://user-images.githubusercontent.com/7570798/39551506-374d209a-4e33-11e8-8542-b39c07891e17.png">

I also verified that it's displaying correctly on the frontend (and not just in the preview). How are you attempting to do this that it's not working as expected?

**Comment by thaoms** [comment]
Nothing special actually, just trying to change it in Global SEO. I'll try to get some more info.

**Comment by khalwat** [comment]
Any luck @thaoms ?

**Comment by jonXmack** [comment]
Try going to Utilities > Clear Caches, as well as SEOMatic > Content SEO and hitting "Save" on each content type, and then checking again. I was having the same issue but clearing the cache fixed it for me on the pages that aren't entry based, and saving the Content SEO types again fixed it on all the other pages.

**Comment by khalwat** [comment]
hrm. Very strange @jonXmack because it should be clearing the caches any time you save the Content SEO, it should be clearing all of the caches anyway (for this very reason).

I just double-checked the code, and it is indeed doing:

```
            Seomatic::$plugin->clearAllCaches();
```

...after saving the Content SEO. So I'm thinking re-saving the Content SEO settings is what fixed it for you. What version of SEOmatic did you start using when you first installed it? I'm wondering if there wasn't some stale data in there.
